# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.5782f,0.8159f,-1.1458f,0f,-0.8159f,0.5782f,4.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.4692f,0.8831f,-0.9153f,0f,-0.8831f,0.4692f,3.5714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,-0.2887f,0.9574f,-0.997f,0f,-0.9574f,-0.2887f,2.2659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,-0.2887f,0.9574f,-0.4641f,0f,-0.9574f,-0.2887f,2.3011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4986f,-0.0425f,-0.5215f,0f,0.0637f,0.9991f,2.4656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4986f,-0.0425f,-0.5215f,0f,0.0637f,0.9991f,2.4656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,-0.0314f,0.9995f,-0.1872f,0f,-0.9995f,-0.0314f,3.1555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.3112f,0.9503f,-0.6203f,0f,-0.9503f,0.3112f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}