# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0455f,0f,0f,0f,0f,-0.0293f,0.0349f,0.2632f,0f,0.0349f,0.0293f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0434f,0.0136f,0.001f,-0.0742f,0.0134f,-0.0433f,0.004f,1.2773f,-0.0022f,0.0035f,0.0453f,-1.1396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0434f,0.0136f,0.001f,-0.0763f,0.0134f,-0.0433f,0.004f,1.2874f,-0.0022f,0.0035f,0.0453f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0448f,-0.0078f,0.0017f,-0.9253f,-0.0078f,-0.0407f,0.0189f,0.9666f,0.0017f,0.0189f,0.0414f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0453f,0.004f,0f,0f,0.0037f,-0.0426f,0.0156f,0.4255f,-0.0014f,0.0155f,0.0428f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.1215f,0f,0f,0f,0f,1.112f,0.1454f,1.0397f,0f,-0.1454f,1.112f,3.274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.1215f,0f,0f,0f,0f,1.1213f,-0.0182f,1.604f,0f,0.0182f,1.1213f,3.2762f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.1215f,0f,0f,0f,0f,1.0044f,0.4989f,3.1421f,0f,-0.4989f,1.0044f,2.9254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.1215f,0f,0f,0f,0f,1.0044f,0.4989f,3.2032f,0f,-0.4989f,1.0044f,3.5211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.1215f,0f,0f,-0.6168f,0f,1.6789f,-0.0701f,2.982f,0f,0.1052f,1.1193f,3.4813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.1215f,0f,0f,0.6168f,0f,1.6789f,-0.0701f,2.982f,0f,0.1052f,1.1193f,3.4813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.1215f,0f,0f,0f,0f,1.1079f,0.1738f,2.2608f,0f,-0.1738f,1.1079f,3.9492f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.1215f,0f,0f,0f,0f,1.1193f,-0.0698f,1.7929f,0f,0.0698f,1.1193f,3.5689f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/100_locator_locator_cinematic