# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0504f,0f,0f,0f,0f,-0.0324f,0.0386f,0.2632f,0f,0.0386f,0.0324f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0481f,0.015f,0.0011f,-0.074f,0.0149f,-0.048f,0.0044f,1.2762f,-0.0024f,0.0039f,0.0502f,-1.1419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0481f,0.015f,0.0011f,-0.0763f,0.0149f,-0.048f,0.0044f,1.2874f,-0.0024f,0.0039f,0.0502f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0497f,-0.0086f,0.0019f,-0.9253f,-0.0086f,-0.0451f,0.021f,0.9666f,0.0019f,0.021f,0.0458f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0502f,0.0044f,0f,0f,0.0041f,-0.0472f,0.0173f,0.4255f,-0.0015f,0.0172f,0.0474f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.1237f,0f,0f,0f,0f,1.1208f,0.0812f,1.0388f,0f,-0.0812f,1.1208f,3.2773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.1237f,0f,0f,0f,0f,1.1218f,-0.0666f,1.6036f,0f,0.0666f,1.1218f,3.3038f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.1237f,0f,0f,0f,0f,1.0762f,0.3233f,3.278f,0f,-0.3233f,1.0762f,3.0758f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.1237f,0f,0f,0f,0f,1.0762f,0.3233f,3.2378f,0f,-0.3233f,1.0762f,3.6746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.1237f,0f,0f,-0.6181f,0f,1.6771f,-0.1128f,3.0293f,0f,0.1691f,1.1181f,3.5862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.1237f,0f,0f,0.6181f,0f,1.6771f,-0.1128f,3.0293f,0f,0.1691f,1.1181f,3.5862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.1237f,0f,0f,0f,0f,1.1222f,0.0584f,2.2621f,0f,-0.0584f,1.1222f,3.9778f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.1237f,0f,0f,0f,0f,1.1216f,-0.0693f,1.793f,0f,0.0693f,1.1216f,3.597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/108_locator_locator_cinematic