# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.051f,0f,0f,0f,0f,-0.0328f,0.0391f,0.2632f,0f,0.0391f,0.0328f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0487f,0.0152f,0.0012f,-0.074f,0.015f,-0.0486f,0.0045f,1.2761f,-0.0024f,0.004f,0.0508f,-1.1422f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0487f,0.0152f,0.0012f,-0.0763f,0.015f,-0.0486f,0.0045f,1.2874f,-0.0024f,0.004f,0.0508f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0502f,-0.0087f,0.002f,-0.9253f,-0.0087f,-0.0456f,0.0212f,0.9666f,0.0019f,0.0212f,0.0464f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0508f,0.0044f,0f,0f,0.0042f,-0.0478f,0.0175f,0.4255f,-0.0015f,0.0174f,0.048f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.1239f,0f,0f,0f,0f,1.1212f,0.079f,1.038f,0f,-0.079f,1.1212f,3.2798f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.1239f,0f,0f,0f,0f,1.1219f,-0.0683f,1.6028f,0f,0.0683f,1.1219f,3.3072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.1239f,0f,0f,0f,0f,1.0836f,0.2984f,3.2934f,0f,-0.2984f,1.0836f,3.0963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.1239f,0f,0f,0f,0f,1.0836f,0.2984f,3.2395f,0f,-0.2984f,1.0836f,3.694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.1239f,0f,0f,-0.6182f,0f,1.6771f,-0.1145f,3.0338f,0f,0.1718f,1.1181f,3.5989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.1239f,0f,0f,0.6182f,0f,1.6771f,-0.1145f,3.0338f,0f,0.1718f,1.1181f,3.5989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.1239f,0f,0f,0f,0f,1.123f,0.0446f,2.2617f,0f,-0.0446f,1.123f,3.9811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.1239f,0f,0f,0f,0f,1.1218f,-0.069f,1.7924f,0f,0.069f,1.1218f,3.6004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/109_locator_locator_cinematic