# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.65f,0.76f,-0.8945f,0f,-0.76f,0.65f,3.9286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.5841f,0.8117f,-0.6057f,0f,-0.8117f,0.5841f,3.5166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,-0.0844f,0.9964f,-0.4298f,0f,-0.9964f,-0.0844f,2.1995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,-0.0844f,0.9964f,0.0843f,0f,-0.9964f,-0.0844f,2.3441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4996f,-0.0231f,-0.0046f,0f,0.0347f,0.9997f,2.4961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4996f,-0.0231f,-0.0046f,0f,0.0347f,0.9997f,2.4961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.1685f,0.9857f,0.1855f,0f,-0.9857f,0.1685f,3.2388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.4775f,0.8787f,-0.298f,0f,-0.8787f,0.4775f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}