# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0621f,0f,0f,0f,0f,-0.0399f,0.0475f,0.2632f,0f,0.0475f,0.0399f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0592f,0.0185f,0.0014f,-0.0735f,0.0183f,-0.059f,0.0055f,1.2736f,-0.003f,0.0048f,0.0618f,-1.1474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0592f,0.0185f,0.0014f,-0.0763f,0.0183f,-0.059f,0.0055f,1.2874f,-0.003f,0.0048f,0.0618f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0611f,-0.0106f,0.0024f,-0.9253f,-0.0106f,-0.0554f,0.0258f,0.9666f,0.0023f,0.0258f,0.0564f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0618f,0.0054f,0f,0f,0.0051f,-0.0581f,0.0212f,0.4255f,-0.0018f,0.0211f,0.0583f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.0519f,0f,0f,0f,0f,1.0215f,0.251f,0.644f,0f,-0.251f,1.0215f,2.0387f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.0519f,0f,0f,0f,0f,1.046f,0.1111f,1.1696f,0f,-0.1111f,1.046f,1.9762f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.0519f,0f,0f,0f,0f,0.9968f,0.336f,2.7657f,0f,-0.336f,0.9968f,1.5998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.0519f,0f,0f,0f,0f,0.9968f,0.336f,2.7468f,0f,-0.336f,0.9968f,2.1612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.0519f,0f,0f,-0.5785f,0f,1.565f,0.1341f,2.5575f,0f,-0.2011f,1.0433f,2.0579f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.0519f,0f,0f,0.5785f,0f,1.565f,0.1341f,2.5575f,0f,-0.2011f,1.0433f,2.0579f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.0519f,0f,0f,0f,0f,1.0391f,0.1638f,1.8813f,0f,-0.1638f,1.0391f,2.4973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.0519f,0f,0f,0f,0f,1.0463f,0.1085f,1.3897f,0f,-0.1085f,1.0463f,2.2178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/211_locator_locator_cinematic