# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0599f,0f,0f,0f,0f,-0.0385f,0.0459f,0.2632f,0f,0.0459f,0.0385f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0572f,0.0178f,0.0014f,-0.0736f,0.0177f,-0.057f,0.0053f,1.2741f,-0.0029f,0.0046f,0.0597f,-1.1464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0572f,0.0178f,0.0014f,-0.0763f,0.0177f,-0.057f,0.0053f,1.2874f,-0.0029f,0.0046f,0.0597f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.059f,-0.0102f,0.0023f,-0.9253f,-0.0103f,-0.0535f,0.0249f,0.9666f,0.0022f,0.0249f,0.0545f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0597f,0.0052f,0f,0f,0.0049f,-0.0561f,0.0205f,0.4255f,-0.0018f,0.0204f,0.0563f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.047f,0f,0f,0f,0f,1.0057f,0.2911f,0.6212f,0f,-0.2911f,1.0057f,1.8974f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.047f,0f,0f,0f,0f,1.0386f,0.1322f,1.1429f,0f,-0.1322f,1.0386f,1.8244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.047f,0f,0f,0f,0f,0.9843f,0.3568f,2.7133f,0f,-0.3568f,0.9843f,1.4269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.047f,0f,0f,0f,0f,0.9843f,0.3568f,2.7072f,0f,-0.3568f,0.9843f,1.9859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.047f,0f,0f,-0.5759f,0f,1.5561f,0.1414f,2.5164f,0f,-0.212f,1.0374f,1.8875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.047f,0f,0f,0.5759f,0f,1.5561f,0.1414f,2.5164f,0f,-0.212f,1.0374f,1.8875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.047f,0f,0f,0f,0f,1.0303f,0.1865f,1.8535f,0f,-0.1865f,1.0303f,2.3399f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.047f,0f,0f,0f,0f,1.0409f,0.1125f,1.3629f,0f,-0.1125f,1.0409f,2.0639f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/214_locator_locator_cinematic