# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0462f,0f,0f,0f,0f,-0.0297f,0.0354f,0.2632f,0f,0.0354f,0.0297f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0441f,0.0138f,0.001f,-0.0742f,0.0136f,-0.044f,0.0041f,1.2771f,-0.0022f,0.0036f,0.0461f,-1.14f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0441f,0.0138f,0.001f,-0.0763f,0.0136f,-0.044f,0.0041f,1.2874f,-0.0022f,0.0036f,0.0461f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0455f,-0.0079f,0.0018f,-0.9253f,-0.0079f,-0.0413f,0.0192f,0.9666f,0.0017f,0.0192f,0.042f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0461f,0.004f,0f,0f,0.0038f,-0.0433f,0.0158f,0.4255f,-0.0014f,0.0158f,0.0435f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.0201f,0f,0f,0f,0f,0.8274f,0.5967f,0.5316f,0f,-0.5967f,0.8274f,1.2532f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.0201f,0f,0f,0f,0f,0.9724f,0.3084f,1.0189f,0f,-0.3084f,0.9724f,1.0919f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.0201f,0f,0f,0f,0f,0.8993f,0.4816f,2.4213f,0f,-0.4816f,0.8993f,0.5818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.0201f,0f,0f,0f,0f,0.8993f,0.4816f,2.4935f,0f,-0.4816f,0.8993f,1.1217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.0201f,0f,0f,-0.5611f,0f,1.439f,-0.3469f,2.2958f,0f,0.5203f,0.9593f,1.0534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.0201f,0f,0f,0.5611f,0f,1.439f,-0.3469f,2.2958f,0f,0.5203f,0.9593f,1.0534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.0201f,0f,0f,0f,0f,0.9674f,0.3237f,1.7198f,0f,-0.3237f,0.9674f,1.5823f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.0201f,0f,0f,0f,0f,1.0122f,0.127f,1.2373f,0f,-0.127f,1.0122f,1.3216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/229_locator_locator_cinematic