# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.7503f,0.661f,-0.47f,0f,-0.661f,0.7503f,3.7713f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.741f,0.6715f,-0.1013f,0f,-0.6715f,0.741f,3.4288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.2399f,0.9708f,0.476f,0f,-0.9708f,0.2399f,2.1955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.2399f,0.9708f,0.9164f,0f,-0.9708f,0.2399f,2.4974f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.5f,0.0074f,0.7847f,0f,-0.0111f,1f,2.6183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.5f,0.0074f,0.7847f,0f,-0.0111f,1f,2.6183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.4648f,0.8854f,0.736f,0f,-0.8854f,0.4648f,3.3834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.7041f,0.7101f,0.206f,0f,-0.7101f,0.7041f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}