# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0048f,0f,0f,0f,0f,-0.0031f,0.0037f,0.2632f,0f,0.0037f,0.0031f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0046f,0.0014f,0.0001f,-0.076f,0.0014f,-0.0046f,0.0004f,1.2863f,-0.0002f,0.0004f,0.0048f,-1.1206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0046f,0.0014f,0.0001f,-0.0763f,0.0014f,-0.0046f,0.0004f,1.2874f,-0.0002f,0.0004f,0.0048f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0048f,-0.0008f,0.0002f,-0.9253f,-0.0008f,-0.0043f,0.002f,0.9666f,0.0002f,0.002f,0.0044f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0048f,0.0004f,0f,0f,0.0004f,-0.0045f,0.0017f,0.4255f,-0.0001f,0.0016f,0.0045f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.0487f,0f,0f,0f,0f,0.8771f,0.5748f,-0.4045f,0f,-0.5748f,0.8771f,3.7022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.0487f,0f,0f,0f,0f,0.8662f,0.5911f,0.0276f,0f,-0.5911f,0.8662f,3.3994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.0487f,0f,0f,0f,0f,0.349f,0.9889f,0.7544f,0f,-0.9889f,0.349f,2.1593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.0487f,0f,0f,0f,0f,0.349f,0.9889f,1.1834f,0f,-0.9889f,0.349f,2.5192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.0487f,0f,0f,-0.5768f,0f,1.5729f,0.0089f,1.0324f,0f,-0.0133f,1.0486f,2.6327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.0487f,0f,0f,0.5768f,0f,1.5729f,0.0089f,1.0324f,0f,-0.0133f,1.0486f,2.6327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.0487f,0f,0f,0f,0f,0.5722f,0.8788f,0.9065f,0f,-0.8788f,0.5722f,3.4266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.0487f,0f,0f,0f,0f,0.7991f,0.679f,0.3447f,0f,-0.679f,0.7991f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/27_locator_locator_cinematic