# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-1f,0f,0f,0f,0f,0.7196f,-0.6944f,0.3531f,0f,-0.6944f,-0.7196f,-0.2552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.9543f,-0.2979f,-0.0226f,-0.1208f,-0.2982f,0.9543f,0.0168f,1.6324f,0.0166f,0.0228f,-0.9996f,-0.4993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.9543f,-0.2979f,-0.0226f,-0.1212f,-0.2982f,0.9543f,0.0168f,1.6327f,0.0166f,0.0228f,-0.9996f,-0.5149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9543f,-0.2979f,-0.0226f,-0.0763f,-0.2982f,0.9543f,0.0168f,1.4619f,0.0166f,0.0228f,-0.9996f,-1.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.9543f,-0.2979f,-0.0226f,-0.2452f,-0.2982f,0.9543f,0.0168f,1.9998f,0.0166f,0.0228f,-0.9996f,-1.053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.9543f,-0.2979f,-0.0226f,-0.0763f,-0.2982f,0.9543f,0.0168f,1.4619f,0.0166f,0.0228f,-0.9996f,-1.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.3725f,0.7638f,-0.5272f,-1.1864f,0.9252f,0.2613f,-0.2751f,0.275f,-0.0724f,-0.5902f,-0.804f,-0.6879f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9388f,0.3157f,-0.1374f,-1.1792f,0.274f,0.4435f,-0.8534f,0.3346f,-0.2085f,-0.8388f,-0.5029f,-0.5103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.8588f,-0.1038f,-0.5017f,-1.172f,0.3805f,0.5267f,-0.7601f,0.3942f,0.3432f,-0.8437f,-0.4129f,-0.3327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9666f,-0.2561f,0.0051f,-0.8028f,-0.1232f,0.4473f,-0.8858f,0.3289f,0.2246f,-0.8569f,-0.464f,-0.3257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-0.9267f,0f,0f,0f,-0.5637f,0f,0f,0f,-1.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9845f,0.1709f,-0.0384f,-0.9253f,0.1741f,0.932f,-0.318f,1.1234f,-0.0186f,-0.3197f,-0.9473f,-0.8513f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9845f,0.1709f,-0.0384f,-0.9253f,0.1741f,0.932f,-0.318f,1.1234f,-0.0186f,-0.3197f,-0.9473f,-0.8513f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9402f,-0.3392f,-0.0301f,-0.6014f,-0.3398f,0.9404f,0.0168f,1.3792f,0.0226f,0.026f,-0.9994f,-0.9506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.5113f,0f,0f,0f,1.2527f,0f,0f,0f,-0.7581f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.9409f,0f,0f,0f,0.3151f,0f,0f,0f,-0.5246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.9409f,0f,0f,0f,0.3151f,0f,0f,0f,-0.5246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.9409f,0f,0f,0f,0.3151f,0f,0f,0f,-0.5246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.9409f,0f,0f,0f,0.3151f,0f,0f,0f,-0.5246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.8335f,0f,0f,0f,1.1583f,0f,0f,0f,-0.7345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.8335f,0f,0f,0f,1.1583f,0f,0f,0f,-0.7345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.9962f,-0.1307f,0f,0.8583f,-0.0846f,1.45f,-0.2416f,1.3553f,0.0211f,-0.361f,-0.9704f,-0.848f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.736f,0f,0f,0f,1.2483f,0f,0f,0f,-0.8243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.736f,0f,0f,0f,1.2483f,0f,0f,0f,-0.8243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.904f,0.4273f,-0.0103f,0.4571f,0.427f,0.904f,0.0217f,1.4691f,0.0186f,0.0153f,-0.9997f,-0.9729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9962f,-0.0872f,0f,0f,-0.0846f,0.9667f,-0.2416f,0.5858f,0.0211f,-0.2407f,-0.9704f,-0.9141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.9962f,-0.0872f,0f,0f,-0.0846f,0.9667f,-0.2416f,0.5858f,0.0211f,-0.2407f,-0.9704f,-0.9141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-1f,0f,0f,0f,0f,0.8951f,-0.4459f,0.1207f,0f,-0.4459f,-0.8951f,0.2167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-1f,0f,0f,0f,0f,0.804f,-0.5946f,0.529f,0f,-0.5946f,-0.804f,-0.0775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9361f,-0.0819f,-0.342f,-0.555f,0.1739f,0.7376f,-0.6525f,0.3826f,0.3057f,-0.6703f,-0.6762f,-0.2246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9361f,0.0819f,0.342f,0.555f,-0.1739f,0.7376f,-0.6525f,0.3826f,-0.3057f,-0.6703f,-0.6762f,-0.2246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-1f,0f,0f,0f,0f,0.8951f,-0.4459f,0.6135f,0f,-0.4459f,-0.8951f,0.0147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-1f,0f,0f,0f,0f,0.1048f,-0.9945f,0.0927f,0f,-0.9945f,-0.1048f,-0.525f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-1f,0f,0f,0f,0f,0.7196f,-0.6944f,0.3741f,0f,-0.6944f,-0.7196f,0.195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-0.9266946223,"py":-0.5637435738,"pz":-1.9275003227,"ry":352.3089368397,"rx":-13.8911385334},"locator_hand":{"px":0.9409321086,"py":0.3150679341,"pz":-0.5246012362,"ry":359.9999697564,"rx":-13.9814843213}},"interactions":{"interaction_mace":{"px":-0.9266979075,"py":-0.5637443583,"pz":-1.9274996833,"ry":352.3089368397,"rx":-13.8911385334},"interaction_hand":{"px":0.9409324874,"py":0.3150671486,"pz":-0.524601309,"ry":359.9999697564,"rx":-13.9814843213}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/280_locator_locator_cinematic