# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-1f,0f,0f,0f,0f,0.8904f,-0.4553f,0.6053f,0f,-0.4553f,-0.8904f,-0.2207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.9657f,-0.2597f,-0.002f,-0.1049f,-0.257f,0.9542f,0.153f,2.0025f,-0.0379f,0.1482f,-0.9882f,-0.2109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.9657f,-0.2597f,-0.002f,-0.1049f,-0.257f,0.9542f,0.153f,2.0049f,-0.0379f,0.1482f,-0.9882f,-0.2264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9657f,-0.2597f,-0.002f,-0.0572f,-0.257f,0.9542f,0.153f,1.9001f,-0.0379f,0.1482f,-0.9882f,-0.7329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.9657f,-0.2597f,-0.002f,-0.2034f,-0.257f,0.9542f,0.153f,2.4464f,-0.0379f,0.1482f,-0.9882f,-0.7112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.9657f,-0.2597f,-0.002f,-0.0572f,-0.257f,0.9542f,0.153f,1.9001f,-0.0379f,0.1482f,-0.9882f,-0.7329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.6607f,0.6753f,-0.3278f,-1.2231f,0.7506f,0.6021f,-0.2724f,0.7206f,0.0134f,-0.426f,-0.9046f,-0.5987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9473f,0.3091f,-0.0841f,-1.2171f,0.2981f,0.7547f,-0.5845f,0.7552f,-0.1172f,-0.5787f,-0.8071f,-0.4145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.9176f,0.1234f,-0.3779f,-1.2111f,0.3219f,0.7884f,-0.5242f,0.7898f,0.2332f,-0.6026f,-0.7632f,-0.2303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9932f,-0.0549f,-0.1023f,-0.8454f,0.0183f,0.7958f,-0.6052f,0.7071f,0.1146f,-0.603f,-0.7895f,-0.2267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-0.9739f,0f,0f,0f,0.0462f,0f,0f,0f,-1.9368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9753f,0.2185f,-0.0319f,-0.9215f,0.2206f,0.9577f,-0.1847f,1.5702f,-0.0098f,-0.1872f,-0.9823f,-0.641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9753f,0.2185f,-0.0319f,-0.9215f,0.2206f,0.9577f,-0.1847f,1.5702f,-0.0098f,-0.1872f,-0.9823f,-0.641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9545f,-0.298f,-0.0078f,-0.5846f,-0.2956f,0.9429f,0.1533f,1.8218f,-0.0383f,0.1487f,-0.9881f,-0.6995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.5225f,0f,0f,0f,1.6415f,0f,0f,0f,-0.5178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.9297f,0f,0f,0f,0.6693f,0f,0f,0f,-0.4322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.9297f,0f,0f,0f,0.6693f,0f,0f,0f,-0.4322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.9297f,0f,0f,0f,0.6693f,0f,0f,0f,-0.4322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.9297f,0f,0f,0f,0.6693f,0f,0f,0f,-0.4322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.8424f,0f,0f,0f,1.5374f,0f,0f,0f,-0.5062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.8424f,0f,0f,0f,1.5374f,0f,0f,0f,-0.5062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-1.0311f,-0.0993f,0.009f,0.9032f,-0.0668f,1.5397f,-0.0869f,1.7638f,-0.0034f,-0.1308f,-1.0295f,-0.5894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.8078f,0f,0f,0f,1.7471f,0f,0f,0f,-0.5624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.8078f,0f,0f,0f,1.7471f,0f,0f,0f,-0.5624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.9922f,0.1246f,-0.0049f,0.4757f,0.1223f,0.9798f,0.1584f,1.8905f,0.0246f,0.1566f,-0.9874f,-0.696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9979f,-0.0641f,0.0087f,0f,-0.0646f,0.9944f,-0.0841f,1.0195f,-0.0033f,-0.0845f,-0.9964f,-0.7835f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.9979f,-0.0641f,0.0087f,0f,-0.0646f,0.9944f,-0.0841f,1.0195f,-0.0033f,-0.0845f,-0.9964f,-0.7835f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-1f,0f,0f,0f,0f,0.9712f,-0.2384f,0.2549f,0f,-0.2384f,-0.9712f,0.1877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-1f,0f,0f,0f,0f,0.9235f,-0.3836f,0.7219f,0f,-0.3836f,-0.9235f,0.0004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9669f,0.0088f,-0.255f,-0.5247f,0.1185f,0.9005f,-0.4185f,0.6197f,0.2259f,-0.4348f,-0.8717f,-0.1926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9669f,-0.0088f,0.255f,0.5247f,-0.1185f,0.9005f,-0.4185f,0.6197f,-0.2259f,-0.4348f,-0.8717f,-0.1926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-1f,0f,0f,0f,0f,0.9479f,-0.3185f,0.776f,0f,-0.3185f,-0.9479f,0.1132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-1f,0f,0f,0f,0f,0.6504f,-0.7596f,0.4346f,0f,-0.7596f,-0.6504f,-0.5546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-1f,0f,0f,0f,0f,0.8904f,-0.4553f,0.4945f,0f,-0.4553f,-0.8904f,0.2161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-0.9739122521,"py":0.0461834631,"pz":-1.9367911311,"ry":353.0929727935,"rx":-5.817498093},"locator_hand":{"px":0.9296807678,"py":0.6693411871,"pz":-0.4321877842,"ry":0.501146665,"rx":-4.8233761877}},"interactions":{"interaction_mace":{"px":-0.9739155815,"py":0.0461827528,"pz":-1.9367906549,"ry":336.9472482328,"rx":-17.4171077364},"interaction_hand":{"px":0.9296811316,"py":0.669340415,"pz":-0.4321879772,"ry":0.501146665,"rx":-4.8233761877}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/289_locator_locator_cinematic