# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0059f,0f,0f,0f,0f,-0.0038f,0.0045f,0.2632f,0f,0.0045f,0.0038f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0056f,0.0018f,0.0001f,-0.076f,0.0017f,-0.0056f,0.0005f,1.2861f,-0.0003f,0.0005f,0.0059f,-1.1211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0056f,0.0018f,0.0001f,-0.0763f,0.0017f,-0.0056f,0.0005f,1.2874f,-0.0003f,0.0005f,0.0059f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0058f,-0.001f,0.0002f,-0.9253f,-0.001f,-0.0053f,0.0024f,0.9666f,0.0002f,0.0024f,0.0054f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0059f,0.0005f,0f,0f,0.0005f,-0.0055f,0.002f,0.4255f,-0.0002f,0.002f,0.0055f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.0535f,0f,0f,0f,0f,0.9109f,0.5292f,-0.2808f,0f,-0.5292f,0.9109f,3.6471f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.0535f,0f,0f,0f,0f,0.9095f,0.5317f,0.1734f,0f,-0.5317f,0.9095f,3.3739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.0535f,0f,0f,0f,0f,0.44f,0.9572f,1.0133f,0f,-0.9572f,0.44f,2.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.0535f,0f,0f,0f,0f,0.44f,0.9572f,1.4094f,0f,-0.9572f,0.44f,2.587f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.0535f,0f,0f,-0.5794f,0f,1.58f,0.0169f,1.2477f,0f,-0.0253f,1.0534f,2.6882f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.0535f,0f,0f,0.5794f,0f,1.58f,0.0169f,1.2477f,0f,-0.0253f,1.0534f,2.6882f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.0535f,0f,0f,0f,0f,0.6504f,0.8288f,1.0514f,0f,-0.8288f,0.6504f,3.4716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.0535f,0f,0f,0f,0f,0.8547f,0.616f,0.485f,0f,-0.616f,0.8547f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/30_locator_locator_cinematic