# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-1f,0f,0f,0f,0f,0.9984f,-0.0558f,0.9429f,0f,-0.0558f,-0.9984f,-0.1086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.9939f,-0.1082f,0.0195f,-0.0465f,-0.1034f,0.9804f,0.1674f,2.5154f,-0.0372f,0.1644f,-0.9857f,0.245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.9939f,-0.1082f,0.0195f,-0.0462f,-0.1034f,0.9804f,0.1674f,2.518f,-0.0372f,0.1644f,-0.9857f,0.2296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9939f,-0.1082f,0.0195f,-0.0165f,-0.1034f,0.9804f,0.1674f,2.4153f,-0.0372f,0.1644f,-0.9857f,-0.2787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.9939f,-0.1082f,0.0195f,-0.0761f,-0.1034f,0.9804f,0.1674f,2.9773f,-0.0372f,0.1644f,-0.9857f,-0.2478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.9939f,-0.1082f,0.0195f,-0.0165f,-0.1034f,0.9804f,0.1674f,2.4153f,-0.0372f,0.1644f,-0.9857f,-0.2787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.9618f,0.2733f,-0.0161f,-1.2064f,0.2737f,0.9591f,-0.0726f,1.3164f,-0.0044f,-0.0743f,-0.9972f,-0.2895f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9765f,0.2155f,0.0076f,-1.208f,0.2138f,0.9721f,-0.096f,1.3246f,-0.0281f,-0.0921f,-0.9954f,-0.1021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.9773f,0.2093f,-0.0338f,-1.2095f,0.2115f,0.973f,-0.092f,1.3328f,0.0137f,-0.0971f,-0.9952f,0.0852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9842f,0.1769f,-0.0113f,-0.8423f,0.1771f,0.9795f,-0.0959f,1.2568f,-0.0059f,-0.0964f,-0.9953f,0.0915f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-0.8931f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-0.893f,0f,0f,0f,0.8436f,0f,0f,0f,-1.6986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9791f,0.2031f,0.0083f,-0.9231f,0.2026f,0.9783f,-0.0437f,2.1686f,-0.017f,-0.0411f,-0.999f,-0.1993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9791f,0.2031f,0.0083f,-0.9231f,0.2026f,0.9783f,-0.0437f,2.1686f,-0.017f,-0.0411f,-0.999f,-0.1993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9918f,-0.1265f,0.0192f,-0.547f,-0.1216f,0.9783f,0.1678f,2.3575f,-0.04f,0.164f,-0.9856f,-0.2549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.55f,0f,0f,0f,2.1019f,0f,0f,0f,-0.1052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.9114f,0f,0f,0f,1.1098f,0f,0f,0f,-0.1617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.9114f,0f,0f,0f,1.1098f,0f,0f,0f,-0.1617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.9114f,0f,0f,0f,1.1098f,0f,0f,0f,-0.1617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.9114f,0f,0f,0f,1.1098f,0f,0f,0f,-0.1617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.8647f,0f,0f,0f,1.9825f,0f,0f,0f,-0.11f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.8647f,0f,0f,0f,1.9825f,0f,0f,0f,-0.11f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-1.0624f,-0.0281f,0.0081f,0.9262f,-0.0183f,1.5834f,0.0634f,2.2627f,-0.0092f,0.0944f,-1.0606f,-0.1619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.8559f,0f,0f,0f,2.2588f,0f,0f,0f,-0.108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.8559f,0f,0f,0f,2.2588f,0f,0f,0f,-0.108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.9993f,0.0384f,-0.001f,0.5153f,0.0377f,0.9841f,0.1737f,2.3758f,0.0077f,0.1735f,-0.9848f,-0.2457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9998f,-0.0177f,0.0076f,0f,-0.0172f,0.9981f,0.0596f,1.5494f,-0.0087f,0.0595f,-0.9982f,-0.4555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.9998f,-0.0177f,0.0076f,0f,-0.0172f,0.9981f,0.0596f,1.5494f,-0.0087f,0.0595f,-0.9982f,-0.4555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-1f,0f,0f,0f,0f,0.9975f,0.0707f,0.4572f,0f,0.0707f,-0.9975f,0.1625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-1f,0f,0f,0f,0f,0.9985f,-0.0555f,0.9599f,0f,-0.0555f,-0.9985f,0.1408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9786f,0.1921f,-0.074f,-0.4635f,0.195f,0.9802f,-0.0341f,0.9434f,0.066f,-0.0478f,-0.9967f,-0.0992f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9786f,-0.1921f,0.074f,0.4635f,-0.195f,0.9802f,-0.0341f,0.9434f,-0.066f,-0.0478f,-0.9967f,-0.0992f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-1f,0f,0f,0f,0f,0.9793f,-0.2025f,0.9638f,0f,-0.2025f,-0.9793f,0.2658f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-1f,0f,0f,0f,0f,0.9851f,0.1722f,0.9219f,0f,0.1722f,-0.9851f,-0.483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-1f,0f,0f,0f,0f,0.9984f,-0.0558f,0.6647f,0f,-0.0558f,-0.9984f,0.246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-0.8930449979,"py":0.8435735416,"pz":-1.6985990933,"ry":355.3457223188,"rx":2.1777412931},"locator_hand":{"px":0.9114410624,"py":1.1097558316,"pz":-0.1617382538,"ry":0.4388487131,"rx":3.4186173367}},"interactions":{"interaction_mace":{"px":-0.8930483254,"py":0.8435727124,"pz":-1.698598854,"ry":340.1402651166,"rx":-10.2518983932},"interaction_hand":{"px":0.9114413906,"py":1.1097550792,"pz":-0.1617385571,"ry":0.4388487131,"rx":3.4186173367}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/302_locator_locator_cinematic