# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.9997f,-0.0015f,0.0242f,0.0077f,0f,0.9982f,0.0601f,1.0048f,-0.0242f,0.0601f,-0.9979f,-0.07f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.9997f,0.0038f,0.0242f,0.0033f,0.0045f,0.9996f,0.0292f,2.6913f,-0.0241f,0.0293f,-0.9993f,0.3114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.9997f,0.0038f,0.0242f,0.0037f,0.0045f,0.9996f,0.0292f,2.6917f,-0.0241f,0.0293f,-0.9993f,0.2958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9997f,0.0038f,0.0242f,0.0147f,0.0045f,0.9996f,0.0292f,2.5185f,-0.0241f,0.0293f,-0.9993f,-0.1937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.9997f,0.0038f,0.0242f,0.0183f,0.0045f,0.9996f,0.0292f,3.0825f,-0.0241f,0.0293f,-0.9993f,-0.2397f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.9997f,0.0038f,0.0242f,0.0147f,0.0045f,0.9996f,0.0292f,2.5185f,-0.0241f,0.0293f,-0.9993f,-0.1937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.9995f,-0.0041f,0.0311f,-1.0406f,-0.0032f,0.9996f,0.0278f,1.4624f,-0.0312f,0.0277f,-0.9991f,-0.2364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9996f,0.0207f,0.0214f,-1.0453f,0.0215f,0.9992f,0.0351f,1.4598f,-0.0207f,0.0355f,-0.9992f,-0.049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.999f,0.022f,0.0391f,-1.0501f,0.0234f,0.999f,0.0371f,1.4572f,-0.0382f,0.0379f,-0.9985f,0.1385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9988f,0.0379f,0.0297f,-0.6753f,0.0389f,0.9986f,0.0365f,1.447f,-0.0283f,0.0376f,-0.9989f,0.1478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1315f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1315f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1315f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1315f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1315f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1315f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1315f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1314f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1314f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1314f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-0.6349f,0f,0f,0f,1.1314f,0f,0f,0f,-1.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9993f,0.0266f,0.0254f,-0.9139f,0.027f,0.9995f,0.014f,2.3449f,-0.025f,0.0147f,-0.9996f,-0.0958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9993f,0.0266f,0.0254f,-0.9139f,0.027f,0.9995f,0.014f,2.3449f,-0.025f,0.0147f,-0.9996f,-0.0958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9997f,0.0056f,0.0237f,-0.5174f,0.0062f,0.9996f,0.0274f,2.4731f,-0.0235f,0.0276f,-0.9993f,-0.1767f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.5713f,0f,0f,0f,2.1981f,0f,0f,0f,-0.002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.9112f,0f,0f,0f,1.197f,0f,0f,0f,-0.023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.9112f,0f,0f,0f,1.197f,0f,0f,0f,-0.023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.9112f,0f,0f,0f,1.197f,0f,0f,0f,-0.023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.9111f,0f,0f,0f,1.197f,0f,0f,0f,-0.023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.8832f,0f,0f,0f,2.0717f,0f,0f,0f,0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.8832f,0f,0f,0f,2.0717f,0f,0f,0f,0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-1.0737f,0.006f,0.026f,0.9288f,0.0048f,1.5921f,0.0313f,2.409f,-0.0258f,0.0466f,-1.0733f,-0.0519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.8844f,0f,0f,0f,2.3841f,0f,0f,0f,0.011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.8844f,0f,0f,0f,2.3841f,0f,0f,0f,0.011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.9997f,0.0038f,0.0242f,0.5448f,0.0045f,0.9996f,0.0292f,2.4683f,-0.0241f,0.0293f,-0.9993f,-0.1511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9997f,0.0038f,0.0242f,0.0144f,0.0045f,0.9996f,0.0292f,1.6475f,-0.0241f,0.0293f,-0.9993f,-0.3442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.9997f,0.0038f,0.0242f,0.0144f,0.0045f,0.9996f,0.0292f,1.6475f,-0.0241f,0.0293f,-0.9993f,-0.3442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.9997f,-0.0106f,0.0218f,0.0045f,0f,0.8998f,0.4364f,0.5033f,-0.0242f,0.4362f,-0.8995f,0.0637f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.9997f,-0.0053f,0.0236f,0.0017f,0f,0.9758f,0.2185f,0.9929f,-0.0242f,0.2185f,-0.9755f,0.1797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9758f,0.2142f,0.0435f,-0.4296f,0.2164f,0.9748f,0.0539f,1.0048f,-0.0308f,0.0621f,-0.9976f,-0.0805f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9762f,-0.2169f,0.0048f,0.4451f,-0.2164f,0.9748f,0.0539f,1.0048f,-0.0164f,0.0516f,-0.9985f,-0.0594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.9997f,0.0038f,0.0239f,-0.0013f,0f,0.9876f,-0.1573f,0.9823f,-0.0242f,-0.1572f,-0.9873f,0.3043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.9997f,-0.0126f,0.0207f,0.0168f,0f,0.8544f,0.5195f,1.0274f,-0.0242f,0.5194f,-0.8542f,-0.4442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.9997f,-0.0015f,0.0242f,0f,0f,0.9982f,0.0601f,0.6875f,-0.0242f,0.0601f,-0.9979f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-0.6348749408,"py":1.1314441079,"pz":-1.6623301646,"ry":355.5654613184,"rx":4.4927611019},"locator_hand":{"px":0.9111479968,"py":1.1969889223,"pz":-0.0229571912,"ry":1.3865205695,"rx":1.6711949095}},"interactions":{"interaction_mace":{"px":-0.6348780703,"py":1.1314426917,"pz":-1.6623300335,"ry":355.5654613184,"rx":4.4927611019},"interaction_hand":{"px":0.9111483126,"py":1.196988154,"pz":-0.0229574665,"ry":1.3865205695,"rx":1.6711949095}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/318_locator_locator_cinematic