# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.9995f,-0.0019f,0.0306f,0.0098f,0f,0.998f,0.0629f,1.0057f,-0.0307f,0.0629f,-0.9976f,-0.069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.9995f,0.0042f,0.0316f,0.0029f,0.0051f,0.9996f,0.0282f,2.6936f,-0.0315f,0.0283f,-0.9991f,0.3131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.9995f,0.0042f,0.0316f,0.0033f,0.0051f,0.9996f,0.0282f,2.694f,-0.0315f,0.0283f,-0.9991f,0.2975f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9995f,0.0042f,0.0316f,0.0179f,0.0051f,0.9996f,0.0282f,2.5203f,-0.0315f,0.0283f,-0.9991f,-0.1918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.9995f,0.0042f,0.0316f,0.0222f,0.0051f,0.9996f,0.0282f,3.0843f,-0.0315f,0.0283f,-0.9991f,-0.2383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.9995f,0.0042f,0.0316f,0.0179f,0.0051f,0.9996f,0.0282f,2.5203f,-0.0315f,0.0283f,-0.9991f,-0.1918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.9989f,-0.0278f,0.0368f,-1.0204f,-0.0262f,0.9988f,0.0411f,1.4647f,-0.0379f,0.04f,-0.9985f,-0.2511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9997f,0.0003f,0.0258f,-1.0262f,0.0016f,0.9988f,0.0491f,1.46f,-0.0258f,0.0491f,-0.9985f,-0.0638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.9989f,0.0017f,0.0458f,-1.0319f,0.004f,0.9986f,0.0518f,1.4552f,-0.0457f,0.052f,-0.9976f,0.1236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9992f,0.02f,0.0351f,-0.6571f,0.0218f,0.9985f,0.051f,1.4522f,-0.034f,0.0517f,-0.9981f,0.135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-0.6003f,0f,0f,0f,1.1572f,0f,0f,0f,-1.6781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9995f,0.0072f,0.0307f,-0.9116f,0.008f,0.9996f,0.0254f,2.3479f,-0.0305f,0.0256f,-0.9992f,-0.1002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9995f,0.0072f,0.0307f,-0.9116f,0.008f,0.9996f,0.0254f,2.3479f,-0.0305f,0.0256f,-0.9992f,-0.1002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9995f,0.0072f,0.0307f,-0.5143f,0.008f,0.9996f,0.0254f,2.4752f,-0.0305f,0.0256f,-0.9992f,-0.1786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.5728f,0f,0f,0f,2.1997f,0f,0f,0f,0.0044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.9122f,0f,0f,0f,1.1984f,0f,0f,0f,-0.0131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.9122f,0f,0f,0f,1.1984f,0f,0f,0f,-0.0131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.9122f,0f,0f,0f,1.1984f,0f,0f,0f,-0.0131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.9122f,0f,0f,0f,1.1984f,0f,0f,0f,-0.0131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.8847f,0f,0f,0f,2.0732f,0f,0f,0f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.8847f,0f,0f,0f,2.0732f,0f,0f,0f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-1.0734f,0.0067f,0.034f,0.9318f,0.0055f,1.5906f,0.0303f,2.4152f,-0.0338f,0.0451f,-1.073f,-0.0407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.886f,0f,0f,0f,2.3856f,0f,0f,0f,0.0196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.886f,0f,0f,0f,2.3856f,0f,0f,0f,0.0196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.9995f,0.0042f,0.0316f,0.5477f,0.0051f,0.9996f,0.0282f,2.4698f,-0.0315f,0.0283f,-0.9991f,-0.1451f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9995f,0.0042f,0.0316f,0.0182f,0.0051f,0.9996f,0.0282f,1.6491f,-0.0315f,0.0283f,-0.9991f,-0.3414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.9995f,0.0042f,0.0316f,0.0182f,0.0051f,0.9996f,0.0282f,1.6491f,-0.0315f,0.0283f,-0.9991f,-0.3414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.9995f,-0.0147f,0.0269f,0.0061f,0f,0.8779f,0.4789f,0.5071f,-0.0307f,0.4786f,-0.8775f,0.0506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.9995f,-0.0076f,0.0297f,0.0021f,0f,0.9691f,0.2465f,0.9931f,-0.0307f,0.2464f,-0.9687f,0.1806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9816f,0.1862f,0.043f,-0.4275f,0.1886f,0.9803f,0.0593f,1.0057f,-0.0311f,0.0663f,-0.9973f,-0.0824f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9816f,-0.1899f,0.0182f,0.4471f,-0.1886f,0.9803f,0.0593f,1.0057f,-0.0291f,0.0548f,-0.9981f,-0.0556f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.9995f,0.0037f,0.0305f,-0.0017f,0f,0.9927f,-0.121f,0.9821f,-0.0307f,-0.1209f,-0.9922f,0.3051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.9995f,-0.0148f,0.0269f,0.0213f,0f,0.8756f,0.483f,1.0293f,-0.0307f,0.4828f,-0.8752f,-0.4431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.9995f,-0.0019f,0.0306f,0f,0f,0.998f,0.0629f,0.6875f,-0.0307f,0.0629f,-0.9976f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-0.6003240621,"py":1.1572144048,"pz":-1.6781353025,"ry":355.7993258929,"rx":5.0287145869},"locator_hand":{"px":0.9122206725,"py":1.1983939249,"pz":-0.0130799436,"ry":1.8129212317,"rx":1.6150936176}},"interactions":{"interaction_mace":{"px":-0.6003271643,"py":1.1572129272,"pz":-1.678135205,"ry":343.4879761948,"rx":-10.2448031756},"interaction_hand":{"px":0.9122209898,"py":1.1983931561,"pz":-0.0130802158,"ry":1.8129212317,"rx":1.6150936176}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/320_locator_locator_cinematic