# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.8232f,0.5677f,-0.0859f,0f,-0.5677f,0.8232f,3.6308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.8473f,0.5311f,0.3371f,0f,-0.5311f,0.8473f,3.3583f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.491f,0.8712f,1.2223f,0f,-0.8712f,0.491f,2.2883f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.491f,0.8712f,1.5658f,0f,-0.8712f,0.491f,2.6971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4992f,0.0326f,1.4064f,0f,-0.0488f,0.9995f,2.7832f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4992f,0.0326f,1.4064f,0f,-0.0488f,0.9995f,2.7832f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.6776f,0.7354f,1.1618f,0f,-0.7354f,0.6776f,3.5097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.8506f,0.5259f,0.6254f,0f,-0.5259f,0.8506f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}