# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.9976f,-0.0039f,0.0694f,0.0224f,0f,0.9985f,0.0555f,1.0033f,-0.0695f,0.0554f,-0.996f,-0.0707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.9962f,0.0182f,-0.0854f,0.0468f,0.0018f,0.9821f,0.1881f,2.6398f,0.0873f,0.1873f,-0.9784f,0.3867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.9962f,0.0182f,-0.0854f,0.0454f,0.0018f,0.9821f,0.1881f,2.6428f,0.0873f,0.1873f,-0.9784f,0.3714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9962f,0.0182f,-0.0854f,0.0006f,0.0018f,0.9821f,0.1881f,2.5498f,0.0873f,0.1873f,-0.9784f,-0.1377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.9962f,0.0182f,-0.0854f,0.0055f,0.0018f,0.9821f,0.1881f,3.114f,0.0873f,0.1873f,-0.9784f,-0.0935f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.9962f,0.0182f,-0.0854f,0.0006f,0.0018f,0.9821f,0.1881f,2.5498f,0.0873f,0.1873f,-0.9784f,-0.1377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.995f,-0.0579f,0.0811f,-0.9953f,-0.0542f,0.9974f,0.0478f,1.4642f,-0.0837f,0.0431f,-0.9956f,-0.3069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9978f,-0.0136f,0.0649f,-1.0091f,-0.0096f,0.9981f,0.061f,1.4599f,-0.0656f,0.0602f,-0.996f,-0.1199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.9951f,-0.0122f,0.0978f,-1.0228f,-0.0057f,0.9978f,0.0664f,1.4555f,-0.0984f,0.0655f,-0.993f,0.067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9967f,0.0206f,0.079f,-0.6488f,0.0257f,0.9976f,0.0644f,1.4549f,-0.0775f,0.0663f,-0.9948f,0.0945f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-0.5128f,0f,0f,0f,1.156f,0f,0f,0f,-1.7139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9973f,-0.0001f,0.0732f,-0.8986f,0.0016f,0.9997f,0.0232f,2.3484f,-0.0732f,0.0233f,-0.997f,-0.1538f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9973f,-0.0001f,0.0732f,-0.8986f,0.0016f,0.9997f,0.0232f,2.3484f,-0.0732f,0.0233f,-0.997f,-0.1538f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9971f,0.0132f,0.0754f,-0.4972f,0.0143f,0.9998f,0.0137f,2.4722f,-0.0752f,0.0148f,-0.9971f,-0.2158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.5796f,0f,0f,0f,2.1973f,0f,0f,0f,0.021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.9185f,0f,0f,0f,1.1956f,0f,0f,0f,0.0264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.9185f,0f,0f,0f,1.1956f,0f,0f,0f,0.0264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.9185f,0f,0f,0f,1.1956f,0f,0f,0f,0.0264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.9185f,0f,0f,0f,1.1956f,0f,0f,0f,0.0264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.8907f,0f,0f,0f,2.0706f,0f,0f,0f,0.0431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.8907f,0f,0f,0f,2.0706f,0f,0f,0f,0.0431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-1.0249f,0.3087f,0.2146f,0.9803f,0.0963f,1.4052f,-0.471f,2.4491f,-0.284f,-0.6378f,-0.934f,0.0553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.8942f,0f,0f,0f,2.4134f,0f,0f,0f,0.1025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.8942f,0f,0f,0f,2.4134f,0f,0f,0f,0.1025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.9808f,0.0515f,0.1881f,0.5905f,0.0156f,0.9821f,-0.1875f,2.4662f,-0.1944f,-0.181f,-0.9641f,-0.1291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9968f,0.0038f,0.0795f,0.0416f,0.0055f,0.9998f,0.0215f,1.6447f,-0.0794f,0.0219f,-0.9966f,-0.3474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.9968f,0.0038f,0.0795f,0.0416f,0.0055f,0.9998f,0.0215f,1.6447f,-0.0794f,0.0219f,-0.9966f,-0.3474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.9976f,-0.0354f,0.0598f,0.0135f,0f,0.8607f,0.5092f,0.5044f,-0.0695f,0.5079f,-0.8586f,0.057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.9976f,-0.016f,0.0677f,0.005f,0f,0.9732f,0.2299f,0.9926f,-0.0695f,0.2293f,-0.9709f,0.1785f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9931f,0.0941f,0.0694f,-0.4141f,0.0981f,0.9936f,0.0555f,1.0033f,-0.0638f,0.0619f,-0.996f,-0.1012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9924f,-0.1018f,0.0694f,0.4588f,-0.0981f,0.9936f,0.0555f,1.0033f,-0.0746f,0.0483f,-0.996f,-0.0403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.9976f,0.0062f,0.0693f,-0.0037f,0f,0.996f,-0.0888f,0.9825f,-0.0695f,-0.0886f,-0.9936f,0.3028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.9976f,-0.0245f,0.0651f,0.0484f,0f,0.9357f,0.3528f,1.0242f,-0.0695f,0.3519f,-0.9334f,-0.4442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.9976f,-0.0039f,0.0694f,0f,0f,0.9985f,0.0555f,0.6875f,-0.0695f,0.0554f,-0.996f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-0.5128110272,"py":1.1560159175,"pz":-1.7138365188,"ry":358.217527388,"rx":4.8686873978},"locator_hand":{"px":0.9185299981,"py":1.1956465729,"pz":0.026434246,"ry":4.5608160561,"rx":1.2310875383}},"interactions":{"interaction_mace":{"px":-0.5128141215,"py":1.1560144208,"pz":-1.7138365501,"ry":345.9922547597,"rx":-10.4751186346},"interaction_hand":{"px":0.9185303274,"py":1.1956458022,"pz":0.0264339944,"ry":4.5608160561,"rx":1.2310875383}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/332_locator_locator_cinematic