# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.9966f,-0.0022f,0.0828f,0.0274f,0f,0.9997f,0.0262f,0.9938f,-0.0829f,0.0261f,-0.9962f,-0.0795f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.9567f,0.1123f,-0.2685f,0.1183f,-0.0029f,0.9189f,0.3946f,2.548f,0.291f,0.3783f,-0.8788f,0.4138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.9567f,0.1123f,-0.2685f,0.1141f,-0.0029f,0.9189f,0.3946f,2.5541f,0.291f,0.3783f,-0.8788f,0.4001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9567f,0.1123f,-0.2685f,-0.037f,-0.0029f,0.9189f,0.3946f,2.573f,0.291f,0.3783f,-0.8788f,-0.0965f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.9567f,0.1123f,-0.2685f,0.0093f,-0.0029f,0.9189f,0.3946f,3.1145f,0.291f,0.3783f,-0.8788f,0.0614f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.9567f,0.1123f,-0.2685f,-0.037f,-0.0029f,0.9189f,0.3946f,2.573f,0.291f,0.3783f,-0.8788f,-0.0965f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.9925f,-0.0816f,0.091f,-0.9834f,-0.0772f,0.9957f,0.0511f,1.4466f,-0.0948f,0.0437f,-0.9945f,-0.3531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9971f,-0.0255f,0.072f,-0.999f,-0.0206f,0.9974f,0.0686f,1.4427f,-0.0736f,0.067f,-0.995f,-0.1663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.993f,-0.0243f,0.1152f,-1.0146f,-0.0155f,0.9969f,0.077f,1.4388f,-0.1167f,0.0747f,-0.9904f,0.0205f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9958f,0.0224f,0.089f,-0.6409f,0.029f,0.9969f,0.0737f,1.4406f,-0.0871f,0.076f,-0.9933f,0.0517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-0.4848f,0f,0f,0f,1.1372f,0f,0f,0f,-1.7543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9965f,-0.0064f,0.0832f,-0.8936f,-0.0046f,0.9998f,0.0208f,2.3318f,-0.0833f,0.0203f,-0.9963f,-0.2017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9965f,-0.0064f,0.0832f,-0.8936f,-0.0046f,0.9998f,0.0208f,2.3318f,-0.0833f,0.0203f,-0.9963f,-0.2017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9959f,0.0154f,0.0886f,-0.4912f,0.0157f,0.9999f,0.0026f,2.454f,-0.0885f,0.004f,-0.9961f,-0.2597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.5819f,0f,0f,0f,2.1838f,0f,0f,0f,-0.0014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.9231f,0f,0f,0f,1.1831f,0f,0f,0f,0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.9231f,0f,0f,0f,1.1831f,0f,0f,0f,0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.9231f,0f,0f,0f,1.1831f,0f,0f,0f,0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.9231f,0f,0f,0f,1.1831f,0f,0f,0f,0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.8928f,0f,0f,0f,2.0581f,0f,0f,0f,0.0273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.8928f,0f,0f,0f,2.0581f,0f,0f,0f,0.0273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.9116f,0.7537f,0.1327f,1.0045f,0.174f,0.7905f,-0.8899f,2.45f,-0.5011f,-1.0966f,-0.5503f,0.0763f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.8865f,0f,0f,0f,2.4475f,0f,0f,0f,0.1361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.8865f,0f,0f,0f,2.4475f,0f,0f,0f,0.1361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.933f,0.1843f,0.3091f,0.6285f,0.0212f,0.8855f,-0.4642f,2.4514f,-0.3592f,-0.4265f,-0.8301f,-0.1504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9953f,0.001f,0.0972f,0.0519f,0.0023f,0.9999f,0.013f,1.6267f,-0.0972f,0.0132f,-0.9952f,-0.3745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.9953f,0.001f,0.0972f,0.0519f,0.0023f,0.9999f,0.013f,1.6267f,-0.0972f,0.0132f,-0.9952f,-0.3745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.9966f,-0.0213f,0.0801f,0.0096f,0f,0.9663f,0.2575f,0.4884f,-0.0829f,0.2566f,-0.963f,0.1344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.9966f,-0.0048f,0.0827f,0.0067f,0f,0.9983f,0.0578f,0.9904f,-0.0829f,0.0576f,-0.9949f,0.1696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9953f,0.0492f,0.0828f,-0.4086f,0.0515f,0.9983f,0.0262f,0.9938f,-0.0814f,0.0303f,-0.9962f,-0.1158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9951f,-0.0535f,0.0828f,0.4634f,-0.0515f,0.9983f,0.0262f,0.9938f,-0.0841f,0.0218f,-0.9962f,-0.0432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.9966f,0.0147f,0.0816f,-0.0037f,0f,0.9841f,-0.1774f,0.984f,-0.0829f,-0.1768f,-0.9808f,0.2941f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.9966f,-0.0211f,0.0801f,0.0585f,0f,0.967f,0.2548f,1.0036f,-0.0829f,0.2539f,-0.9637f,-0.4531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.9966f,-0.0022f,0.0828f,0f,0f,0.9997f,0.0262f,0.6875f,-0.0829f,0.0261f,-0.9962f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-0.4848416142,"py":1.1372286234,"pz":-1.7542627788,"ry":358.7674479587,"rx":4.6910686748},"locator_hand":{"px":0.9230661373,"py":1.1831468046,"pz":0.0188140643,"ry":5.5803203135,"rx":0.7463729154}},"interactions":{"interaction_mace":{"px":-0.4848446989,"py":1.1372271077,"pz":-1.7542628369,"ry":346.6268116063,"rx":-10.7213072848},"interaction_hand":{"px":0.9230664729,"py":1.1831460325,"pz":0.0188138253,"ry":5.5803203135,"rx":0.7463729154}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/344_locator_locator_cinematic