# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.9979f,-0.0006f,0.0649f,0.0218f,0f,1f,0.0098f,0.9883f,-0.0649f,0.0098f,-0.9978f,-0.0849f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.9462f,0.1194f,-0.3006f,0.1328f,-0.0066f,0.922f,0.3871f,2.5442f,0.3234f,0.3683f,-0.8716f,0.3917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.9462f,0.1194f,-0.3006f,0.1281f,-0.0066f,0.922f,0.3871f,2.5502f,0.3234f,0.3683f,-0.8716f,0.3781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9462f,0.1194f,-0.3006f,-0.0399f,-0.0066f,0.922f,0.3871f,2.5649f,0.3234f,0.3683f,-0.8716f,-0.1131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.9462f,0.1194f,-0.3006f,0.0085f,-0.0066f,0.922f,0.3871f,3.1077f,0.3234f,0.3683f,-0.8716f,0.0395f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.9462f,0.1194f,-0.3006f,-0.0399f,-0.0066f,0.922f,0.3871f,2.5649f,0.3234f,0.3683f,-0.8716f,-0.1131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.994f,-0.0902f,0.0619f,-0.993f,-0.0871f,0.9949f,0.0512f,1.4365f,-0.0662f,0.0455f,-0.9968f,-0.3459f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9987f,-0.0282f,0.0422f,-1.0032f,-0.0252f,0.9972f,0.0709f,1.433f,-0.0441f,0.0697f,-0.9966f,-0.1587f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.9955f,-0.027f,0.0904f,-1.0134f,-0.0196f,0.9965f,0.081f,1.4295f,-0.0922f,0.0789f,-0.9926f,0.0285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9978f,0.0274f,0.06f,-0.639f,0.032f,0.9965f,0.0769f,1.432f,-0.0577f,0.0786f,-0.9952f,0.049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-0.5341f,0f,0f,0f,1.1251f,0f,0f,0f,-1.76f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9985f,-0.0078f,0.0546f,-0.9006f,-0.0067f,0.9998f,0.0188f,2.3222f,-0.0547f,0.0184f,-0.9983f,-0.1989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9985f,-0.0078f,0.0546f,-0.9006f,-0.0067f,0.9998f,0.0188f,2.3222f,-0.0547f,0.0184f,-0.9983f,-0.1989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9979f,0.0163f,0.0623f,-0.4997f,0.0161f,0.9999f,-0.0041f,2.4436f,-0.0624f,-0.0031f,-0.998f,-0.2683f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.5795f,0f,0f,0f,2.1764f,0f,0f,0f,-0.0334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.9223f,0f,0f,0f,1.1762f,0f,0f,0f,-0.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.9223f,0f,0f,0f,1.1762f,0f,0f,0f,-0.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.9223f,0f,0f,0f,1.1762f,0f,0f,0f,-0.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.9223f,0f,0f,0f,1.1762f,0f,0f,0f,-0.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.8911f,0f,0f,0f,2.0512f,0f,0f,0f,-0.0111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.8911f,0f,0f,0f,2.0512f,0f,0f,0f,-0.0111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.9211f,0.6976f,0.1316f,1.0015f,0.1643f,0.8173f,-0.8685f,2.442f,-0.4659f,-1.091f,-0.5665f,0.03f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.8871f,0f,0f,0f,2.4388f,0f,0f,0f,0.0933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.8871f,0f,0f,0f,2.4388f,0f,0f,0f,0.0933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.9437f,0.1653f,0.2864f,0.6204f,0.0174f,0.8897f,-0.4562f,2.4431f,-0.3303f,-0.4256f,-0.8425f,-0.1852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9973f,0f,0.074f,0.0417f,0.0005f,1f,0.007f,1.6163f,-0.074f,0.007f,-0.9972f,-0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.9973f,0f,0.074f,0.0417f,0.0005f,1f,0.007f,1.6163f,-0.074f,0.007f,-0.9972f,-0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.9979f,-0.0099f,0.0641f,0.0063f,0f,0.9882f,0.1531f,0.486f,-0.0649f,0.1527f,-0.9861f,0.1529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.9979f,-0.0007f,0.0649f,0.0056f,0f,0.9999f,0.0108f,0.989f,-0.0649f,0.0108f,-0.9978f,0.1646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.997f,0.0433f,0.0649f,-0.4148f,0.044f,0.999f,0.0098f,0.9883f,-0.0644f,0.0126f,-0.9978f,-0.1133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9969f,-0.0446f,0.0649f,0.4584f,-0.044f,0.999f,0.0098f,0.9883f,-0.0652f,0.0069f,-0.9978f,-0.0565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.9979f,0.0134f,0.0635f,-0.0026f,0f,0.9784f,-0.2065f,0.9846f,-0.0649f,-0.2061f,-0.9764f,0.2893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.9979f,-0.0147f,0.0632f,0.0461f,0f,0.974f,0.2266f,0.992f,-0.0649f,0.2261f,-0.9719f,-0.4591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.9979f,-0.0006f,0.0649f,0f,0f,1f,0.0098f,0.6875f,-0.0649f,0.0098f,-0.9978f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-0.5341195141,"py":1.1250672704,"pz":-1.7600240931,"ry":357.1169516804,"rx":4.5648966369},"locator_hand":{"px":0.9222905136,"py":1.1762091067,"pz":-0.0149804987,"ry":4.2465777061,"rx":0.4021860795}},"interactions":{"interaction_mace":{"px":-0.5341225962,"py":1.1250657486,"pz":-1.7600240595,"ry":345.0000057443,"rx":-10.8672532384},"interaction_hand":{"px":0.9222908446,"py":1.1762083336,"pz":-0.0149807407,"ry":4.2465777061,"rx":0.4021860795}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/351_locator_locator_cinematic