# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.9998f,0f,0.0192f,0.0065f,0f,1f,0.0006f,0.9852f,-0.0192f,0.0006f,-0.9998f,-0.0883f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.8584f,0.1351f,-0.4948f,0.2529f,-0.0551f,0.9348f,0.3509f,2.5716f,0.51f,0.3285f,-0.795f,0.3731f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.8584f,0.1351f,-0.4948f,0.2451f,-0.0551f,0.9348f,0.3509f,2.5771f,0.51f,0.3285f,-0.795f,0.3607f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.8584f,0.1351f,-0.4948f,-0.0199f,-0.0551f,0.9348f,0.3509f,2.5718f,0.51f,0.3285f,-0.795f,-0.086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.8584f,0.1351f,-0.4948f,0.0252f,-0.0551f,0.9348f,0.3509f,3.1195f,0.51f,0.3285f,-0.795f,0.0491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.8584f,0.1351f,-0.4948f,-0.0199f,-0.0551f,0.9348f,0.3509f,2.5718f,0.51f,0.3285f,-0.795f,-0.086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.9956f,-0.0926f,-0.0145f,-1.0177f,-0.0932f,0.9944f,0.0502f,1.4322f,0.0097f,0.0513f,-0.9986f,-0.2844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9991f,-0.025f,-0.034f,-1.0138f,-0.0274f,0.997f,0.0719f,1.4291f,0.0321f,0.0728f,-0.9968f,-0.097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.9996f,-0.0231f,0.0185f,-1.0098f,-0.0215f,0.9963f,0.0837f,1.4259f,-0.0203f,0.0833f,-0.9963f,0.0905f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9991f,0.0384f,-0.016f,-0.6349f,0.0371f,0.9962f,0.0788f,1.4284f,0.019f,0.0781f,-0.9968f,0.0826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-0.6669f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-0.6669f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-0.6669f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-0.6669f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-0.6669f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-0.6669f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-0.6669f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-0.667f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-0.667f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-0.667f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-0.667f,0f,0f,0f,1.1176f,0f,0f,0f,-1.7285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9998f,-0.0062f,-0.021f,-0.9144f,-0.0066f,0.9998f,0.0166f,2.3182f,0.0209f,0.0168f,-0.9996f,-0.1468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9998f,-0.0062f,-0.021f,-0.9144f,-0.0066f,0.9998f,0.0166f,2.3182f,0.0209f,0.0168f,-0.9996f,-0.1468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9998f,0.0173f,-0.0107f,-0.5195f,0.0174f,0.9998f,-0.0106f,2.4384f,0.0105f,-0.0108f,-0.9999f,-0.246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.5736f,0f,0f,0f,2.1727f,0f,0f,0f,-0.0851f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.9173f,0f,0f,0f,1.1727f,0f,0f,0f,-0.0842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.9173f,0f,0f,0f,1.1727f,0f,0f,0f,-0.0842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.9173f,0f,0f,0f,1.1727f,0f,0f,0f,-0.0842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.9173f,0f,0f,0f,1.1727f,0f,0f,0f,-0.0842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.8861f,0f,0f,0f,2.0477f,0f,0f,0f,-0.0838f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.8861f,0f,0f,0f,2.0477f,0f,0f,0f,-0.0838f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.9958f,0.35f,0.1504f,0.9743f,0.1077f,1.2168f,-0.6076f,2.4207f,-0.2611f,-0.8331f,-0.8244f,-0.0862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.8906f,0f,0f,0f,2.4078f,0f,0f,0f,-0.012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.8906f,0f,0f,0f,2.4078f,0f,0f,0f,-0.012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.985f,0.0615f,0.1612f,0.582f,0.01f,0.9531f,-0.3024f,2.4384f,-0.1722f,-0.2962f,-0.9395f,-0.2412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-1f,0f,0.0044f,0.0125f,0f,1f,0.0006f,1.6104f,-0.0044f,0.0006f,-1f,-0.4004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-1f,0f,0.0044f,0.0125f,0f,1f,0.0006f,1.6104f,-0.0044f,0.0006f,-1f,-0.4004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.9998f,-0.0036f,0.0188f,0.0023f,0f,0.9818f,0.19f,0.4861f,-0.0192f,0.1899f,-0.9816f,0.1286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.9998f,-0.001f,0.0191f,0.0017f,0f,0.9986f,0.0533f,0.9882f,-0.0192f,0.0532f,-0.9984f,0.1616f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9977f,0.0647f,0.0192f,-0.4309f,0.0647f,0.9979f,0.0006f,0.9852f,-0.0191f,0.0018f,-0.9998f,-0.0967f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9977f,-0.0647f,0.0192f,0.4439f,-0.0647f,0.9979f,0.0006f,0.9852f,-0.0191f,-0.0007f,-0.9998f,-0.0799f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.9998f,0.0037f,0.0188f,-0.0007f,0f,0.9808f,-0.1953f,0.985f,-0.0192f,-0.1952f,-0.9806f,0.2866f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.9998f,-0.0047f,0.0186f,0.0137f,0f,0.9688f,0.2477f,0.9854f,-0.0192f,0.2477f,-0.9686f,-0.4632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.9998f,0f,0.0192f,0f,0f,1f,0.0006f,0.6875f,-0.0192f,0.0006f,-0.9998f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-0.6669586472,"py":1.1175956861,"pz":-1.7285200293,"ry":352.7889419612,"rx":4.4442446169},"locator_hand":{"px":0.9173280225,"py":1.1727119977,"pz":-0.0841597451,"ry":0.2524303728,"rx":0.0318522832}},"interactions":{"interaction_mace":{"px":-0.6669617182,"py":1.1175941653,"pz":-1.7285197598,"ry":340.6608634584,"rx":-10.9803137316},"interaction_hand":{"px":0.9173283361,"py":1.172711223,"pz":-0.0841600045,"ry":0.2524303728,"rx":0.0318522832}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/358_locator_locator_cinematic