# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.9476f,0f,-0.3194f,-0.1081f,0f,1f,0f,0.985f,0.3194f,0f,-0.9476f,-0.0708f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.2625f,0.2413f,-0.9343f,0.5193f,-0.1155f,0.9534f,0.2787f,2.6201f,0.958f,0.1811f,-0.2224f,0.0978f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.2625f,0.2413f,-0.9343f,0.5047f,-0.1155f,0.9534f,0.2787f,2.6245f,0.958f,0.1811f,-0.2224f,0.0944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.2625f,0.2413f,-0.9343f,0.0069f,-0.1155f,0.9534f,0.2787f,2.5807f,0.958f,0.1811f,-0.2224f,-0.0473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.2625f,0.2413f,-0.9343f,0.0842f,-0.1155f,0.9534f,0.2787f,3.1344f,0.958f,0.1811f,-0.2224f,0.0406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.2625f,0.2413f,-0.9343f,0.0069f,-0.1155f,0.9534f,0.2787f,2.5807f,0.958f,0.1811f,-0.2224f,-0.0473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.8437f,-0.0516f,-0.5343f,-1.0421f,-0.0984f,0.9934f,0.0594f,1.4346f,0.5277f,0.1027f,-0.8432f,0.2562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.836f,0.0228f,-0.5482f,-0.9411f,-0.0284f,0.996f,0.0847f,1.4297f,0.548f,0.0864f,-0.832f,0.4142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.867f,0.0313f,-0.4974f,-0.8402f,-0.0213f,0.9948f,0.0996f,1.4248f,0.4979f,0.0969f,-0.8618f,0.5721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.8404f,0.0923f,-0.534f,-0.5242f,0.05f,0.9944f,0.0933f,1.4258f,0.5396f,0.0517f,-0.8403f,0.3702f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-1.4972f,0f,0f,0f,1.132f,0f,0f,0f,-1.1611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.8427f,0.0117f,-0.5383f,-0.8749f,-0.0028f,0.9997f,0.026f,2.3188f,0.5384f,0.0234f,-0.8424f,0.3251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.8427f,0.0117f,-0.5383f,-0.8749f,-0.0028f,0.9997f,0.026f,2.3188f,0.5384f,0.0234f,-0.8424f,0.3251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.8511f,0.012f,-0.5248f,-0.5874f,0.0199f,0.9998f,-0.0095f,2.4381f,0.5246f,-0.0186f,-0.8511f,0.0364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.4353f,0f,0f,0f,2.1725f,0f,0f,0f,-0.3815f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.732f,0f,0f,0f,1.1725f,0f,0f,0f,-0.5552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.732f,0f,0f,0f,1.1725f,0f,0f,0f,-0.5552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.732f,0f,0f,0f,1.1725f,0f,0f,0f,-0.5552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.732f,0f,0f,0f,1.1725f,0f,0f,0f,-0.5552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.705f,0f,0f,0f,2.0475f,0f,0f,0f,-0.5394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.705f,0f,0f,0f,2.0475f,0f,0f,0f,-0.5394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.8662f,0.0371f,-0.528f,0.7032f,-0.0074f,1.4882f,0.0606f,2.3897f,0.5286f,0.0816f,-0.8645f,-0.6194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.7032f,0f,0f,0f,2.355f,0f,0f,0f,-0.5462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.7032f,0f,0f,0f,2.355f,0f,0f,0f,-0.5462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.8564f,0.0163f,-0.516f,0.3294f,0.001f,0.9995f,0.03f,2.4381f,0.5162f,0.0252f,-0.8561f,-0.5006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.8629f,0f,-0.5053f,-0.208f,0f,1f,0f,1.61f,0.5053f,0f,-0.8629f,-0.3669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.8629f,0f,-0.5053f,-0.208f,0f,1f,0f,1.61f,0.5053f,0f,-0.8629f,-0.3669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.9476f,0.1493f,-0.2824f,-0.0644f,0f,0.8841f,0.4673f,0.4978f,0.3194f,0.4428f,-0.8378f,0.059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.9476f,0.0679f,-0.3121f,-0.0283f,0f,0.9771f,0.2126f,0.9881f,0.3194f,0.2014f,-0.9259f,0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9397f,0.1222f,-0.3194f,-0.5227f,0.129f,0.9917f,0f,0.985f,0.3168f,-0.0412f,-0.9476f,0.069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9397f,-0.1222f,-0.3194f,0.3064f,-0.129f,0.9917f,0f,0.985f,0.3168f,0.0412f,-0.9476f,-0.2106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.9476f,-0.0422f,-0.3166f,0.0116f,0f,0.9912f,-0.1321f,0.985f,0.3194f,-0.1252f,-0.9393f,0.2846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.9476f,0.1085f,-0.3004f,-0.2279f,0f,0.9405f,0.3398f,0.985f,0.3194f,0.322f,-0.8912f,-0.4262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.9476f,0f,-0.3194f,0f,0f,1f,0f,0.6875f,0.3194f,0f,-0.9476f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-1.4971614616,"py":1.1320298735,"pz":-1.1611128887,"ry":321.4205018877,"rx":5.0015965635},"locator_hand":{"px":0.7319652187,"py":1.1725163998,"pz":-0.5552340597,"ry":329.645703125,"rx":0}},"interactions":{"interaction_mace":{"px":-1.4971639556,"py":1.1320283625,"pz":-1.1611110684,"ry":309.272334624,"rx":-10.402201651},"interaction_hand":{"px":0.7319653568,"py":1.172515625,"pz":-0.5552344423,"ry":329.645703125,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/373_locator_locator_cinematic