# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.8587f,0.5124f,0.1363f,0f,-0.5124f,0.8587f,3.5524f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.8948f,0.4464f,0.5837f,0f,-0.4464f,0.8948f,3.3222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.6137f,0.7896f,1.6186f,0f,-0.7896f,0.6137f,2.3748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.6137f,0.7896f,1.8983f,0f,-0.7896f,0.6137f,2.8297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4984f,0.0461f,1.7274f,0f,-0.0691f,0.9989f,2.894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4984f,0.0461f,1.7274f,0f,-0.0691f,0.9989f,2.894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.7752f,0.6317f,1.3821f,0f,-0.6317f,0.7752f,3.5784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.9111f,0.4121f,0.8547f,0f,-0.4121f,0.9111f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}