# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.5949f,0f,-0.8038f,-0.2721f,0f,1f,0f,0.985f,0.8038f,0f,-0.5949f,0.0486f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [0.1315f,0.357f,-0.9248f,0.3382f,-0.0831f,0.9336f,0.3486f,2.5402f,0.9878f,0.031f,0.1524f,-0.0304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.1315f,0.357f,-0.9248f,0.3238f,-0.0831f,0.9336f,0.3486f,2.5456f,0.9878f,0.031f,0.1524f,-0.0281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.1315f,0.357f,-0.9248f,-0.1911f,-0.0831f,0.9336f,0.3486f,2.5394f,0.9878f,0.031f,0.1524f,0.04f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [0.1315f,0.357f,-0.9248f,-0.0481f,-0.0831f,0.9336f,0.3486f,3.0863f,0.9878f,0.031f,0.1524f,0.0669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [0.1315f,0.357f,-0.9248f,-0.1911f,-0.0831f,0.9336f,0.3486f,2.5394f,0.9878f,0.031f,0.1524f,0.04f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.4548f,0.0174f,-0.8904f,-0.9491f,-0.0942f,0.9933f,0.0676f,1.4373f,0.8856f,0.1146f,-0.4501f,0.8219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.4414f,0.075f,-0.8942f,-0.782f,-0.0252f,0.9951f,0.0959f,1.4301f,0.897f,0.0649f,-0.4373f,0.9065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.4966f,0.0903f,-0.8633f,-0.6148f,-0.017f,0.9934f,0.1137f,1.423f,0.8678f,0.0712f,-0.4917f,0.9911f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.4428f,0.1247f,-0.8879f,-0.4455f,0.0661f,0.9921f,0.1063f,1.4211f,0.8942f,-0.0116f,-0.4476f,0.6565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-2.0665f,0f,0f,0f,1.1494f,0f,0f,0f,-0.166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.4513f,0.0364f,-0.8916f,-0.7575f,0.005f,0.9993f,0.0382f,2.3188f,0.8923f,0.0128f,-0.4512f,0.7949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.4513f,0.0364f,-0.8916f,-0.7575f,0.005f,0.9993f,0.0382f,2.3188f,0.8923f,0.0128f,-0.4512f,0.7949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.4719f,0.0053f,-0.8816f,-0.6536f,0.021f,0.9998f,-0.0053f,2.4381f,0.8814f,-0.021f,-0.4719f,0.4009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,0.0286f,0f,0f,0f,2.1725f,0f,0f,0f,-0.4682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,0.2005f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,0.2005f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,0.2005f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,0.2005f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,0.1849f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,0.1849f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.4775f,-0.0731f,-0.8779f,0.0466f,-0.013f,1.4909f,-0.0487f,2.4594f,0.8792f,-0.0176f,-0.4775f,-0.8066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,0.1839f,0f,0f,0f,2.3679f,0f,0f,0f,-0.7428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,0.1839f,0f,0f,0f,2.3679f,0f,0f,0f,-0.7428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.4884f,-0.0261f,-0.8722f,-0.1223f,-0.0125f,0.9997f,-0.0229f,2.4381f,0.8725f,-0.0003f,-0.4886f,-0.5193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.5f,0f,-0.866f,-0.5233f,0f,1f,0f,1.61f,0.866f,0f,-0.5f,-0.1373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.5f,0f,-0.866f,-0.5233f,0f,1f,0f,1.61f,0.866f,0f,-0.5f,-0.1373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.5949f,0.2362f,-0.7683f,-0.1022f,0f,0.9558f,0.2939f,0.4865f,0.8038f,0.1748f,-0.5687f,0.1743f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.5949f,0.0518f,-0.8021f,-0.0712f,0f,0.9979f,0.0644f,0.9881f,0.8038f,0.0383f,-0.5937f,0.1973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.5935f,0.0413f,-0.8038f,-0.5324f,0.0694f,0.9976f,0f,0.985f,0.8018f,-0.0558f,-0.5949f,0.4002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.5935f,-0.0413f,-0.8038f,-0.0118f,-0.0694f,0.9976f,0f,0.985f,0.8018f,0.0558f,-0.5949f,-0.3031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.5949f,-0.1537f,-0.7889f,0.0293f,0f,0.9816f,-0.1912f,0.985f,0.8038f,-0.1137f,-0.584f,0.2717f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.5949f,0.2042f,-0.7774f,-0.5735f,0f,0.9672f,0.254f,0.985f,0.8038f,0.1511f,-0.5754f,-0.1745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.5949f,0f,-0.8038f,0f,0f,1f,0f,0.6875f,0.8038f,0f,-0.5949f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-2.0665051211,"py":1.1493975894,"pz":-0.166039548,"ry":290.859445798,"rx":5.74299629},"locator_hand":{"px":0.2004890765,"py":1.1725163998,"pz":-0.7658898368,"ry":300.0016992188,"rx":0}},"interactions":{"interaction_mace":{"px":-2.0665063629,"py":1.1493961001,"pz":-0.1660367097,"ry":278.640234062,"rx":-9.5993650958},"interaction_hand":{"px":0.2004890072,"py":1.172515625,"pz":-0.7658902377,"ry":300.0016992188,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/391_locator_locator_cinematic