# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.3459f,0f,-0.9383f,-0.3176f,0f,1f,0f,0.985f,0.9383f,0f,-0.3459f,0.1329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [0.2802f,0.3825f,-0.8805f,0.2537f,-0.0613f,0.9225f,0.3812f,2.5018f,0.958f,-0.0528f,0.2819f,-0.0153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.2802f,0.3825f,-0.8805f,0.2399f,-0.0613f,0.9225f,0.3812f,2.5078f,0.958f,-0.0528f,0.2819f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.2802f,0.3825f,-0.8805f,-0.2583f,-0.0613f,0.9225f,0.3812f,2.5194f,0.958f,-0.0528f,0.2819f,0.1356f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [0.2802f,0.3825f,-0.8805f,-0.0982f,-0.0613f,0.9225f,0.3812f,3.0622f,0.958f,-0.0528f,0.2819f,0.1235f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [0.2802f,0.3825f,-0.8805f,-0.2583f,-0.0613f,0.9225f,0.3812f,2.5194f,0.958f,-0.0528f,0.2819f,0.1356f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.2419f,0.0513f,-0.9689f,-0.8404f,-0.0791f,0.9942f,0.0724f,1.4397f,0.9671f,0.0941f,-0.2365f,1.0608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.2334f,0.0953f,-0.9677f,-0.6588f,-0.0174f,0.9946f,0.1022f,1.4301f,0.9722f,0.0407f,-0.2305f,1.1063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.2929f,0.1143f,-0.9493f,-0.4772f,-0.0086f,0.9925f,0.1222f,1.4206f,0.9561f,0.044f,-0.2897f,1.1518f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.2257f,0.1304f,-0.9654f,-0.3863f,0.0831f,0.99f,0.1143f,1.4145f,0.9707f,-0.0544f,-0.2342f,0.788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-2.1533f,0f,0f,0f,1.1661f,0f,0f,0f,0.3472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.2422f,0.0535f,-0.9688f,-0.6462f,0.0162f,0.9986f,0.051f,2.3178f,0.9701f,-0.0034f,-0.2427f,0.985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.2422f,0.0535f,-0.9688f,-0.6462f,0.0162f,0.9986f,0.051f,2.3178f,0.9701f,-0.0034f,-0.2427f,0.985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.2722f,0.0069f,-0.9622f,-0.6283f,0.0201f,0.9998f,0.0015f,2.4381f,0.962f,-0.019f,-0.2723f,0.5783f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,-0.1383f,0f,0f,0f,2.1725f,0f,0f,0f,-0.412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,-0.0309f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,-0.0309f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,-0.0309f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,-0.0309f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,-0.0407f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,-0.0407f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.1267f,-1.6717f,-0.5873f,0.4431f,-0.3273f,1.2393f,-0.736f,1.9777f,0.9364f,0.207f,-0.3367f,-0.9145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,-0.0923f,0f,0f,0f,2.5009f,0f,0f,0f,-0.7521f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,-0.0923f,0f,0f,0f,2.5009f,0f,0f,0f,-0.7521f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.088f,-0.4296f,-0.8987f,-0.2965f,-0.2003f,0.8914f,-0.4065f,2.4381f,0.9758f,0.1442f,-0.1645f,-0.4311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.3123f,0f,-0.95f,-0.6108f,0f,1f,0f,1.61f,0.95f,0f,-0.3123f,0.0248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.3123f,0f,-0.95f,-0.6108f,0f,1f,0f,1.61f,0.95f,0f,-0.3123f,0.0248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.3459f,0.2474f,-0.9051f,-0.1372f,0f,0.9646f,0.2637f,0.4883f,0.9383f,0.0912f,-0.3337f,0.1994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.3459f,0.096f,-0.9333f,-0.0831f,0f,0.9947f,0.1024f,0.9881f,0.9383f,0.0354f,-0.3441f,0.2194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.3447f,0.0292f,-0.9383f,-0.469f,0.0845f,0.9964f,0f,0.985f,0.9349f,-0.0793f,-0.3459f,0.5434f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.3447f,-0.0292f,-0.9383f,-0.1663f,-0.0845f,0.9964f,0f,0.985f,0.9349f,0.0793f,-0.3459f,-0.2776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.3459f,-0.1653f,-0.9236f,0.0342f,0f,0.9844f,-0.1762f,0.985f,0.9383f,-0.061f,-0.3405f,0.2626f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.3459f,0.259f,-0.9018f,-0.6695f,0f,0.9611f,0.2761f,0.985f,0.9383f,0.0955f,-0.3325f,0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.3459f,0f,-0.9383f,0f,0f,1f,0f,0.6875f,0.9383f,0f,-0.3459f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-2.1532400562,"py":1.1661360586,"pz":0.3472244061,"ry":278.1155667873,"rx":6.5413570163},"locator_hand":{"px":-0.030948438,"py":1.1725163998,"pz":-0.7385245726,"ry":288.1984827492,"rx":0}},"interactions":{"interaction_mace":{"px":-2.1532406604,"py":1.1661346022,"pz":0.3472274606,"ry":265.7738250722,"rx":-8.6989728752},"interaction_hand":{"px":-0.0309485878,"py":1.172515625,"pz":-0.7385249508,"ry":288.1984827492,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/412_locator_locator_cinematic