# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.3069f,0f,-0.9518f,-0.3222f,0f,1f,0f,0.985f,0.9518f,0f,-0.3069f,0.1461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [0.3299f,0.3804f,-0.864f,0.2403f,-0.0603f,0.9218f,0.3829f,2.5001f,0.9421f,-0.0742f,0.327f,-0.0309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.3299f,0.3804f,-0.864f,0.2268f,-0.0603f,0.9218f,0.3829f,2.5061f,0.9421f,-0.0742f,0.327f,-0.0258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.3299f,0.3804f,-0.864f,-0.263f,-0.0603f,0.9218f,0.3829f,2.5187f,0.9421f,-0.0742f,0.327f,0.1465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [0.3299f,0.3804f,-0.864f,-0.103f,-0.0603f,0.9218f,0.3829f,3.0611f,0.9421f,-0.0742f,0.327f,0.1252f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [0.3299f,0.3804f,-0.864f,-0.263f,-0.0603f,0.9218f,0.3829f,2.5187f,0.9421f,-0.0742f,0.327f,0.1465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.195f,0.0575f,-0.9791f,-0.8087f,-0.0723f,0.9947f,0.0728f,1.4403f,0.9781f,0.085f,-0.1898f,1.0982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.189f,0.098f,-0.9771f,-0.6252f,-0.0142f,0.9946f,0.1026f,1.43f,0.9819f,0.0333f,-0.1866f,1.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.2479f,0.1178f,-0.9616f,-0.4417f,-0.0055f,0.9924f,0.123f,1.4198f,0.9688f,0.0357f,-0.2453f,1.1724f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.1781f,0.1293f,-0.9755f,-0.3678f,0.0877f,0.9895f,0.1151f,1.4123f,0.9801f,-0.065f,-0.1876f,0.8048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-2.1542f,0f,0f,0f,1.1705f,0f,0f,0f,0.4469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.197f,0.0575f,-0.9787f,-0.6144f,0.02f,0.9983f,0.0546f,2.3173f,0.9802f,-0.0089f,-0.1979f,1.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.197f,0.0575f,-0.9787f,-0.6144f,0.02f,0.9983f,0.0546f,2.3173f,0.9802f,-0.0089f,-0.1979f,1.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.2295f,0.0082f,-0.9733f,-0.6142f,0.0194f,0.9998f,0.0038f,2.4381f,0.9731f,-0.018f,-0.2297f,0.6039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,-0.1655f,0f,0f,0f,2.1725f,0f,0f,0f,-0.4057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,-0.0717f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,-0.0717f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,-0.0717f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,-0.0717f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,-0.0803f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,-0.0803f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.2016f,-1.6553f,-0.5427f,1.1195f,-0.3976f,1.1662f,-0.7155f,1.4341f,0.8951f,0.1452f,-0.44f,-1.1045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0f,0f,0f,-0.1356f,0f,0f,0f,2.5036f,0f,0f,0f,-0.748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0f,0f,0f,-0.1356f,0f,0f,0f,2.5036f,0f,0f,0f,-0.748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.0416f,-0.4329f,-0.9005f,-0.3244f,-0.2024f,0.8862f,-0.4167f,2.4381f,0.9784f,0.1649f,-0.1244f,-0.4182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.2728f,0f,-0.9621f,-0.6196f,0f,1f,0f,1.61f,0.9621f,0f,-0.2728f,0.0502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.2728f,0f,-0.9621f,-0.6196f,0f,1f,0f,1.61f,0.9621f,0f,-0.2728f,0.0502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.3069f,0.3883f,-0.8689f,-0.1789f,0f,0.913f,0.408f,0.4949f,0.9518f,0.1252f,-0.2802f,0.1923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.3069f,0.1765f,-0.9353f,-0.0843f,0f,0.9827f,0.1854f,0.9881f,0.9518f,0.0569f,-0.3015f,0.2228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.3047f,0.0362f,-0.9518f,-0.4565f,0.118f,0.993f,0f,0.985f,0.9451f,-0.1123f,-0.3069f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.3047f,-0.0362f,-0.9518f,-0.188f,-0.118f,0.993f,0f,0.985f,0.9451f,0.1123f,-0.3069f,-0.2703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.3069f,-0.1362f,-0.942f,0.0347f,0f,0.9897f,-0.1431f,0.985f,0.9518f,-0.0439f,-0.3037f,0.2612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.3069f,0.3085f,-0.9004f,-0.6791f,0f,0.946f,0.3241f,0.985f,0.9518f,0.0995f,-0.2903f,0.031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.3069f,0f,-0.9518f,0f,0f,1f,0f,0.6875f,0.9518f,0f,-0.3069f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-2.1542309481,"py":1.1704545371,"pz":0.4468852118,"ry":275.4920562904,"rx":6.7674951788},"locator_hand":{"px":-0.0717472459,"py":1.1725163998,"pz":-0.736397345,"ry":285.8316526332,"rx":0}},"interactions":{"interaction_mace":{"px":-2.1542314168,"py":1.170453092,"pz":0.4468882953,"ry":275.4920562904,"rx":6.7674951788},"interaction_hand":{"px":-0.0717474111,"py":1.172515625,"pz":-0.7363977167,"ry":285.8316526332,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/419_locator_locator_cinematic