# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.2634f,0f,-0.9647f,-0.3266f,0f,1f,0f,0.985f,0.9647f,0f,-0.2634f,0.1608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [0.3952f,0.3748f,-0.8386f,0.2225f,-0.0599f,0.9215f,0.3837f,2.4998f,0.9166f,-0.1014f,0.3866f,-0.0551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.3952f,0.3748f,-0.8386f,0.2094f,-0.0599f,0.9215f,0.3837f,2.5058f,0.9166f,-0.1014f,0.3866f,-0.0491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.3952f,0.3748f,-0.8386f,-0.2671f,-0.0599f,0.9215f,0.3837f,2.5188f,0.9166f,-0.1014f,0.3866f,0.1572f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [0.3952f,0.3748f,-0.8386f,-0.1087f,-0.0599f,0.9215f,0.3837f,3.0611f,0.9166f,-0.1014f,0.3866f,0.1243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [0.3952f,0.3748f,-0.8386f,-0.2671f,-0.0599f,0.9215f,0.3837f,2.5188f,0.9166f,-0.1014f,0.3866f,0.1572f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.138f,0.0634f,-0.9884f,-0.7683f,-0.0617f,0.9955f,0.0725f,1.4408f,0.9885f,0.071f,-0.1335f,1.1393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.136f,0.0994f,-0.9857f,-0.583f,-0.0095f,0.9948f,0.1016f,1.4298f,0.9907f,0.0231f,-0.1343f,1.1663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.1928f,0.12f,-0.9739f,-0.3978f,-0.0009f,0.9925f,0.1224f,1.4188f,0.9812f,0.0244f,-0.1912f,1.1933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.1209f,0.1256f,-0.9847f,-0.3443f,0.093f,0.989f,0.1147f,1.4093f,0.9883f,-0.0778f,-0.1312f,0.8223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.5641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-2.1488f,0f,0f,0f,1.1752f,0f,0f,0f,0.5641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.1428f,0.0618f,-0.9878f,-0.5747f,0.0252f,0.998f,0.0588f,2.3165f,0.9894f,-0.0165f,-0.1441f,1.0376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.1428f,0.0618f,-0.9878f,-0.5747f,0.0252f,0.998f,0.0588f,2.3165f,0.9894f,-0.0165f,-0.1441f,1.0376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.1783f,0.0103f,-0.9839f,-0.5955f,0.0181f,0.9998f,0.0072f,2.4381f,0.9838f,-0.0165f,-0.1785f,0.6313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,-0.1969f,0f,0f,0f,2.1725f,0f,0f,0f,-0.3991f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,-0.1195f,0f,0f,0f,1.1725f,0f,0f,0f,-0.734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,-0.1195f,0f,0f,0f,1.1725f,0f,0f,0f,-0.734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,-0.1195f,0f,0f,0f,1.1725f,0f,0f,0f,-0.734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,-0.1195f,0f,0f,0f,1.1725f,0f,0f,0f,-0.734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,-0.1265f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,-0.1265f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.3092f,-1.5142f,-0.2072f,1.9632f,-0.6238f,0.5478f,-0.773f,0.85f,0.7935f,-0.1594f,-0.6885f,-1.1952f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0.005f,-0.1887f,-0.3948f,-0.1854f,-0.0883f,0.3863f,-0.1857f,2.5049f,0.4286f,0.0818f,-0.0337f,-0.7431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0.005f,-0.1887f,-0.3948f,-0.1854f,-0.0883f,0.3863f,-0.1857f,2.5049f,0.4286f,0.0818f,-0.0337f,-0.7431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [0.0114f,-0.4311f,-0.9022f,-0.3562f,-0.2018f,0.8827f,-0.4244f,2.4381f,0.9794f,0.1869f,-0.077f,-0.4039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.2252f,0f,-0.9743f,-0.6281f,0f,1f,0f,1.61f,0.9743f,0f,-0.2252f,0.0785f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.2252f,0f,-0.9743f,-0.6281f,0f,1f,0f,1.61f,0.9743f,0f,-0.2252f,0.0785f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.2634f,0.4691f,-0.843f,-0.1893f,0f,0.8738f,0.4863f,0.4966f,0.9647f,0.1281f,-0.2301f,0.1983f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.2634f,0.1947f,-0.9448f,-0.0854f,0f,0.9794f,0.2018f,0.9881f,0.9647f,0.0531f,-0.2579f,0.2267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.2613f,0.0328f,-0.9647f,-0.4418f,0.1246f,0.9922f,0f,0.985f,0.9572f,-0.1202f,-0.2634f,0.5829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.2613f,-0.0328f,-0.9647f,-0.2114f,-0.1246f,0.9922f,0f,0.985f,0.9572f,0.1202f,-0.2634f,-0.2612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.2634f,-0.1316f,-0.9557f,0.0352f,0f,0.9906f,-0.1365f,0.985f,0.9647f,-0.0359f,-0.2609f,0.2596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.2634f,0.3218f,-0.9094f,-0.6883f,0f,0.9427f,0.3336f,0.985f,0.9647f,0.0878f,-0.2483f,0.0621f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.2634f,0f,-0.9647f,0f,0f,1f,0f,0.6875f,0.9647f,0f,-0.2634f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-2.1488221253,"py":1.1751978631,"pz":0.5640524279,"ry":272.3769733026,"rx":7.0383270366},"locator_hand":{"px":-0.1194801861,"py":1.1725163998,"pz":-0.7340453244,"ry":283.0156675454,"rx":0}},"interactions":{"interaction_mace":{"px":-2.1488224311,"py":1.1751964335,"pz":0.5640555391,"ry":259.9283157905,"rx":-8.1136118281},"interaction_hand":{"px":-0.1194803694,"py":1.172515625,"pz":-0.7340456875,"ry":283.0156675454,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/429_locator_locator_cinematic