# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.8894f,0.4571f,0.3542f,0f,-0.4571f,0.8894f,3.4782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9323f,0.3618f,0.821f,0f,-0.3618f,0.9323f,3.2903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.7169f,0.6972f,1.9813f,0f,-0.6972f,0.7169f,2.4782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.7169f,0.6972f,2.1955f,0f,-0.6972f,0.7169f,2.9674f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4974f,0.0586f,2.0162f,0f,-0.0878f,0.9983f,3.0098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4974f,0.0586f,2.0162f,0f,-0.0878f,0.9983f,3.0098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.853f,0.522f,1.5823f,0f,-0.522f,0.853f,3.6418f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.9545f,0.2982f,1.0715f,0f,-0.2982f,0.9545f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}