# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.2444f,0f,-0.9697f,-0.3283f,0f,1f,0f,0.985f,0.9697f,0f,-0.2444f,0.1673f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [0.4294f,0.3705f,-0.8236f,0.2128f,-0.0603f,0.9217f,0.3832f,2.5007f,0.9011f,-0.1149f,0.4181f,-0.0697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.4294f,0.3705f,-0.8236f,0.1999f,-0.0603f,0.9217f,0.3832f,2.5067f,0.9011f,-0.1149f,0.4181f,-0.0632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.4294f,0.3705f,-0.8236f,-0.2685f,-0.0603f,0.9217f,0.3832f,2.5195f,0.9011f,-0.1149f,0.4181f,0.1609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [0.4294f,0.3705f,-0.8236f,-0.1115f,-0.0603f,0.9217f,0.3832f,3.0619f,0.9011f,-0.1149f,0.4181f,0.1224f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [0.4294f,0.3705f,-0.8236f,-0.2685f,-0.0603f,0.9217f,0.3832f,2.5195f,0.9011f,-0.1149f,0.4181f,0.1609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.1095f,0.0653f,-0.9918f,-0.7479f,-0.0539f,0.996f,0.0715f,1.441f,0.9925f,0.0613f,-0.1056f,1.1577f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.1103f,0.0987f,-0.989f,-0.5621f,-0.0061f,0.995f,0.0999f,1.4296f,0.9939f,0.017f,-0.1092f,1.1798f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.165f,0.1194f,-0.979f,-0.3762f,0.0022f,0.9927f,0.1207f,1.4181f,0.9863f,0.0177f,-0.164f,1.2019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.0926f,0.1221f,-0.9882f,-0.3326f,0.0958f,0.9889f,0.1132f,1.4074f,0.9911f,-0.0841f,-0.1032f,0.8296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-2.144f,0f,0f,0f,1.1774f,0f,0f,0f,0.6203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.1163f,0.0639f,-0.9912f,-0.5549f,0.0285f,0.9977f,0.061f,2.3158f,0.9928f,-0.0211f,-0.1178f,1.0482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.1163f,0.0639f,-0.9912f,-0.5549f,0.0285f,0.9977f,0.061f,2.3158f,0.9928f,-0.0211f,-0.1178f,1.0482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.1534f,0.0118f,-0.9881f,-0.5857f,0.0169f,0.9998f,0.0093f,2.4381f,0.988f,-0.0153f,-0.1535f,0.6428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,-0.2115f,0f,0f,0f,2.1725f,0f,0f,0f,-0.3968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,-0.1421f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,-0.1421f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,-0.1421f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,-0.1421f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,-0.1484f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,-0.1484f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.3666f,-1.1332f,0.1205f,2.5354f,-0.7584f,0.2203f,-0.7209f,0.4866f,0.65f,-0.382f,-0.7732f,-1.2277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0.0298f,-0.3622f,-0.7662f,-0.2084f,-0.1694f,0.7487f,-0.3605f,2.5042f,0.8304f,0.1657f,-0.046f,-0.7412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0.0298f,-0.3622f,-0.7662f,-0.2084f,-0.1694f,0.7487f,-0.3605f,2.5042f,0.8304f,0.1657f,-0.046f,-0.7412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [0.0351f,-0.4271f,-0.9035f,-0.3709f,-0.1997f,0.8828f,-0.4251f,2.4381f,0.9792f,0.1954f,-0.0543f,-0.3978f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.2021f,0f,-0.9794f,-0.6313f,0f,1f,0f,1.61f,0.9794f,0f,-0.2021f,0.0909f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.2021f,0f,-0.9794f,-0.6313f,0f,1f,0f,1.61f,0.9794f,0f,-0.2021f,0.0909f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.2444f,0.3854f,-0.8898f,-0.1544f,0f,0.9176f,0.3974f,0.49f,0.9697f,0.0971f,-0.2242f,0.2111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.2444f,0.1244f,-0.9617f,-0.0859f,0f,0.9917f,0.1283f,0.9881f,0.9697f,0.0313f,-0.2424f,0.2284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.2433f,0.0232f,-0.9697f,-0.4352f,0.0949f,0.9955f,0f,0.985f,0.9653f,-0.0921f,-0.2444f,0.5915f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.2433f,-0.0232f,-0.9697f,-0.2214f,-0.0949f,0.9955f,0f,0.985f,0.9653f,0.0921f,-0.2444f,-0.257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.2444f,-0.1609f,-0.9562f,0.0354f,0f,0.9861f,-0.1659f,0.985f,0.9697f,-0.0406f,-0.241f,0.2589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.2444f,0.2822f,-0.9277f,-0.6919f,0f,0.9567f,0.2911f,0.985f,0.9697f,0.0711f,-0.2338f,0.0756f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.2444f,0f,-0.9697f,0f,0f,1f,0f,0.6875f,0.9697f,0f,-0.2444f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-2.144021322,"py":1.1773651865,"pz":0.6202545421,"ry":270.8694408251,"rx":7.1835528716},"locator_hand":{"px":-0.1420612684,"py":1.1725163998,"pz":-0.7334715735,"ry":281.6621106885,"rx":0}},"interactions":{"interaction_mace":{"px":-2.1440215483,"py":1.1773637668,"pz":0.6202576646,"ry":258.3795596262,"rx":-7.9342524134},"interaction_hand":{"px":-0.1420614602,"py":1.172515625,"pz":-0.7334719322,"ry":281.6621106885,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/436_locator_locator_cinematic