# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.2387f,0f,-0.9711f,-0.3288f,0f,1f,0f,0.985f,0.9711f,0f,-0.2387f,0.1692f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [0.4424f,0.3685f,-0.8176f,0.2092f,-0.0606f,0.9219f,0.3827f,2.5015f,0.8948f,-0.1197f,0.4302f,-0.076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.4424f,0.3685f,-0.8176f,0.1964f,-0.0606f,0.9219f,0.3827f,2.5075f,0.8948f,-0.1197f,0.4302f,-0.0693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.4424f,0.3685f,-0.8176f,-0.2688f,-0.0606f,0.9219f,0.3827f,2.52f,0.8948f,-0.1197f,0.4302f,0.1615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [0.4424f,0.3685f,-0.8176f,-0.1126f,-0.0606f,0.9219f,0.3827f,3.0625f,0.8948f,-0.1197f,0.4302f,0.1211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [0.4424f,0.3685f,-0.8176f,-0.2688f,-0.0606f,0.9219f,0.3827f,2.52f,0.8948f,-0.1197f,0.4302f,0.1615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.0989f,0.0655f,-0.9929f,-0.7407f,-0.0493f,0.9963f,0.0707f,1.441f,0.9939f,0.0559f,-0.0953f,1.1638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.1013f,0.0976f,-0.9901f,-0.5547f,-0.0042f,0.9951f,0.0986f,1.4294f,0.9949f,0.0141f,-0.1004f,1.1842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.1544f,0.1185f,-0.9809f,-0.3687f,0.004f,0.9929f,0.1193f,1.4178f,0.988f,0.0145f,-0.1538f,1.2045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.0821f,0.1199f,-0.9894f,-0.3286f,0.0969f,0.989f,0.1119f,1.4065f,0.9919f,-0.0866f,-0.0929f,0.8318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-2.1422f,0f,0f,0f,1.1781f,0f,0f,0f,0.6403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.1067f,0.0649f,-0.9922f,-0.5478f,0.0302f,0.9976f,0.062f,2.3155f,0.9938f,-0.0233f,-0.1084f,1.0511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.1067f,0.0649f,-0.9922f,-0.5478f,0.0302f,0.9976f,0.062f,2.3155f,0.9938f,-0.0233f,-0.1084f,1.0511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.1445f,0.0127f,-0.9894f,-0.582f,0.0163f,0.9998f,0.0105f,2.4381f,0.9894f,-0.0146f,-0.1447f,0.6461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,-0.2165f,0f,0f,0f,2.1725f,0f,0f,0f,-0.3965f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,-0.1498f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,-0.1498f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,-0.1498f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,-0.1498f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,-0.1559f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,-0.1559f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [-0.3649f,-0.9042f,0.2218f,2.7524f,-0.7495f,0.1439f,-0.6462f,0.3487f,0.5524f,-0.4021f,-0.7302f,-1.2475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0.0426f,-0.4242f,-0.9046f,-0.216f,-0.1982f,0.8838f,-0.4238f,2.5034f,0.9792f,0.1973f,-0.0464f,-0.741f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0.0426f,-0.4242f,-0.9046f,-0.216f,-0.1982f,0.8838f,-0.4238f,2.5034f,0.9792f,0.1973f,-0.0464f,-0.741f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [0.0426f,-0.4242f,-0.9046f,-0.3759f,-0.1982f,0.8838f,-0.4238f,2.4381f,0.9792f,0.1973f,-0.0464f,-0.3962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.194f,0f,-0.981f,-0.6322f,0f,1f,0f,1.61f,0.981f,0f,-0.194f,0.0946f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.194f,0f,-0.981f,-0.6322f,0f,1f,0f,1.61f,0.981f,0f,-0.194f,0.0946f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.2387f,0.3062f,-0.9216f,-0.1295f,0f,0.949f,0.3153f,0.487f,0.9711f,0.0753f,-0.2265f,0.2182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.2387f,0.0745f,-0.9682f,-0.086f,0f,0.9971f,0.0767f,0.9881f,0.9711f,0.0183f,-0.238f,0.2289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.238f,0.0177f,-0.9711f,-0.4332f,0.0743f,0.9972f,0f,0.985f,0.9684f,-0.0721f,-0.2387f,0.5941f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.238f,-0.0177f,-0.9711f,-0.2243f,-0.0743f,0.9972f,0f,0.985f,0.9684f,0.0721f,-0.2387f,-0.2557f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.2387f,-0.181f,-0.9541f,0.0354f,0f,0.9825f,-0.1864f,0.985f,0.9711f,-0.0445f,-0.2345f,0.2587f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.2387f,0.2536f,-0.9374f,-0.6929f,0f,0.9653f,0.2612f,0.985f,0.9711f,0.0623f,-0.2304f,0.0797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.2387f,0f,-0.9711f,0f,0f,1f,0f,0.6875f,0.9711f,0f,-0.2387f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left2) {transformation: [-0.3668f,-0.9024f,0.2261f,2.7448f,-0.7463f,0.1403f,-0.6506f,0.3502f,0.5554f,-0.4073f,-0.725f,-1.2546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-2.142205019,"py":1.1781265588,"pz":0.6402602614,"ry":270.3313005822,"rx":7.2476195868},"locator_hand":{"px":-0.1498132389,"py":1.1725163998,"pz":-0.7337643911,"ry":281.188839012,"rx":0}},"interactions":{"interaction_mace":{"px":-2.142205217,"py":1.1781251443,"pz":0.6402633881,"ry":257.819363388,"rx":-7.8518910837},"interaction_hand":{"px":-0.1498134337,"py":1.172515625,"pz":-0.7337647482,"ry":281.188839012,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/440_locator_locator_cinematic