# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.2371f,0f,-0.9715f,-0.3289f,0f,1f,0f,0.985f,0.9715f,0f,-0.2371f,0.1697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [0.4495f,0.3671f,-0.8144f,0.2074f,-0.0611f,0.9222f,0.3819f,2.5025f,0.8912f,-0.122f,0.437f,-0.0803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.4495f,0.3671f,-0.8144f,0.1946f,-0.0611f,0.9222f,0.3819f,2.5085f,0.8912f,-0.122f,0.437f,-0.0735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.4495f,0.3671f,-0.8144f,-0.2686f,-0.0611f,0.9222f,0.3819f,2.5206f,0.8912f,-0.122f,0.437f,0.161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [0.4495f,0.3671f,-0.8144f,-0.1131f,-0.0611f,0.9222f,0.3819f,3.0632f,0.8912f,-0.122f,0.437f,0.1197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [0.4495f,0.3671f,-0.8144f,-0.2686f,-0.0611f,0.9222f,0.3819f,2.5206f,0.8912f,-0.122f,0.437f,0.161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.093f,0.0652f,-0.9935f,-0.7374f,-0.0447f,0.9966f,0.0696f,1.441f,0.9947f,0.0509f,-0.0898f,1.1666f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.097f,0.0962f,-0.9906f,-0.5513f,-0.0023f,0.9953f,0.0969f,1.4292f,0.9953f,0.0116f,-0.0963f,1.1861f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.1485f,0.117f,-0.982f,-0.3652f,0.0056f,0.9931f,0.1175f,1.4175f,0.9889f,0.012f,-0.1481f,1.2055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.0766f,0.1179f,-0.9901f,-0.327f,0.0976f,0.9891f,0.1102f,1.4056f,0.9923f,-0.0882f,-0.0873f,0.8327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-2.1417f,0f,0f,0f,1.1785f,0f,0f,0f,0.6501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.1019f,0.0656f,-0.9926f,-0.5443f,0.0317f,0.9975f,0.0627f,2.3151f,0.9943f,-0.0251f,-0.1038f,1.0516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.1019f,0.0656f,-0.9926f,-0.5443f,0.0317f,0.9975f,0.0627f,2.3151f,0.9943f,-0.0251f,-0.1038f,1.0516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.1402f,0.0136f,-0.99f,-0.5802f,0.0155f,0.9998f,0.0116f,2.4381f,0.99f,-0.0138f,-0.1404f,0.6469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,-0.2186f,0f,0f,0f,2.1725f,0f,0f,0f,-0.3971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,-0.1532f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,-0.1532f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,-0.1532f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,-0.1532f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,-0.1592f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,-0.1592f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [0f,0f,0f,2.7471f,0f,0f,0f,0.3487f,0f,0f,0f,-1.2594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0.045f,-0.4211f,-0.9059f,-0.219f,-0.1965f,0.8854f,-0.4213f,2.5024f,0.9795f,0.197f,-0.0429f,-0.7416f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0.045f,-0.4211f,-0.9059f,-0.219f,-0.1965f,0.8854f,-0.4213f,2.5024f,0.9795f,0.197f,-0.0429f,-0.7416f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [0.045f,-0.4211f,-0.9059f,-0.378f,-0.1965f,0.8854f,-0.4213f,2.4381f,0.9795f,0.197f,-0.0429f,-0.3962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.1903f,0f,-0.9817f,-0.6325f,0f,1f,0f,1.61f,0.9817f,0f,-0.1903f,0.0956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.1903f,0f,-0.9817f,-0.6325f,0f,1f,0f,1.61f,0.9817f,0f,-0.1903f,0.0956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.2371f,0.2254f,-0.945f,-0.1076f,0f,0.9727f,0.2321f,0.4855f,0.9715f,0.055f,-0.2307f,0.2237f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.2371f,0.0308f,-0.971f,-0.086f,0f,0.9995f,0.0317f,0.9881f,0.9715f,0.0075f,-0.237f,0.229f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.2368f,0.0133f,-0.9715f,-0.4326f,0.0563f,0.9984f,0f,0.985f,0.9699f,-0.0547f,-0.2371f,0.5947f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.2368f,-0.0133f,-0.9715f,-0.2251f,-0.0563f,0.9984f,0f,0.985f,0.9699f,0.0547f,-0.2371f,-0.2553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.2371f,-0.1982f,-0.951f,0.0354f,0f,0.979f,-0.2041f,0.985f,0.9715f,-0.0484f,-0.2321f,0.2586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.2371f,0.2282f,-0.9443f,-0.6932f,0f,0.972f,0.2349f,0.985f,0.9715f,0.0557f,-0.2305f,0.0808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.2371f,0f,-0.9715f,0f,0f,1f,0f,0.6875f,0.9715f,0f,-0.2371f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm3) {transformation: [-0.0151f,-0.1372f,0.0637f,2.7007f,-0.1501f,0.0213f,0.0103f,0.3051f,-0.0182f,-0.0619f,-0.1376f,-1.1417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm2) {transformation: [-0.0151f,-0.1372f,0.0637f,2.7007f,-0.1501f,0.0213f,0.0103f,0.3051f,-0.0182f,-0.0619f,-0.1376f,-1.1417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-2.1416610834,"py":1.1785146229,"pz":0.6501429592,"ry":270.0669877709,"rx":7.2966254568},"locator_hand":{"px":-0.1532077631,"py":1.1725163998,"pz":-0.7345932008,"ry":280.9711964929,"rx":0}},"interactions":{"interaction_mace":{"px":-2.1416612675,"py":1.1785132132,"pz":0.6501460889,"ry":270.0669877709,"rx":7.2966254568},"interaction_hand":{"px":-0.1532079593,"py":1.172515625,"pz":-0.7345935572,"ry":280.9711964929,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/444_locator_locator_cinematic