# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.248f,0f,-0.9688f,-0.328f,0f,1f,0f,0.985f,0.9688f,0f,-0.248f,0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [0.4424f,0.3669f,-0.8183f,0.2108f,-0.0622f,0.9229f,0.3801f,2.5047f,0.8947f,-0.1172f,0.4311f,-0.0809f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.4424f,0.3669f,-0.8183f,0.198f,-0.0622f,0.9229f,0.3801f,2.5107f,0.8947f,-0.1172f,0.4311f,-0.0742f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.4424f,0.3669f,-0.8183f,-0.2672f,-0.0622f,0.9229f,0.3801f,2.5217f,0.8947f,-0.1172f,0.4311f,0.1566f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [0.4424f,0.3669f,-0.8183f,-0.112f,-0.0622f,0.9229f,0.3801f,3.0646f,0.8947f,-0.1172f,0.4311f,0.1176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [0.4424f,0.3669f,-0.8183f,-0.2672f,-0.0622f,0.9229f,0.3801f,2.5217f,0.8947f,-0.1172f,0.4311f,0.1566f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.0979f,0.0631f,-0.9932f,-0.7448f,-0.0356f,0.9971f,0.0669f,1.4406f,0.9946f,0.0419f,-0.0954f,1.1608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.1048f,0.0923f,-0.9902f,-0.5588f,0.0013f,0.9957f,0.0927f,1.4288f,0.9945f,0.0084f,-0.1045f,1.1816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.1526f,0.1128f,-0.9818f,-0.3729f,0.0086f,0.9936f,0.1128f,1.4169f,0.9882f,0.0088f,-0.1526f,1.2024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.0824f,0.1141f,-0.99f,-0.3321f,0.098f,0.9895f,0.1058f,1.4041f,0.9918f,-0.0883f,-0.0927f,0.8298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-2.1456f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-2.1456f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-2.1456f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-2.1457f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-2.1457f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-2.1456f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-2.1456f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-2.1456f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-2.1456f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-2.1456f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-2.1456f,0f,0f,0f,1.1781f,0f,0f,0f,0.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.1088f,0.0666f,-0.9918f,-0.5501f,0.0343f,0.9974f,0.0632f,2.3143f,0.9935f,-0.0272f,-0.1108f,1.045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.1088f,0.0666f,-0.9918f,-0.5501f,0.0343f,0.9974f,0.0632f,2.3143f,0.9935f,-0.0272f,-0.1108f,1.045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.1476f,0.0154f,-0.9889f,-0.5828f,0.014f,0.9998f,0.0135f,2.4381f,0.9889f,-0.0119f,-0.1478f,0.6402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,-0.213f,0f,0f,0f,2.1725f,0f,0f,0f,-0.4009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,-0.1449f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7379f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,-0.1449f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7379f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,-0.1449f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7379f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,-0.1449f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,-0.1511f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,-0.1511f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [0f,0f,0f,2.7594f,0f,0f,0f,0.3487f,0f,0f,0f,-1.2398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0.0324f,-0.4148f,-0.9094f,-0.209f,-0.1932f,0.8901f,-0.4128f,2.4995f,0.9806f,0.189f,-0.0513f,-0.7451f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0.0324f,-0.4148f,-0.9094f,-0.209f,-0.1932f,0.8901f,-0.4128f,2.4995f,0.9806f,0.189f,-0.0513f,-0.7451f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [0.0324f,-0.4148f,-0.9094f,-0.3723f,-0.1932f,0.8901f,-0.4128f,2.4381f,0.9806f,0.189f,-0.0513f,-0.4012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.198f,0f,-0.9802f,-0.6307f,0f,1f,0f,1.61f,0.9802f,0f,-0.198f,0.0886f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.198f,0f,-0.9802f,-0.6307f,0f,1f,0f,1.61f,0.9802f,0f,-0.198f,0.0886f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.248f,0.1369f,-0.959f,-0.0938f,0f,0.99f,0.1413f,0.485f,0.9688f,0.035f,-0.2455f,0.226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.248f,0.0038f,-0.9688f,-0.0858f,0f,1f,0.004f,0.9881f,0.9688f,0.001f,-0.248f,0.228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.2477f,0.0112f,-0.9688f,-0.4365f,0.0452f,0.999f,0f,0.985f,0.9678f,-0.0438f,-0.248f,0.5899f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.2477f,-0.0112f,-0.9688f,-0.2195f,-0.0452f,0.999f,0f,0.985f,0.9678f,0.0438f,-0.248f,-0.2578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.248f,-0.2082f,-0.9461f,0.0353f,0f,0.9766f,-0.2149f,0.985f,0.9688f,-0.0533f,-0.2422f,0.259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.248f,0.2119f,-0.9453f,-0.6913f,0f,0.9758f,0.2188f,0.985f,0.9688f,0.0542f,-0.242f,0.0731f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.248f,0f,-0.9688f,0f,0f,1f,0f,0.6875f,0.9688f,0f,-0.248f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm3) {transformation: [-0.0621f,-0.5631f,0.2616f,2.7007f,-0.6164f,0.0876f,0.0422f,0.3051f,-0.0748f,-0.2542f,-0.565f,-1.1417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm2) {transformation: [-0.0621f,-0.5631f,0.2616f,2.7007f,-0.6164f,0.0876f,0.0422f,0.3051f,-0.0748f,-0.2542f,-0.565f,-1.1417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-2.1456341549,"py":1.1780880212,"pz":0.6352782832,"ry":270.483735367,"rx":7.3453287069},"locator_hand":{"px":-0.1449237031,"py":1.1725163998,"pz":-0.7378510131,"ry":281.4221896631,"rx":0}},"interactions":{"interaction_mace":{"px":-2.145634362,"py":1.1780866195,"pz":0.6352814151,"ry":270.483735367,"rx":7.3453287069},"interaction_hand":{"px":-0.1449238965,"py":1.172515625,"pz":-0.737851371,"ry":281.4221896631,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/452_locator_locator_cinematic