# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.261f,0f,-0.9653f,-0.3268f,0f,1f,0f,0.985f,0.9653f,0f,-0.261f,0.1617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [0.426f,0.3683f,-0.8264f,0.2165f,-0.0629f,0.9232f,0.379f,2.5058f,0.9025f,-0.1095f,0.4165f,-0.0761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.426f,0.3683f,-0.8264f,0.2036f,-0.0629f,0.9232f,0.379f,2.5118f,0.9025f,-0.1095f,0.4165f,-0.0696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.426f,0.3683f,-0.8264f,-0.2657f,-0.0629f,0.9232f,0.379f,2.5223f,0.9025f,-0.1095f,0.4165f,0.1526f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [0.426f,0.3683f,-0.8264f,-0.1102f,-0.0629f,0.9232f,0.379f,3.0653f,0.9025f,-0.1095f,0.4165f,0.1171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [0.426f,0.3683f,-0.8264f,-0.2657f,-0.0629f,0.9232f,0.379f,2.5223f,0.9025f,-0.1095f,0.4165f,0.1526f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.1098f,0.0614f,-0.9921f,-0.7563f,-0.0312f,0.9974f,0.0652f,1.4404f,0.9935f,0.0381f,-0.1076f,1.1516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.118f,0.0898f,-0.9889f,-0.5707f,0.003f,0.9959f,0.0901f,1.4285f,0.993f,0.0077f,-0.1178f,1.1747f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.1638f,0.1101f,-0.9803f,-0.385f,0.0099f,0.9939f,0.1099f,1.4167f,0.9865f,0.0083f,-0.1639f,1.1979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.0949f,0.1124f,-0.9891f,-0.3394f,0.0976f,0.9899f,0.1031f,1.4035f,0.9907f,-0.0868f,-0.1049f,0.8259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-2.1503f,0f,0f,0f,1.1772f,0f,0f,0f,0.6083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.1215f,0.067f,-0.9903f,-0.5602f,0.0353f,0.9974f,0.0631f,2.3139f,0.992f,-0.0273f,-0.1236f,1.0374f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.1215f,0.067f,-0.9903f,-0.5602f,0.0353f,0.9974f,0.0631f,2.3139f,0.992f,-0.0273f,-0.1236f,1.0374f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.1603f,0.0162f,-0.9869f,-0.5875f,0.0132f,0.9998f,0.0143f,2.4381f,0.987f,-0.0107f,-0.1605f,0.6323f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0f,0f,0f,-0.2046f,0f,0f,0f,2.1725f,0f,0f,0f,-0.404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0f,0f,0f,-0.1322f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0f,0f,0f,-0.1322f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0f,0f,0f,-0.1322f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0f,0f,0f,-0.1322f,0f,0f,0f,1.1725f,0f,0f,0f,-0.7401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0f,0f,0f,-0.1388f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0f,0f,0f,-0.1388f,0f,0f,0f,2.0475f,0f,0f,0f,-0.7095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [0f,0f,0f,2.7782f,0f,0f,0f,0.3487f,0f,0f,0f,-1.2051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [0.0163f,-0.4116f,-0.9112f,-0.195f,-0.1918f,0.8931f,-0.4069f,2.4979f,0.9813f,0.1814f,-0.0643f,-0.7478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [0.0163f,-0.4116f,-0.9112f,-0.195f,-0.1918f,0.8931f,-0.4069f,2.4979f,0.9813f,0.1814f,-0.0643f,-0.7478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [0.0163f,-0.4116f,-0.9112f,-0.3639f,-0.1918f,0.8931f,-0.4069f,2.4381f,0.9813f,0.1814f,-0.0643f,-0.4064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.2105f,0f,-0.9776f,-0.6285f,0f,1f,0f,1.61f,0.9776f,0f,-0.2105f,0.0801f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.2105f,0f,-0.9776f,-0.6285f,0f,1f,0f,1.61f,0.9776f,0f,-0.2105f,0.0801f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.261f,0.157f,-0.9525f,-0.1069f,0f,0.9867f,0.1627f,0.4855f,0.9653f,0.0424f,-0.2575f,0.2211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.261f,0.0306f,-0.9649f,-0.0855f,0f,0.9995f,0.0317f,0.9881f,0.9653f,0.0083f,-0.2608f,0.2269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.2606f,0.0147f,-0.9653f,-0.441f,0.0563f,0.9984f,0f,0.985f,0.9638f,-0.0543f,-0.261f,0.584f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.2606f,-0.0147f,-0.9653f,-0.2126f,-0.0563f,0.9984f,0f,0.985f,0.9638f,0.0543f,-0.261f,-0.2607f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.261f,-0.197f,-0.945f,0.0352f,0f,0.979f,-0.2041f,0.985f,0.9653f,-0.0533f,-0.2555f,0.2595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.261f,0.2268f,-0.9383f,-0.6888f,0f,0.972f,0.2349f,0.985f,0.9653f,0.0613f,-0.2537f,0.0638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.261f,0f,-0.9653f,0f,0f,1f,0f,0.6875f,0.9653f,0f,-0.261f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm3) {transformation: [-0.0844f,-0.7653f,0.3555f,2.7007f,-0.8376f,0.119f,0.0574f,0.3051f,-0.1017f,-0.3454f,-0.7678f,-1.1417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm2) {transformation: [-0.0844f,-0.7653f,0.3555f,2.7007f,-0.8376f,0.119f,0.0574f,0.3051f,-0.1017f,-0.3454f,-0.7678f,-1.1417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-2.1502965956,"py":1.1772331022,"pz":0.6083446458,"ry":271.2267769959,"rx":7.3429861773},"locator_hand":{"px":-0.1322303025,"py":1.1725163998,"pz":-0.7400752974,"ry":282.1505207204,"rx":0}},"interactions":{"interaction_mace":{"px":-2.1502968429,"py":1.1772317037,"pz":0.6083477762,"ry":271.2267769959,"rx":7.3429861773},"interaction_hand":{"px":-0.1322304912,"py":1.172515625,"pz":-0.7400756577,"ry":282.1505207204,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/456_locator_locator_cinematic