# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0134f,0f,0f,0f,0f,-0.0086f,0.0103f,0.2632f,0f,0.0103f,0.0086f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0128f,0.004f,0.0003f,-0.0757f,0.0039f,-0.0127f,0.0012f,1.2844f,-0.0006f,0.001f,0.0133f,-1.1246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0128f,0.004f,0.0003f,-0.0763f,0.0039f,-0.0127f,0.0012f,1.2874f,-0.0006f,0.001f,0.0133f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0132f,-0.0023f,0.0005f,-0.9253f,-0.0023f,-0.012f,0.0056f,0.9666f,0.0005f,0.0056f,0.0122f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0133f,0.0012f,0f,0f,0.0011f,-0.0125f,0.0046f,0.4255f,-0.0004f,0.0046f,0.0126f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.078f,0f,0f,0f,0f,1.0444f,0.2671f,0.4476f,0f,-0.2671f,1.0444f,3.347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.078f,0f,0f,0f,0f,1.0631f,0.1786f,0.9814f,0f,-0.1786f,1.0631f,3.2505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.078f,0f,0f,0f,0f,0.8505f,0.6623f,2.3271f,0f,-0.6623f,0.8505f,2.5089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.078f,0f,0f,0f,0f,0.8505f,0.6623f,2.4988f,0f,-0.6623f,0.8505f,3.0583f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.078f,0f,0f,-0.5929f,0f,1.6141f,0.0634f,2.2989f,0f,-0.0951f,1.0761f,3.0807f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.078f,0f,0f,0.5929f,0f,1.6141f,0.0634f,2.2989f,0f,-0.0951f,1.0761f,3.0807f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.078f,0f,0f,0f,0f,0.9744f,0.461f,1.7609f,0f,-0.461f,0.9744f,3.708f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.078f,0f,0f,0f,0f,1.0555f,0.219f,1.2307f,0f,-0.219f,1.0555f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/47_locator_locator_cinematic