# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.9085f,0f,-0.418f,-0.1415f,0f,1f,0f,0.985f,0.418f,0f,-0.9085f,-0.0575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.8792f,0.1093f,-0.4637f,0.1249f,-0.0701f,0.9331f,0.3528f,2.5217f,0.4712f,0.3427f,-0.8127f,0.4698f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.8792f,0.1093f,-0.4637f,0.1176f,-0.0701f,0.9331f,0.3528f,2.5272f,0.4712f,0.3427f,-0.8127f,0.4571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.8792f,0.1093f,-0.4637f,-0.1275f,-0.0701f,0.9331f,0.3528f,2.5231f,0.4712f,0.3427f,-0.8127f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.8792f,0.1093f,-0.4637f,-0.095f,-0.0701f,0.9331f,0.3528f,3.07f,0.4712f,0.3427f,-0.8127f,0.1412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.8792f,0.1093f,-0.4637f,-0.1275f,-0.0701f,0.9331f,0.3528f,2.5231f,0.4712f,0.3427f,-0.8127f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.8894f,0.0178f,-0.4567f,-1.2241f,-0.0033f,0.999f,0.0453f,1.4355f,0.457f,0.0418f,-0.8885f,0.1588f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.8955f,0.0371f,-0.4434f,-1.1413f,0.0109f,0.9981f,0.0614f,1.4259f,0.4448f,0.0502f,-0.8942f,0.3267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.9077f,0.0453f,-0.4172f,-1.0584f,0.0147f,0.997f,0.0764f,1.4163f,0.4194f,0.0632f,-0.9056f,0.4946f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.8829f,0.1031f,-0.4581f,-0.7226f,0.0792f,0.9943f,0.0711f,1.4035f,0.4628f,0.0265f,-0.886f,0.3282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-1.5355f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-1.5354f,0f,0f,0f,1.1552f,0f,0f,0f,-1.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.8955f,0.0534f,-0.4418f,-1.0263f,0.0343f,0.9981f,0.0511f,2.3113f,0.4437f,0.0305f,-0.8956f,0.2507f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.8955f,0.0534f,-0.4418f,-1.0263f,0.0343f,0.9981f,0.0511f,2.3113f,0.4437f,0.0305f,-0.8956f,0.2507f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9098f,0.0128f,-0.4148f,-0.7053f,0.0069f,0.9999f,0.0157f,2.4381f,0.4149f,0.0114f,-0.9098f,0.0035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [-0.8042f,-0.2009f,-0.5593f,0.3323f,-0.2889f,0.9546f,0.0724f,2.0267f,0.5194f,0.2198f,-0.8258f,-0.5251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [-0.7557f,-0.2487f,-0.6059f,0.8556f,-0.3638f,0.9287f,0.0725f,1.2391f,0.5446f,0.2752f,-0.7922f,-1.1757f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [-0.783f,-0.2721f,-0.5593f,0.9604f,-0.3731f,0.925f,0.0724f,1.2255f,0.4977f,0.2654f,-0.8258f,-1.0208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [-0.8054f,-0.2764f,-0.5244f,1.0653f,-0.3592f,0.9313f,0.0608f,1.2119f,0.4716f,0.2373f,-0.8493f,-0.866f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [-0.7948f,-0.1727f,-0.5817f,0.7637f,-0.2486f,0.9672f,0.0526f,1.1036f,0.5535f,0.1864f,-0.8117f,-0.6712f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [-0.9642f,-0.2009f,0.1732f,0.6087f,-0.1531f,0.9546f,0.2554f,1.9976f,-0.2166f,0.2198f,-0.9512f,-0.7149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [-0.9642f,-0.2009f,0.1732f,0.6087f,-0.1531f,0.9546f,0.2554f,1.9976f,-0.2166f,0.2198f,-0.9512f,-0.7149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [0f,0f,0f,3.3701f,0f,0f,0f,0.4943f,0f,0f,0f,0.61f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [-0.9248f,-0.1904f,-0.3295f,0.6631f,-0.1896f,0.9812f,-0.0349f,2.4321f,0.33f,0.0302f,-0.9435f,-0.3653f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [-0.9248f,-0.1904f,-0.3295f,0.6631f,-0.1896f,0.9812f,-0.0349f,2.4321f,0.33f,0.0302f,-0.9435f,-0.3653f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.9248f,-0.1904f,-0.3295f,0.2789f,-0.1896f,0.9812f,-0.0349f,2.4381f,0.33f,0.0302f,-0.9435f,-0.3969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9263f,0f,-0.3768f,-0.2721f,0f,1f,0f,1.61f,0.3768f,0f,-0.9263f,-0.3414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.9263f,0f,-0.3768f,-0.2721f,0f,1f,0f,1.61f,0.3768f,0f,-0.9263f,-0.3414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.9085f,0.1661f,-0.3835f,-0.0666f,0f,0.9176f,0.3974f,0.49f,0.418f,0.3611f,-0.8336f,0.1053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.9085f,0.0536f,-0.4145f,-0.037f,0f,0.9917f,0.1283f,0.9881f,0.418f,0.1165f,-0.901f,0.1696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9044f,0.0862f,-0.418f,-0.539f,0.0949f,0.9955f,0f,0.985f,0.4161f,-0.0397f,-0.9085f,0.1253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9044f,-0.0862f,-0.418f,0.256f,-0.0949f,0.9955f,0f,0.985f,0.4161f,0.0397f,-0.9085f,-0.2404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.9085f,-0.0694f,-0.4122f,0.0152f,0f,0.9861f,-0.1659f,0.985f,0.418f,-0.1508f,-0.8959f,0.2831f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.9085f,0.1217f,-0.3999f,-0.2982f,0f,0.9567f,0.2911f,0.985f,0.418f,0.2644f,-0.8691f,-0.3982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.9085f,0f,-0.418f,0f,0f,1f,0f,0.6875f,0.418f,0f,-0.9085f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-1.5354381287,"py":1.1552370699,"pz":-1.3013691025,"ry":327.8595554759,"rx":6.6491620315},"locator_hand":{"px":0.8211816592,"py":1.0554212603,"pz":-0.909884759,"ry":325.8895051278,"rx":4.1507083268}},"interactions":{"interaction_mace":{"px":-1.5354408704,"py":1.15523567,"pz":-1.3013675727,"ry":327.8595554759,"rx":6.6491620315},"interaction_hand":{"px":0.8473188097,"py":0.9923651216,"pz":-0.9646468768,"ry":325.8895051278,"rx":4.1507083268}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/486_locator_locator_cinematic