# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.8465f,0f,0.5324f,0.1802f,0f,1f,0f,0.985f,-0.5324f,0f,-0.8465f,-0.0366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.6357f,-0.2953f,0.7133f,-0.2934f,-0.0597f,0.94f,0.3359f,2.5314f,-0.7697f,0.1709f,-0.6152f,0.33f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.6357f,-0.2953f,0.7133f,-0.2822f,-0.0597f,0.94f,0.3359f,2.5367f,-0.7697f,0.1709f,-0.6152f,0.3204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6357f,-0.2953f,0.7133f,0.1186f,-0.0597f,0.94f,0.3359f,2.5231f,-0.7697f,0.1709f,-0.6152f,-0.0096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.6357f,-0.2953f,0.7133f,-0.0029f,-0.0597f,0.94f,0.3359f,3.0729f,-0.7697f,0.1709f,-0.6152f,0.0481f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.6357f,-0.2953f,0.7133f,0.1186f,-0.0597f,0.94f,0.3359f,2.5231f,-0.7697f,0.1709f,-0.6152f,-0.0096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.8227f,-0.0184f,0.5681f,-0.5494f,0.0023f,0.9994f,0.0357f,1.4327f,-0.5684f,0.0307f,-0.8222f,-0.8855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.8154f,-0.0189f,0.5787f,-0.6581f,0.011f,0.9988f,0.0482f,1.4248f,-0.5789f,0.0456f,-0.8141f,-0.733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.8028f,-0.0251f,0.5957f,-0.7668f,0.0136f,0.9981f,0.0604f,1.417f,-0.5961f,0.0566f,-0.8009f,-0.5804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.8242f,0.0227f,0.5659f,-0.4613f,0.0657f,0.9963f,0.0558f,1.4058f,-0.5625f,0.0832f,-0.8226f,-0.3633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,0.5889f,0f,0f,0f,1.1412f,0f,0f,0f,-1.8482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.8148f,-0.0002f,0.5798f,-0.5355f,0.0298f,0.9987f,0.0421f,2.3106f,-0.579f,0.0516f,-0.8137f,-0.6765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.8148f,-0.0002f,0.5798f,-0.5355f,0.0298f,0.9987f,0.0421f,2.3106f,-0.579f,0.0516f,-0.8137f,-0.6765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.7994f,-0.0045f,0.6008f,-0.165f,0.0048f,0.9999f,0.0139f,2.4381f,-0.6008f,0.014f,-0.7993f,-0.5131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [-0.872f,-0.4556f,0.1791f,0.9925f,-0.3867f,0.8654f,0.3185f,1.8714f,-0.3001f,0.2085f,-0.9308f,0.1685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [-0.7331f,-0.6799f,-0.0135f,1.9449f,-0.6604f,0.707f,0.253f,1.2711f,-0.1625f,0.1944f,-0.9674f,-0.0551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [-0.6794f,-0.7115f,0.1791f,1.9113f,-0.6442f,0.6953f,0.3185f,1.2114f,-0.3512f,0.101f,-0.9308f,0.1194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [-0.6814f,-0.653f,0.3306f,1.8778f,-0.5693f,0.7567f,0.3214f,1.1517f,-0.4601f,0.0308f,-0.8873f,0.294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [-0.9508f,-0.2963f,0.0908f,1.5508f,-0.2671f,0.9321f,0.2446f,1.0067f,-0.1571f,0.2083f,-0.9654f,0.1814f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [-0.4899f,-0.4556f,0.7433f,1.322f,-0.0482f,0.8654f,0.4987f,1.8841f,-0.8704f,0.2085f,-0.446f,0.2362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [-0.4899f,-0.4556f,0.7433f,1.322f,-0.0482f,0.8654f,0.4987f,1.8841f,-0.8704f,0.2085f,-0.446f,0.2362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [0f,0f,0f,2.5616f,0f,0f,0f,-0.0366f,0f,0f,0f,2.7691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [-0.6975f,-0.008f,0.7165f,0.7904f,-0.1722f,0.9725f,-0.1567f,2.4458f,-0.6956f,-0.2326f,-0.6797f,0.5176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [-0.6975f,-0.008f,0.7165f,0.7904f,-0.1722f,0.9725f,-0.1567f,2.4458f,-0.6956f,-0.2326f,-0.6797f,0.5176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.6975f,-0.008f,0.7165f,0.6619f,-0.1722f,0.9725f,-0.1567f,2.4381f,-0.6956f,-0.2326f,-0.6797f,0.1541f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.7783f,0f,0.6279f,0.3466f,0f,1f,0f,1.61f,-0.6279f,0f,-0.7783f,-0.3011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.7783f,0f,0.6279f,0.3466f,0f,1f,0f,1.61f,-0.6279f,0f,-0.7783f,-0.3011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.8465f,-0.1044f,0.522f,0.0545f,0f,0.9806f,0.1962f,0.4852f,-0.5324f,0.166f,-0.8301f,0.1634f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.8465f,-0.008f,0.5323f,0.0471f,0f,0.9999f,0.015f,0.9881f,-0.5324f,0.0127f,-0.8464f,0.1751f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.8455f,0.042f,0.5324f,-0.1901f,0.0496f,0.9988f,0f,0.985f,-0.5317f,0.0264f,-0.8465f,-0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.8455f,-0.042f,0.5324f,0.5506f,-0.0496f,0.9988f,0f,0.985f,-0.5317f,-0.0264f,-0.8465f,0.1963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.8465f,0.1121f,0.5204f,-0.0194f,0f,0.9776f,-0.2106f,0.985f,-0.5324f,-0.1783f,-0.8275f,0.2809f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.8465f,-0.1199f,0.5187f,0.3799f,0f,0.9743f,0.2252f,0.985f,-0.5324f,0.1906f,-0.8248f,-0.354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.8465f,0f,0.5324f,0f,0f,1f,0f,0.6875f,-0.5324f,0f,-0.8465f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":0.588876806,"py":1.1412208279,"pz":-1.8481918702,"ry":29.5782925789,"rx":6.1112578285},"locator_hand":{"px":1.7660554504,"py":1.0232950718,"pz":0.0550907051,"ry":10.8929459383,"rx":18.5741146832}},"interactions":{"interaction_mace":{"px":0.5888741585,"py":1.1412194151,"pz":-1.8481935468,"ry":17.0061931332,"rx":-8.9414051756},"interaction_hand":{"px":1.8332678392,"py":0.9766169749,"pz":0.0240783388,"ry":10.8929459383,"rx":18.5741146832}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/496_locator_locator_cinematic