# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.5673f,0f,0.8235f,0.2788f,0f,1f,0f,0.985f,-0.8235f,0f,-0.5673f,0.058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.1579f,-0.3276f,0.9315f,-0.318f,-0.0449f,0.9448f,0.3246f,2.538f,-0.9864f,0.0094f,-0.1639f,0.1376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.1579f,-0.3276f,0.9315f,-0.3035f,-0.0449f,0.9448f,0.3246f,2.543f,-0.9864f,0.0094f,-0.1639f,0.1351f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.1579f,-0.3276f,0.9315f,0.2092f,-0.0449f,0.9448f,0.3246f,2.5231f,-0.9864f,0.0094f,-0.1639f,0.0539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.1579f,-0.3276f,0.9315f,0.0831f,-0.0449f,0.9448f,0.3246f,3.0749f,-0.9864f,0.0094f,-0.1639f,0.049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.1579f,-0.3276f,0.9315f,0.2092f,-0.0449f,0.9448f,0.3246f,2.5231f,-0.9864f,0.0094f,-0.1639f,0.0539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.5083f,-0.0219f,0.8609f,-0.0438f,0.0045f,0.9996f,0.0281f,1.4305f,-0.8611f,0.0182f,-0.508f,-1.0117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.4986f,-0.0278f,0.8664f,-0.2064f,0.01f,0.9992f,0.0378f,1.4241f,-0.8668f,0.0275f,-0.498f,-0.9185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.4844f,-0.036f,0.8741f,-0.3689f,0.0119f,0.9988f,0.0477f,1.4177f,-0.8748f,0.0335f,-0.4834f,-0.8252f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.511f,-0.0102f,0.8595f,-0.182f,0.0538f,0.9976f,0.0438f,1.4083f,-0.8579f,0.0686f,-0.5092f,-0.5002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1294f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1294f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1294f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1294f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1294f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1294f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1294f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1294f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1293f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1293f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,1.3912f,0f,0f,0f,1.1293f,0f,0f,0f,-1.4085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.4983f,-0.0172f,0.8668f,-0.1145f,0.025f,0.9991f,0.0342f,2.3103f,-0.8667f,0.0387f,-0.4974f,-0.8231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.4983f,-0.0172f,0.8668f,-0.1145f,0.025f,0.9991f,0.0342f,2.3103f,-0.8667f,0.0387f,-0.4974f,-0.8231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.4794f,-0.0087f,0.8775f,0.1554f,0.0035f,0.9999f,0.0118f,2.4381f,-0.8776f,0.0087f,-0.4794f,-0.5214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [-0.5652f,-0.4846f,0.6677f,0.6903f,-0.5041f,0.8435f,0.1855f,1.6456f,-0.653f,-0.2318f,-0.721f,0.6957f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [-0.4948f,-0.736f,0.462f,1.6003f,-0.828f,0.5606f,0.0064f,1.1047f,-0.2637f,-0.3794f,-0.8869f,1.1393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [-0.261f,-0.6972f,0.6677f,1.4751f,-0.8487f,0.4953f,0.1855f,1.07f,-0.46f,-0.5182f,-0.721f,1.2744f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [-0.1718f,-0.566f,0.8063f,1.35f,-0.7622f,0.5949f,0.2553f,1.0352f,-0.6242f,-0.5707f,-0.5336f,1.4096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [-0.7725f,-0.2854f,0.5673f,1.138f,-0.3027f,0.9508f,0.0661f,0.8461f,-0.5582f,-0.1207f,-0.8209f,1.1647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0.0725f,-0.4846f,0.8717f,0.9275f,-0.2253f,0.8435f,0.4876f,1.6977f,-0.9716f,-0.2318f,-0.048f,0.9288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0.0725f,-0.4846f,0.8717f,0.9275f,-0.2253f,0.8435f,0.4876f,1.6977f,-0.9716f,-0.2318f,-0.048f,0.9288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [0f,0f,0f,0.5371f,0f,0f,0f,0.309f,0f,0f,0f,4.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [-0.314f,0.2093f,0.9261f,0.5854f,-0.158f,0.9503f,-0.2684f,2.4602f,-0.9362f,-0.2306f,-0.2653f,0.8062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [-0.314f,0.2093f,0.9261f,0.5854f,-0.158f,0.9503f,-0.2684f,2.4602f,-0.9362f,-0.2306f,-0.2653f,0.8062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.314f,0.2093f,0.9261f,0.6385f,-0.158f,0.9503f,-0.2684f,2.4381f,-0.9362f,-0.2306f,-0.2653f,0.4249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.4547f,0f,0.8907f,0.5362f,0f,1f,0f,1.61f,-0.8907f,0f,-0.4547f,-0.1193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.4547f,0f,0.8907f,0.5362f,0f,1f,0f,1.61f,-0.8907f,0f,-0.4547f,-0.1193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.5673f,-0.1172f,0.8152f,0.0817f,0f,0.9898f,0.1423f,0.4851f,-0.8235f,0.0807f,-0.5615f,0.1938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.5673f,-0.0071f,0.8235f,0.0729f,0f,1f,0.0087f,0.9881f,-0.8235f,0.0049f,-0.5672f,0.1998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.5666f,0.0267f,0.8235f,0.0306f,0.0471f,0.9989f,0f,0.985f,-0.8226f,0.0388f,-0.5673f,-0.3023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.5666f,-0.0267f,0.8235f,0.527f,-0.0471f,0.9989f,0f,0.985f,-0.8226f,-0.0388f,-0.5673f,0.4183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.5673f,0.1755f,0.8046f,-0.03f,0f,0.977f,-0.2131f,0.985f,-0.8235f,-0.1209f,-0.5542f,0.2707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.5673f,-0.1824f,0.8031f,0.5876f,0f,0.9752f,0.2215f,0.985f,-0.8235f,0.1257f,-0.5532f,-0.1548f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.5673f,0f,0.8235f,0f,0f,1f,0f,0.6875f,-0.8235f,0f,-0.5673f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":1.391206288,"py":1.1293450451,"pz":-1.4085014927,"ry":54.2460321137,"rx":5.6318299789},"locator_hand":{"px":1.3874454922,"py":0.8620577459,"pz":1.1758655466,"ry":42.8015653352,"rx":10.6874240079}},"interactions":{"interaction_mace":{"px":1.3912045765,"py":1.1293436187,"pz":-1.4085041104,"ry":41.716103327,"rx":-9.4585489234},"interaction_hand":{"px":1.4600379912,"py":0.8172855301,"pz":1.1954587749,"ry":42.8015653352,"rx":10.6874240079}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/503_locator_locator_cinematic