# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.4371f,0f,0.8994f,0.3045f,0f,1f,0f,0.985f,-0.8994f,0f,-0.4371f,0.102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.1556f,-0.3127f,0.937f,-0.2821f,-0.002f,0.9487f,0.3163f,2.5429f,-0.9878f,0.0474f,-0.1482f,0.1933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.1556f,-0.3127f,0.937f,-0.2675f,-0.002f,0.9487f,0.3163f,2.5478f,-0.9878f,0.0474f,-0.1482f,0.1909f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.1556f,-0.3127f,0.937f,0.245f,-0.002f,0.9487f,0.3163f,2.5231f,-0.9878f,0.0474f,-0.1482f,0.1103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.1556f,-0.3127f,0.937f,0.1277f,-0.002f,0.9487f,0.3163f,3.0765f,-0.9878f,0.0474f,-0.1482f,0.1276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.1556f,-0.3127f,0.937f,0.245f,-0.002f,0.9487f,0.3163f,2.5231f,-0.9878f,0.0474f,-0.1482f,0.1103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.4066f,-0.0105f,0.9136f,0.0823f,0.0045f,0.9999f,0.0135f,1.4263f,-0.9136f,0.0096f,-0.4065f,-0.9584f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.4008f,-0.0142f,0.9161f,-0.0895f,0.006f,0.9998f,0.0181f,1.423f,-0.9162f,0.0127f,-0.4006f,-0.8833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.3939f,-0.0186f,0.919f,-0.2613f,0.0067f,0.9997f,0.0231f,1.4198f,-0.9191f,0.0152f,-0.3936f,-0.8082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.4077f,-0.0078f,0.9131f,-0.111f,0.0277f,0.9994f,0.0209f,1.4148f,-0.9127f,0.0338f,-0.4073f,-0.4647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,1.5486f,0f,0f,0f,1.1052f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,1.5487f,0f,0f,0f,1.1052f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,1.5487f,0f,0f,0f,1.1052f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,1.5487f,0f,0f,0f,1.1052f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,1.5487f,0f,0f,0f,1.1052f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,1.5487f,0f,0f,0f,1.1052f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,1.5487f,0f,0f,0f,1.1052f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,1.5486f,0f,0f,0f,1.1052f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,1.5486f,0f,0f,0f,1.1052f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,1.5486f,0f,0f,0f,1.1051f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,1.5486f,0f,0f,0f,1.1051f,0f,0f,0f,-1.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.4007f,-0.0105f,0.9161f,0.001f,0.0134f,0.9998f,0.0173f,2.31f,-0.9161f,0.0192f,-0.4005f,-0.7939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.4007f,-0.0105f,0.9161f,0.001f,0.0134f,0.9998f,0.0173f,2.31f,-0.9161f,0.0192f,-0.4005f,-0.7939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.3905f,-0.0053f,0.9206f,0.2404f,0.0014f,1f,0.0064f,2.4381f,-0.9206f,0.0038f,-0.3905f,-0.4676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0.1358f,0.6716f,0.7284f,-0.8713f,-0.845f,0.4623f,-0.2688f,0.8096f,-0.5173f,-0.579f,0.6303f,0.4384f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [-0.5325f,0.5513f,0.6423f,-1.4785f,-0.7576f,0.028f,-0.6521f,0.7457f,-0.3775f,-0.8338f,0.4027f,1.4103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [-0.3252f,0.6031f,0.7284f,-1.615f,-0.9453f,-0.185f,-0.2688f,0.7961f,-0.0274f,-0.7759f,0.6303f,1.2921f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [-0.0453f,0.7695f,0.6371f,-1.7516f,-0.9959f,-0.0848f,0.0316f,0.8465f,0.0783f,-0.633f,0.7702f,1.1739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0.1266f,0.6637f,0.7372f,-1.7007f,-0.5972f,0.6444f,-0.4776f,0.5297f,-0.792f,-0.3799f,0.4779f,0.98f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0.611f,0.6716f,0.419f,-0.9977f,-0.7876f,0.4623f,0.4074f,1.0158f,0.0799f,-0.579f,0.8114f,0.6724f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0.611f,0.6716f,0.419f,-0.9977f,-0.7876f,0.4623f,0.4074f,1.0158f,0.0799f,-0.579f,0.8114f,0.6724f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [0f,0f,0f,-4.2889f,0f,0f,0f,1.8971f,0f,0f,0f,0.4925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [-0.1716f,0.4191f,0.8916f,0.5282f,-0.1392f,0.8856f,-0.4431f,2.486f,-0.9753f,-0.2001f,-0.0936f,0.8819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [-0.1716f,0.4191f,0.8916f,0.5282f,-0.1392f,0.8856f,-0.4431f,2.486f,-0.9753f,-0.2001f,-0.0936f,0.8819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.1716f,0.4191f,0.8916f,0.6413f,-0.1392f,0.8856f,-0.4431f,2.4381f,-0.9753f,-0.2001f,-0.0936f,0.5164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.3773f,0f,0.9261f,0.5856f,0f,1f,0f,1.61f,-0.9261f,0f,-0.3773f,-0.0346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.3773f,0f,0.9261f,0.5856f,0f,1f,0f,1.61f,-0.9261f,0f,-0.3773f,-0.0346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.4371f,-0.2946f,0.8498f,0.149f,0f,0.9448f,0.3275f,0.4909f,-0.8994f,0.1432f,-0.413f,0.1776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.4371f,-0.1267f,0.8904f,0.0796f,0f,0.99f,0.1409f,0.9881f,-0.8994f,0.0616f,-0.4327f,0.2113f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.4349f,0.0437f,0.8994f,0.1133f,0.1f,0.995f,0f,0.985f,-0.8949f,0.09f,-0.4371f,-0.2915f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.4349f,-0.0437f,0.8994f,0.4957f,-0.1f,0.995f,0f,0.985f,-0.8949f,-0.09f,-0.4371f,0.4955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.4371f,0.1447f,0.8877f,-0.0328f,0f,0.987f,-0.1609f,0.985f,-0.8994f,-0.0703f,-0.4314f,0.2659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.4371f,-0.2684f,0.8585f,0.6418f,0f,0.9544f,0.2984f,0.985f,-0.8994f,0.1304f,-0.4172f,-0.0619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.4371f,0f,0.8994f,0f,0f,1f,0f,0.6875f,-0.8994f,0f,-0.4371f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":1.5486323718,"py":1.1051472785,"pz":-1.1910373439,"ry":60.4494760946,"rx":4.6018803907},"locator_hand":{"px":-1.6782032172,"py":0.5674324052,"pz":1.2262569418,"ry":130.8710143766,"rx":-15.5935435523}},"interactions":{"interaction_mace":{"px":1.5486309401,"py":1.1051458193,"pz":-1.1910401074,"ry":48.0276162866,"rx":-10.5856540886},"interaction_hand":{"px":-1.7155190648,"py":0.5510173618,"pz":1.3036920157,"ry":130.8710143766,"rx":-15.5935435523}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/515_locator_locator_cinematic