# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.4323f,0f,0.9017f,0.3053f,0f,1f,0f,0.985f,-0.9017f,0f,-0.4323f,0.1036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.1878f,-0.3131f,0.931f,-0.2762f,0.0085f,0.9473f,0.3203f,2.5406f,-0.9822f,0.0681f,-0.1752f,0.2172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.1878f,-0.3131f,0.931f,-0.2616f,0.0085f,0.9473f,0.3203f,2.5456f,-0.9822f,0.0681f,-0.1752f,0.2144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.1878f,-0.3131f,0.931f,0.248f,0.0085f,0.9473f,0.3203f,2.5231f,-0.9822f,0.0681f,-0.1752f,0.1168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.1878f,-0.3131f,0.931f,0.1301f,0.0085f,0.9473f,0.3203f,3.076f,-0.9822f,0.0681f,-0.1752f,0.1442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.1878f,-0.3131f,0.931f,0.248f,0.0085f,0.9473f,0.3203f,2.5231f,-0.9822f,0.0681f,-0.1752f,0.1168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.4078f,-0.0073f,0.9131f,0.0741f,0.0036f,0.9999f,0.0096f,1.4252f,-0.9131f,0.0072f,-0.4077f,-0.9457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.4035f,-0.01f,0.9149f,-0.0975f,0.0044f,0.9999f,0.0128f,1.4228f,-0.915f,0.0092f,-0.4034f,-0.8701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.3987f,-0.0131f,0.917f,-0.269f,0.0049f,0.9999f,0.0164f,1.4205f,-0.9171f,0.0111f,-0.3986f,-0.7944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.4086f,-0.0054f,0.9127f,-0.1177f,0.02f,0.9997f,0.0148f,1.4168f,-0.9125f,0.0243f,-0.4083f,-0.4513f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,1.5388f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,1.5388f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,1.5388f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,1.5388f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,1.5388f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,1.5388f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,1.5388f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,1.5388f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,1.5388f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,1.5387f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,1.5387f,0f,0f,0f,1.0984f,0f,0f,0f,-1.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.4035f,-0.0075f,0.915f,-0.004f,0.0097f,0.9999f,0.0124f,2.31f,-0.9149f,0.0139f,-0.4034f,-0.7857f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.4035f,-0.0075f,0.915f,-0.004f,0.0097f,0.9999f,0.0124f,2.31f,-0.9149f,0.0139f,-0.4034f,-0.7857f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.3962f,-0.0039f,0.9182f,0.2375f,0.001f,1f,0.0047f,2.4381f,-0.9182f,0.0027f,-0.3962f,-0.4609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0.3541f,0.8332f,0.4248f,-1.3213f,-0.8343f,0.4866f,-0.2589f,0.665f,-0.4224f,-0.2627f,0.8675f,0.1663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [-0.2801f,0.8597f,0.4272f,-2.263f,-0.7455f,0.0855f,-0.6609f,0.5731f,-0.6047f,-0.5036f,0.617f,0.816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [-0.2397f,0.873f,0.4248f,-2.3426f,-0.9562f,-0.1365f,-0.2589f,0.6216f,-0.168f,-0.4682f,0.8675f,0.6534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [-0.0024f,0.9569f,0.2903f,-2.4223f,-0.9983f,-0.0194f,0.0556f,0.6702f,0.0588f,-0.2897f,0.9553f,0.4907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [0.3358f,0.786f,0.519f,-2.2895f,-0.6647f,0.5882f,-0.4606f,0.3573f,-0.6673f,-0.1903f,0.72f,0.3323f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0.5508f,0.8332f,0.0499f,-1.5362f,-0.7731f,0.4866f,0.4069f,0.8649f,0.3147f,-0.2627f,0.9121f,0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0.5508f,0.8332f,0.0499f,-1.5362f,-0.7731f,0.4866f,0.4069f,0.8649f,0.3147f,-0.2627f,0.9121f,0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [0f,0f,0f,-4.5076f,0f,0f,0f,1.666f,0f,0f,0f,-1.1419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [-0.1692f,0.4512f,0.8762f,0.5344f,-0.1368f,0.8697f,-0.4742f,2.4913f,-0.976f,-0.2001f,-0.0854f,0.8834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [-0.1692f,0.4512f,0.8762f,0.5344f,-0.1368f,0.8697f,-0.4742f,2.4913f,-0.976f,-0.2001f,-0.0854f,0.8834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.1692f,0.4512f,0.8762f,0.6484f,-0.1368f,0.8697f,-0.4742f,2.4381f,-0.976f,-0.2001f,-0.0854f,0.5189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.3867f,0f,0.9222f,0.5871f,0f,1f,0f,1.61f,-0.9222f,0f,-0.3867f,-0.0314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.3867f,0f,0.9222f,0.5871f,0f,1f,0f,1.61f,-0.9222f,0f,-0.3867f,-0.0314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.4323f,-0.351f,0.8306f,0.165f,0f,0.9211f,0.3893f,0.4939f,-0.9017f,0.1683f,-0.3982f,0.1709f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.4323f,-0.1583f,0.8877f,0.0798f,0f,0.9845f,0.1755f,0.9881f,-0.9017f,0.0759f,-0.4256f,0.2117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.4295f,0.0493f,0.9017f,0.1161f,0.114f,0.9935f,0f,0.985f,-0.8959f,0.1028f,-0.4323f,-0.2909f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.4295f,-0.0493f,0.9017f,0.4944f,-0.114f,0.9935f,0f,0.985f,-0.8959f,-0.1028f,-0.4323f,0.4982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.4323f,0.1326f,0.8919f,-0.0329f,0f,0.9891f,-0.1471f,0.985f,-0.9017f,-0.0636f,-0.4276f,0.2658f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.4323f,-0.2871f,0.8548f,0.6434f,0f,0.948f,0.3184f,0.985f,-0.9017f,0.1376f,-0.4098f,-0.0585f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.4323f,0f,0.9017f,0f,0f,1f,0f,0.6875f,-0.9017f,0f,-0.4323f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":1.5387356994,"py":1.0983797599,"pz":-1.1811312044,"ry":60.2597655363,"rx":4.3020051037},"locator_hand":{"px":-2.3679057754,"py":0.3922969727,"pz":0.5672831862,"ry":153.911819068,"rx":-15.0063503202}},"interactions":{"interaction_mace":{"px":1.5387342548,"py":1.0983782903,"pz":-1.1811339557,"ry":60.2597655363,"rx":4.3020051037},"interaction_hand":{"px":-2.4324683327,"py":0.3739220842,"pz":0.6234272553,"ry":153.911819068,"rx":-15.0063503202}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/518_locator_locator_cinematic