# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.4022f,0f,0.9155f,0.3099f,0f,1f,0f,0.985f,-0.9155f,0f,-0.4022f,0.1138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose_armor) {transformation: [-0.147f,-0.333f,0.9314f,-0.2747f,0.0283f,0.9398f,0.3404f,2.5291f,-0.9887f,0.0764f,-0.1287f,0.2067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.147f,-0.333f,0.9314f,-0.2601f,0.0283f,0.9398f,0.3404f,2.5345f,-0.9887f,0.0764f,-0.1287f,0.2047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.147f,-0.333f,0.9314f,0.2535f,0.0283f,0.9398f,0.3404f,2.5231f,-0.9887f,0.0764f,-0.1287f,0.1281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-0.147f,-0.333f,0.9314f,0.1244f,0.0283f,0.9398f,0.3404f,3.0731f,-0.9887f,0.0764f,-0.1287f,0.163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-0.147f,-0.333f,0.9314f,0.2535f,0.0283f,0.9398f,0.3404f,2.5231f,-0.9887f,0.0764f,-0.1287f,0.1281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.3641f,0f,0.9314f,0.1042f,0f,1f,0f,1.4225f,-0.9314f,0f,-0.3641f,-0.9268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.3641f,0f,0.9314f,-0.0704f,0f,1f,0f,1.4225f,-0.9314f,0f,-0.3641f,-0.8586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.3641f,0f,0.9314f,-0.2451f,0f,1f,0f,1.4225f,-0.9314f,0f,-0.3641f,-0.7903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.3641f,0f,0.9314f,-0.1086f,0f,1f,0f,1.4225f,-0.9314f,0f,-0.3641f,-0.4411f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,1.5749f,0f,0f,0f,1.0816f,0f,0f,0f,-1.0951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.3641f,0f,0.9314f,0.0265f,0f,1f,0f,2.31f,-0.9314f,0f,-0.3641f,-0.7824f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.3641f,0f,0.9314f,0.0265f,0f,1f,0f,2.31f,-0.9314f,0f,-0.3641f,-0.7824f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.3641f,0f,0.9314f,0.2571f,0f,1f,0f,2.4381f,-0.9314f,0f,-0.3641f,-0.4498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(armed_armor_left) {transformation: [0.4567f,0.7491f,0.4798f,-1.6788f,-0.8093f,0.5738f,-0.1256f,0.6424f,-0.3694f,-0.3309f,0.8683f,-0.2413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left) {transformation: [0.227f,0.8282f,0.5124f,-2.5806f,-0.6787f,0.5118f,-0.5267f,0.4749f,-0.6985f,-0.2282f,0.6783f,0.4487f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left1) {transformation: [0.2555f,0.8394f,0.4798f,-2.6706f,-0.9268f,0.3539f,-0.1256f,0.4985f,-0.2752f,-0.4126f,0.8683f,0.2859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_left2) {transformation: [0.4859f,0.7907f,0.3724f,-2.7606f,-0.8728f,0.4614f,0.1593f,0.522f,-0.0459f,-0.4025f,0.9143f,0.123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_left) {transformation: [-0.21f,0.7166f,0.6652f,-2.5893f,-0.9314f,0.0602f,-0.359f,0.2185f,-0.2973f,-0.6949f,0.6548f,-0.0155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm1) {transformation: [0.6622f,0.7491f,0.0163f,-1.9152f,-0.6611f,0.5738f,0.4834f,0.8236f,0.3528f,-0.3309f,0.8752f,-0.0845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm) {transformation: [0.6622f,0.7491f,0.0163f,-1.9152f,-0.6611f,0.5738f,0.4834f,0.8236f,0.3528f,-0.3309f,0.8752f,-0.0845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left) {transformation: [0f,0f,0f,-5.0077f,0f,0f,0f,1.0827f,0f,0f,0f,-1.5023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [-0.1239f,0.502f,0.8559f,0.5136f,-0.1371f,0.8457f,-0.5158f,2.4998f,-0.9828f,-0.1813f,-0.0359f,0.8974f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [-0.1239f,0.502f,0.8559f,0.5136f,-0.1371f,0.8457f,-0.5158f,2.4998f,-0.9828f,-0.1813f,-0.0359f,0.8974f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.1239f,0.502f,0.8559f,0.6439f,-0.1371f,0.8457f,-0.5158f,2.4381f,-0.9828f,-0.1813f,-0.0359f,0.5398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.3641f,0f,0.9314f,0.596f,0f,1f,0f,1.61f,-0.9314f,0f,-0.3641f,-0.0119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest_armor) {transformation: [-0.3641f,0f,0.9314f,0.596f,0f,1f,0f,1.61f,-0.9314f,0f,-0.3641f,-0.0119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.4022f,-0.4433f,0.8011f,0.1863f,0f,0.875f,0.4842f,0.4983f,-0.9155f,0.1948f,-0.3519f,0.1681f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.4022f,-0.1982f,0.8938f,0.0811f,0f,0.9763f,0.2164f,0.9881f,-0.9155f,0.0871f,-0.3927f,0.2144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.3988f,0.0525f,0.9155f,0.134f,0.1305f,0.9914f,0f,0.985f,-0.9077f,0.1195f,-0.4022f,-0.2867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.3988f,-0.0525f,0.9155f,0.4859f,-0.1305f,0.9914f,0f,0.985f,-0.9077f,-0.1195f,-0.4022f,0.5144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_front) {transformation: [-0.4022f,0.1195f,0.9077f,-0.0334f,0f,0.9914f,-0.1305f,0.985f,-0.9155f,-0.0525f,-0.3988f,0.2647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-0.4022f,-0.3131f,0.8603f,0.6533f,0f,0.9397f,0.342f,0.985f,-0.9155f,0.1376f,-0.378f,-0.037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belly_armor) {transformation: [-0.4022f,0f,0.9155f,0f,0f,1f,0f,0.6875f,-0.9155f,0f,-0.4022f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":1.5748683676,"py":1.081570714,"pz":-1.0950812694,"ry":62.670929394,"rx":3.5348435416},"locator_hand":{"px":-2.6656006784,"py":0.2615838332,"pz":0.2188456435,"ry":151.0780475047,"rx":-7.2153872709}},"interactions":{"interaction_mace":{"px":1.5748670297,"py":1.081569217,"pz":-1.0950840597,"ry":62.670929394,"rx":3.5348435416},"interaction_hand":{"px":-2.7254252464,"py":0.2391413587,"pz":0.2786409043,"ry":151.0780475047,"rx":-7.2153872709}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/525_locator_locator_cinematic