# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9492f,0.3147f,0.8822f,0f,-0.3147f,0.9492f,3.3099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9887f,0.1499f,1.3787f,0f,-0.1499f,0.9887f,3.2283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8958f,0.4445f,2.752f,0f,-0.4445f,0.8958f,2.7839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8958f,0.4445f,2.8063f,0f,-0.4445f,0.8958f,3.3152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4946f,0.0848f,2.6177f,0f,-0.1272f,0.9964f,3.3045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4946f,0.0848f,2.6177f,0f,-0.1272f,0.9964f,3.3045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9706f,0.2406f,2.0135f,0f,-0.2406f,0.9706f,3.7763f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.9997f,0.0231f,1.5689f,0f,-0.0231f,0.9997f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}