# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0193f,0f,0f,0f,0f,-0.0124f,0.0148f,0.2632f,0f,0.0148f,0.0124f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0184f,0.0058f,0.0004f,-0.0754f,0.0057f,-0.0184f,0.0017f,1.2831f,-0.0009f,0.0015f,0.0193f,-1.1274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0184f,0.0058f,0.0004f,-0.0763f,0.0057f,-0.0184f,0.0017f,1.2874f,-0.0009f,0.0015f,0.0193f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.019f,-0.0033f,0.0007f,-0.9253f,-0.0033f,-0.0173f,0.008f,0.9666f,0.0007f,0.008f,0.0176f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0193f,0.0017f,0f,0f,0.0016f,-0.0181f,0.0066f,0.4255f,-0.0006f,0.0066f,0.0182f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.0911f,0f,0f,0f,0f,1.0802f,0.1537f,0.8132f,0f,-0.1537f,1.0802f,3.221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.0911f,0f,0f,0f,0f,1.0909f,0.0173f,1.362f,0f,-0.0173f,1.0909f,3.2055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.0911f,0f,0f,0f,0f,0.9783f,0.483f,2.8624f,0f,-0.483f,0.9783f,2.7284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.0911f,0f,0f,0f,0f,0.9783f,0.483f,2.9205f,0f,-0.483f,0.9783f,3.3081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.0911f,0f,0f,-0.6001f,0f,1.631f,0.0903f,2.7136f,0f,-0.1355f,1.0873f,3.2914f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.0911f,0f,0f,0.6001f,0f,1.631f,0.0903f,2.7136f,0f,-0.1355f,1.0873f,3.2914f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.0911f,0f,0f,0f,0f,1.0595f,0.2604f,2.0533f,0f,-0.2604f,1.0595f,3.8048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.0911f,0f,0f,0f,0f,1.0908f,0.023f,1.5689f,0f,-0.023f,1.0908f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/58_locator_locator_cinematic