# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.6068f,0.7949f,-1.0507f,0f,-0.7949f,0.6068f,3.9851f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.5148f,0.8573f,-0.797f,0f,-0.8573f,0.5148f,3.5505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,-0.2111f,0.9775f,-0.7801f,0f,-0.9775f,-0.2111f,2.2347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,-0.2111f,0.9775f,-0.2518f,0f,-0.9775f,-0.2111f,2.3124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4991f,-0.0351f,-0.3217f,0f,0.0526f,0.9994f,2.4729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4991f,-0.0351f,-0.3217f,0f,0.0526f,0.9994f,2.4729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.0459f,0.9989f,-0.0416f,0f,-0.9989f,0.0459f,3.1865f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.3769f,0.9263f,-0.496f,0f,-0.9263f,0.3769f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}