# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.96f,0.28f,0.9259f,0f,-0.28f,0.96f,3.2822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9946f,0.1035f,1.4256f,0f,-0.1035f,0.9946f,3.224f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8902f,0.4555f,2.7908f,0f,-0.4555f,0.8902f,2.8083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8902f,0.4555f,2.8517f,0f,-0.4555f,0.8902f,3.3389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4781f,0.1701f,2.6601f,0f,-0.2552f,0.9854f,3.3256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4781f,0.1701f,2.6601f,0f,-0.2552f,0.9854f,3.3256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9748f,0.2233f,2.0475f,0f,-0.2233f,0.9748f,3.7865f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}