# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0004f,0f,0f,0f,0f,-0.0002f,0.0003f,0.2632f,0f,0.0003f,0.0002f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0003f,0.0001f,0f,-0.0762f,0.0001f,-0.0003f,0f,1.2873f,0f,0f,0.0004f,-1.1185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0003f,0.0001f,0f,-0.0763f,0.0001f,-0.0003f,0f,1.2874f,0f,0f,0.0004f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0003f,-0.0001f,0f,-0.9253f,-0.0001f,-0.0003f,0.0001f,0.9666f,0f,0.0001f,0.0003f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0004f,0f,0f,0f,0f,-0.0003f,0.0001f,0.4255f,0f,0.0001f,0.0003f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.0123f,0f,0f,0f,0f,0.6339f,0.7892f,-1.0401f,0f,-0.7892f,0.6339f,3.9795f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.0123f,0f,0f,0f,0f,0.5426f,0.8546f,-0.7724f,0f,-0.8546f,0.5426f,3.5461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.0123f,0f,0f,0f,0f,-0.1939f,0.9935f,-0.7302f,0f,-0.9935f,-0.1939f,2.2128f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.0123f,0f,0f,0f,0f,-0.1939f,0.9935f,-0.1971f,0f,-0.9935f,-0.1939f,2.3021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.0123f,0f,0f,-0.5568f,0f,1.5175f,-0.0345f,-0.271f,0f,0.0518f,1.0117f,2.4633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.0123f,0f,0f,0.5568f,0f,1.5175f,-0.0345f,-0.271f,0f,0.0518f,1.0117f,2.4633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.0123f,0f,0f,0f,0f,0.0659f,1.0101f,-0.0014f,0f,-1.0101f,0.0659f,3.191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.0123f,0f,0f,0f,0f,0.3978f,0.9309f,-0.4664f,0f,-0.9309f,0.3978f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/7_locator_locator_cinematic