# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0334f,0f,0f,0f,0f,-0.0215f,0.0256f,0.2632f,0f,0.0256f,0.0215f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0319f,0.01f,0.0008f,-0.0748f,0.0099f,-0.0318f,0.0029f,1.28f,-0.0016f,0.0026f,0.0333f,-1.134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0319f,0.01f,0.0008f,-0.0763f,0.0099f,-0.0318f,0.0029f,1.2874f,-0.0016f,0.0026f,0.0333f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0329f,-0.0057f,0.0013f,-0.9253f,-0.0057f,-0.0298f,0.0139f,0.9666f,0.0012f,0.0139f,0.0304f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0333f,0.0029f,0f,0f,0.0027f,-0.0313f,0.0114f,0.4255f,-0.001f,0.0114f,0.0314f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.1116f,0f,0f,0f,0f,1.0764f,0.2776f,1.001f,0f,-0.2776f,1.0764f,3.2692f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.1116f,0f,0f,0f,0f,1.1082f,0.0861f,1.5581f,0f,-0.0861f,1.1082f,3.219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.1116f,0f,0f,0f,0f,0.9627f,0.5557f,3.025f,0f,-0.5557f,0.9627f,2.8071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.1116f,0f,0f,0f,0f,0.9627f,0.5557f,3.1223f,0f,-0.5557f,0.9627f,3.3927f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.1116f,0f,0f,-0.6114f,0f,1.6673f,-0.005f,2.9044f,0f,0.0075f,1.1116f,3.3705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.1116f,0f,0f,0.6114f,0f,1.6673f,-0.005f,2.9044f,0f,0.0075f,1.1116f,3.3705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.1116f,0f,0f,0f,0f,1.0858f,0.2381f,2.2188f,0f,-0.2381f,1.0858f,3.8765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.1116f,0f,0f,0f,0f,1.1103f,-0.053f,1.7495f,0f,0.053f,1.1103f,3.5063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/81_locator_locator_cinematic