# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.6274f,0.7787f,-0.978f,0f,-0.7787f,0.6274f,3.959f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.5479f,0.8365f,-0.7075f,0f,-0.8365f,0.5479f,3.5347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,-0.1519f,0.9884f,-0.6161f,0f,-0.9884f,-0.1519f,2.2159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,-0.1519f,0.9884f,-0.0934f,0f,-0.9884f,-0.1519f,2.3253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4993f,-0.0295f,-0.1723f,0f,0.0442f,0.9996f,2.482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4993f,-0.0295f,-0.1723f,0f,0.0442f,0.9996f,2.482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.1037f,0.9946f,0.0659f,0f,-0.9946f,0.1037f,3.2107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.4248f,0.9053f,-0.4029f,0f,-0.9053f,0.4248f,3.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}