# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0424f,0f,0f,0f,0f,-0.0272f,0.0325f,0.2632f,0f,0.0325f,0.0272f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0404f,0.0126f,0.001f,-0.0744f,0.0125f,-0.0403f,0.0037f,1.278f,-0.002f,0.0033f,0.0422f,-1.1382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0404f,0.0126f,0.001f,-0.0763f,0.0125f,-0.0403f,0.0037f,1.2874f,-0.002f,0.0033f,0.0422f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.0417f,-0.0072f,0.0016f,-0.9253f,-0.0073f,-0.0378f,0.0176f,0.9666f,0.0016f,0.0176f,0.0385f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0422f,0.0037f,0f,0f,0.0035f,-0.0397f,0.0145f,0.4255f,-0.0013f,0.0144f,0.0398f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.1195f,0f,0f,0f,0f,1.1007f,0.204f,1.0359f,0f,-0.204f,1.1007f,3.2798f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.1195f,0f,0f,0f,0f,1.1192f,0.027f,1.5988f,0f,-0.027f,1.1192f,3.2593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.1195f,0f,0f,0f,0f,0.9711f,0.557f,3.0789f,0f,-0.557f,0.9711f,2.8689f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.1195f,0f,0f,0f,0f,0.9711f,0.557f,3.1754f,0f,-0.557f,0.9711f,3.4589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.1195f,0f,0f,-0.6157f,0f,1.6784f,-0.0352f,2.9535f,0f,0.0527f,1.1189f,3.4308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.1195f,0f,0f,0.6157f,0f,1.6784f,-0.0352f,2.9535f,0f,0.0527f,1.1189f,3.4308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.1195f,0f,0f,0f,0f,1.0969f,0.2236f,2.2555f,0f,-0.2236f,1.0969f,3.9301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.1195f,0f,0f,0f,0f,1.1174f,-0.0679f,1.7878f,0f,0.0679f,1.1174f,3.5512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/95_locator_locator_cinematic