# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [0.0436f,0f,0f,0f,0f,-0.028f,0.0334f,0.2632f,0f,0.0334f,0.028f,-0.258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [0.0416f,0.013f,0.001f,-0.0743f,0.0129f,-0.0415f,0.0038f,1.2777f,-0.0021f,0.0034f,0.0434f,-1.1387f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0416f,0.013f,0.001f,-0.0763f,0.0129f,-0.0415f,0.0038f,1.2874f,-0.0021f,0.0034f,0.0434f,-1.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [0.043f,-0.0075f,0.0017f,-0.9253f,-0.0075f,-0.039f,0.0181f,0.9666f,0.0016f,0.0181f,0.0396f,-0.9316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [0.0435f,0.0038f,0f,0f,0.0036f,-0.0408f,0.0149f,0.4255f,-0.0013f,0.0149f,0.041f,-0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs3) {transformation: [1.1203f,0f,0f,0f,0f,1.1057f,0.1805f,1.0378f,0f,-0.1805f,1.1057f,3.2774f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1.1203f,0f,0f,0f,0f,1.1203f,0.0088f,1.6014f,0f,-0.0088f,1.1203f,3.266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1.1203f,0f,0f,0f,0f,0.9821f,0.5392f,3.1002f,0f,-0.5392f,0.9821f,2.8883f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1.1203f,0f,0f,0f,0f,0.9821f,0.5392f,3.1857f,0f,-0.5392f,0.9821f,3.4804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1.1203f,0f,0f,-0.6162f,0f,1.679f,-0.0471f,2.9638f,0f,0.0707f,1.1193f,3.4484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1.1203f,0f,0f,0.6162f,0f,1.679f,-0.0471f,2.9638f,0f,0.0707f,1.1193f,3.4484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1.1203f,0f,0f,0f,0f,1.1009f,0.2076f,2.258f,0f,-0.2076f,1.1009f,3.9378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1.1203f,0f,0f,0f,0f,1.1182f,-0.0689f,1.7903f,0f,0.0689f,1.1182f,3.5582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(locator_cinematic) positioned ^5.3125 ^6.375 ^5.5 rotated ~0 ~0 run function aj:echo_knight/animations/spawn/zzz/frames/97_locator_locator_cinematic