# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:ghost_villager_a"
data modify storage animated_java:temp entry.data.rig_hash set value "822db7ed374e707cbae89903f4ac9bc8e298e52fc6a3bba0d2379ed5119aa04b"
tp @s ~ ~ ~ ~ ~
summon minecraft:interaction ^0 ^0.1875 ^0 { Tags:["","aj.ghost_villager_a.entity","aj.ghost_villager_a.interaction","aj.ghost_villager_a.interaction.interaction","aj.ghost_villager_a.node","aj.ghost_villager_a.node.interaction","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.interaction","aj.global.root.child","aj.global.root.child.interaction","aj.new"], response: false, width: 0.5f, height: 1.75f, }
execute as @n[ type=minecraft:interaction, tag=aj.ghost_villager_a.interaction.interaction, tag=aj.new, distance=..1 ] run function aj:ghost_villager_a/zzz/summon/as_interaction/interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.interaction.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.bodywear] run function aj:ghost_villager_a/zzz/summon/as_node/bodywear
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bodywear set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.nose] run function aj:ghost_villager_a/zzz/summon/as_node/nose
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nose set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.headwear] run function aj:ghost_villager_a/zzz/summon/as_node/headwear
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.headwear set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.eyelids] run function aj:ghost_villager_a/zzz/summon/as_node/eyelids
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelids set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.head] run function aj:ghost_villager_a/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.arm1_l] run function aj:ghost_villager_a/zzz/summon/as_node/arm1_l
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm1_l set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.arm_l] run function aj:ghost_villager_a/zzz/summon/as_node/arm_l
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_l set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.arm1_r] run function aj:ghost_villager_a/zzz/summon/as_node/arm1_r
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm1_r set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.arm_r] run function aj:ghost_villager_a/zzz/summon/as_node/arm_r
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_r set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.body] run function aj:ghost_villager_a/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.hovering_legs_ghost_stuff1] run function aj:ghost_villager_a/zzz/summon/as_node/hovering_legs_ghost_stuff1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hovering_legs_ghost_stuff1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.ghost_villager_a.node.hovering_legs_ghost_stuff] run function aj:ghost_villager_a/zzz/summon/as_node/hovering_legs_ghost_stuff
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hovering_legs_ghost_stuff set from storage animated_java:gu out
function aj:ghost_villager_a/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:ghost_villager_a/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:ghost_villager_a/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function aj:ghost_villager_a/zzz/summon/zzz/0 with storage animated_java:temp entry.data.interactions.interaction
execute at @s run function aj:ghost_villager_a/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new