# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9857f,0.1683f,3.2262f,0f,-0.1683f,0.9857f,0.3191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9993f,0.0382f,3.7287f,0f,-0.0382f,0.9993f,0.2937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8632f,0.5048f,5.0897f,0f,-0.5048f,0.8632f,-0.1358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8632f,0.5048f,5.1803f,0f,-0.5048f,0.8632f,0.3905f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4915f,-0.1065f,4.9808f,0f,0.1597f,0.9943f,0.3667f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4915f,-0.1065f,4.9808f,0f,0.1597f,0.9943f,0.3667f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9731f,0.2304f,4.3716f,0f,-0.2304f,0.9731f,0.832f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.9993f,0.0382f,3.9225f,0f,-0.0382f,0.9993f,0.5365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}