# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9896f,0.1437f,3.2318f,0f,-0.1437f,0.9896f,0.3019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9999f,0.0133f,3.7348f,0f,-0.0133f,0.9999f,0.2889f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.9378f,0.3471f,5.2142f,0f,-0.3471f,0.9378f,-0.017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.9378f,0.3471f,5.2119f,0f,-0.3471f,0.9378f,0.517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4869f,-0.1318f,5.0186f,0f,0.1978f,0.9913f,0.4439f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4869f,-0.1318f,5.0186f,0f,0.1978f,0.9913f,0.4439f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9918f,0.1275f,4.3641f,0f,-0.1275f,0.9918f,0.8431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.9999f,0.0133f,3.9225f,0f,-0.0133f,0.9999f,0.5365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}