# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9902f,0.1396f,3.2328f,0f,-0.1396f,0.9902f,0.299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,1f,0.0092f,3.7359f,0f,-0.0092f,1f,0.2882f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.9503f,0.3113f,5.2388f,0f,-0.3113f,0.9503f,0.0096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.9503f,0.3113f,5.2163f,0f,-0.3113f,0.9503f,0.5431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4869f,-0.1321f,5.0253f,0f,0.1982f,0.9912f,0.459f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4869f,-0.1321f,5.0253f,0f,0.1982f,0.9912f,0.459f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9942f,0.1074f,4.3629f,0f,-0.1074f,0.9942f,0.8449f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,1f,0.0092f,3.9225f,0f,-0.0092f,1f,0.5365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}