# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.9999f,-0.014f,5.4187f,0f,0.014f,0.9999f,0.2387f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.9999f,-0.014f,5.2242f,0f,0.014f,0.9999f,0.7361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4999f,-0.014f,5.0643f,0f,0.021f,0.9999f,0.5463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4999f,-0.014f,5.0643f,0f,0.021f,0.9999f,0.5463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9999f,-0.014f,4.36f,0f,0.014f,0.9999f,0.849f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}