# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.9998f,-0.0205f,5.4218f,0f,0.0205f,0.9998f,0.2437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.9998f,-0.0205f,5.224f,0f,0.0205f,0.9998f,0.7397f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.5f,-0.005f,5.065f,0f,0.0075f,1f,0.5479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.5f,-0.005f,5.065f,0f,0.0075f,1f,0.5479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9999f,-0.0163f,4.36f,0f,0.0163f,0.9999f,0.849f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}