# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [-1f,0f,0f,0f,0f,0.9914f,0.1305f,1.4088f,0f,0.1305f,-0.9914f,1.6953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.912f,0f,0f,-1f,1.7015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [-1f,0f,0f,0f,0f,0.866f,0.5f,3.2611f,0f,0.5f,-0.866f,2.0993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [-1f,0f,0f,0f,0f,0.866f,0.5f,3.3487f,0f,0.5f,-0.866f,1.5726f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [-1f,0f,0f,0.55f,0f,1.5f,0f,3.1496f,0f,0f,-1f,1.5956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [-1f,0f,0f,-0.55f,0f,1.5f,0f,3.1496f,0f,0f,-1f,1.5956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [-1f,0f,0f,0f,0f,0.9763f,0.2164f,2.5338f,0f,0.2164f,-0.9763f,1.139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.0963f,0f,0f,-1f,1.4515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}