# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [-1f,0f,0f,0f,0f,0.9914f,0.1305f,1.3643f,0f,0.1305f,-0.9914f,1.7634f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.8674f,0f,0f,-1f,1.7697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [-1f,0f,0f,0f,0f,0.866f,0.5f,3.2165f,0f,0.5f,-0.866f,2.1675f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [-1f,0f,0f,0f,0f,0.866f,0.5f,3.3041f,0f,0.5f,-0.866f,1.6407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [-1f,0f,0f,0.55f,0f,1.5f,0f,3.105f,0f,0f,-1f,1.6638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [-1f,0f,0f,-0.55f,0f,1.5f,0f,3.105f,0f,0f,-1f,1.6638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [-1f,0f,0f,0f,0f,0.9763f,0.2164f,2.4893f,0f,0.2164f,-0.9763f,1.2072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.0518f,0f,0f,-1f,1.5197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}