# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.7732f,0.6342f,3.2456f,0f,-0.6342f,0.7732f,-1.0842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9412f,0.3379f,3.7171f,0f,-0.3379f,0.9412f,-1.2601f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8705f,0.4921f,5.0779f,0f,-0.4921f,0.8705f,-1.7869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8705f,0.4921f,5.1608f,0f,-0.4921f,0.8705f,-1.2594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.2726f,0.5294f,4.9608f,0f,-0.7941f,0.8484f,-1.2608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.2726f,0.5294f,4.9608f,0f,-0.7941f,0.8484f,-1.2608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9546f,0.2978f,4.3856f,0f,-0.2978f,0.9546f,-0.754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.9962f,0.0872f,3.9225f,0f,-0.0872f,0.9962f,-1.0271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}