# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.7813f,0.6242f,3.2448f,0f,-0.6242f,0.7813f,-0.933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9429f,0.3331f,3.7171f,0f,-0.3331f,0.9429f,-1.1065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8707f,0.4918f,5.0781f,0f,-0.4918f,0.8707f,-1.6337f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8707f,0.4918f,5.1608f,0f,-0.4918f,0.8707f,-1.1061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.2724f,0.5295f,4.9608f,0f,-0.7943f,0.8483f,-1.1071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.2724f,0.5295f,4.9608f,0f,-0.7943f,0.8483f,-1.1071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9547f,0.2977f,4.3856f,0f,-0.2977f,0.9547f,-0.6004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.9962f,0.0872f,3.9225f,0f,-0.0872f,0.9962f,-0.8735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}