# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9405f,0.3397f,3.2242f,0f,-0.3397f,0.9405f,0.4046f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.982f,0.1888f,3.7171f,0f,-0.1888f,0.982f,0.3035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8559f,0.5171f,5.0573f,0f,-0.5171f,0.8559f,-0.2325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8559f,0.5171f,5.1554f,0f,-0.5171f,0.8559f,0.2924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4028f,0.3542f,4.9558f,0f,-0.5312f,0.9352f,0.2973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4028f,0.3542f,4.9558f,0f,-0.5312f,0.9352f,0.2973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9517f,0.307f,4.3856f,0f,-0.307f,0.9517f,0.8096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}