# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9442f,0.3295f,3.2234f,0f,-0.3295f,0.9442f,0.4009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9834f,0.1814f,3.7171f,0f,-0.1814f,0.9834f,0.3035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8524f,0.5228f,5.0526f,0f,-0.5228f,0.8524f,-0.2336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8524f,0.5228f,5.1542f,0f,-0.5228f,0.8524f,0.2907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4147f,0.3325f,4.9547f,0f,-0.4987f,0.9431f,0.296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4147f,0.3325f,4.9547f,0f,-0.4987f,0.9431f,0.296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.951f,0.3091f,4.3856f,0f,-0.3091f,0.951f,0.8096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}