# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9617f,0.274f,3.2195f,0f,-0.274f,0.9617f,0.3785f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9906f,0.1368f,3.7171f,0f,-0.1368f,0.9906f,0.3035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8269f,0.5623f,5.0199f,0f,-0.5623f,0.8269f,-0.2401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8269f,0.5623f,5.146f,0f,-0.5623f,0.8269f,0.2788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4747f,0.183f,4.9466f,0f,-0.2744f,0.9831f,0.2872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4747f,0.183f,4.9466f,0f,-0.2744f,0.9831f,0.2872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9461f,0.324f,4.3856f,0f,-0.324f,0.9461f,0.8096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}