# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.968f,0.2509f,3.2181f,0f,-0.2509f,0.968f,0.3684f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9932f,0.1166f,3.7171f,0f,-0.1166f,0.9932f,0.3035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8135f,0.5816f,5.0035f,0f,-0.5816f,0.8135f,-0.2427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8135f,0.5816f,5.1418f,0f,-0.5816f,0.8135f,0.2731f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4912f,0.1084f,4.9425f,0f,-0.1626f,0.9941f,0.2828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4912f,0.1084f,4.9425f,0f,-0.1626f,0.9941f,0.2828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9435f,0.3314f,4.3856f,0f,-0.3314f,0.9435f,0.8096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}