# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9728f,0.2315f,3.2171f,0f,-0.2315f,0.9728f,0.3598f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.995f,0.0996f,3.7171f,0f,-0.0996f,0.995f,0.3035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8017f,0.5978f,4.9897f,0f,-0.5978f,0.8017f,-0.2445f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8017f,0.5978f,5.1383f,0f,-0.5978f,0.8017f,0.2685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4985f,0.0448f,4.9389f,0f,-0.0672f,0.999f,0.2791f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4985f,0.0448f,4.9389f,0f,-0.0672f,0.999f,0.2791f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9413f,0.3377f,4.3856f,0f,-0.3377f,0.9413f,0.8096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}