# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9741f,0.226f,3.2168f,0f,-0.226f,0.9741f,0.3575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9955f,0.0949f,3.7171f,0f,-0.0949f,0.9955f,0.3035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.7984f,0.6021f,4.986f,0f,-0.6021f,0.7984f,-0.2449f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.7984f,0.6021f,5.1373f,0f,-0.6021f,0.7984f,0.2673f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4994f,0.0274f,4.938f,0f,-0.041f,0.9996f,0.2781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4994f,0.0274f,4.938f,0f,-0.041f,0.9996f,0.2781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9406f,0.3394f,4.3856f,0f,-0.3394f,0.9406f,0.8096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}