# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9757f,0.2191f,3.2159f,0f,-0.2191f,0.9757f,0.3555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.996f,0.0899f,3.7164f,0f,-0.0899f,0.996f,0.3041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.7827f,0.6225f,4.9669f,0f,-0.6225f,0.7827f,-0.2504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.7827f,0.6225f,5.1314f,0f,-0.6225f,0.7827f,0.2577f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4997f,-0.0196f,4.932f,0f,0.0294f,0.9998f,0.27f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4997f,-0.0196f,4.932f,0f,0.0294f,0.9998f,0.27f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9363f,0.3511f,4.3863f,0f,-0.3511f,0.9363f,0.8084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.996f,0.0899f,3.9225f,0f,-0.0899f,0.996f,0.5365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}