# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9791f,0.2035f,3.2189f,0f,-0.2035f,0.9791f,0.3442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9973f,0.0739f,3.7202f,0f,-0.0739f,0.9973f,0.3008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.7813f,0.6242f,4.9702f,0f,-0.6242f,0.7813f,-0.2272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.7813f,0.6242f,5.1358f,0f,-0.6242f,0.7813f,0.2805f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4984f,-0.0463f,4.9358f,0f,0.0695f,0.9989f,0.2858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4984f,-0.0463f,4.9358f,0f,0.0695f,0.9989f,0.2858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9416f,0.3368f,4.3819f,0f,-0.3368f,0.9416f,0.8158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.9973f,0.0739f,3.9225f,0f,-0.0739f,0.9973f,0.5365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}