# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ghost_legs3) {transformation: [1f,0f,0f,0f,0f,0.9838f,0.179f,3.2239f,0f,-0.179f,0.9838f,0.3267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs2) {transformation: [1f,0f,0f,0f,0f,0.9988f,0.0491f,3.7261f,0f,-0.0491f,0.9988f,0.2958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose1) {transformation: [1f,0f,0f,0f,0f,0.8345f,0.551f,5.0466f,0f,-0.551f,0.8345f,-0.1701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head1) {transformation: [1f,0f,0f,0f,0f,0.8345f,0.551f,5.1656f,0f,-0.551f,0.8345f,0.3505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_left1) {transformation: [1f,0f,0f,-0.55f,0f,1.4944f,-0.0863f,4.9656f,0f,0.1295f,0.9963f,0.3386f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right1) {transformation: [1f,0f,0f,0.55f,0f,1.4944f,-0.0863f,4.9656f,0f,0.1295f,0.9963f,0.3386f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [1f,0f,0f,0f,0f,0.9635f,0.2678f,4.3748f,0f,-0.2678f,0.9635f,0.8271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_belly) {transformation: [1f,0f,0f,0f,0f,0.9988f,0.0491f,3.9225f,0f,-0.0491f,0.9988f,0.5365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}