# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "re:echo_knight"
data modify storage animated_java:temp entry.data.rig_hash set value "2294ac42dc7cfd5214a7cc2618f383f9ef265af16054ab2e95bdb01d5f4d0148"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=re.echo_knight.node.belly] run function re:echo_knight/zzz/summon/as_node/belly
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.belly set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.nose_armor] run function re:echo_knight/zzz/summon/as_node/nose_armor
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nose_armor set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.nose] run function re:echo_knight/zzz/summon/as_node/nose
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nose set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.head] run function re:echo_knight/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.head_feathers] run function re:echo_knight/zzz/summon/as_node/head_feathers
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head_feathers set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.head_armor] run function re:echo_knight/zzz/summon/as_node/head_armor
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head_armor set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.finger_armor_right] run function re:echo_knight/zzz/summon/as_node/finger_armor_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_armor_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.finger_armor_right1] run function re:echo_knight/zzz/summon/as_node/finger_armor_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_armor_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.finger_armor_right2] run function re:echo_knight/zzz/summon/as_node/finger_armor_right2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_armor_right2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.thumb_armor_right] run function re:echo_knight/zzz/summon/as_node/thumb_armor_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.thumb_armor_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_spike] run function re:echo_knight/zzz/summon/as_node/mace_spike
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_spike set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_spike2] run function re:echo_knight/zzz/summon/as_node/mace_spike2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_spike2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_spike5] run function re:echo_knight/zzz/summon/as_node/mace_spike5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_spike5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_spike1] run function re:echo_knight/zzz/summon/as_node/mace_spike1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_spike1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_spike6] run function re:echo_knight/zzz/summon/as_node/mace_spike6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_spike6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_spike3] run function re:echo_knight/zzz/summon/as_node/mace_spike3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_spike3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_spike4] run function re:echo_knight/zzz/summon/as_node/mace_spike4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_spike4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_ball] run function re:echo_knight/zzz/summon/as_node/mace_ball
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_ball set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_ball2] run function re:echo_knight/zzz/summon/as_node/mace_ball2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_ball2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_handle1] run function re:echo_knight/zzz/summon/as_node/mace_handle1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_handle1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.mace_handle] run function re:echo_knight/zzz/summon/as_node/mace_handle
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mace_handle set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.arm_right] run function re:echo_knight/zzz/summon/as_node/arm_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.arm_armor_right] run function re:echo_knight/zzz/summon/as_node/arm_armor_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_armor_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.shoulder_pad_right] run function re:echo_knight/zzz/summon/as_node/shoulder_pad_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.shoulder_pad_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.finger_armor_left] run function re:echo_knight/zzz/summon/as_node/finger_armor_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_armor_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.finger_armor_left1] run function re:echo_knight/zzz/summon/as_node/finger_armor_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_armor_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.finger_armor_left2] run function re:echo_knight/zzz/summon/as_node/finger_armor_left2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_armor_left2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.thumb_armor_left] run function re:echo_knight/zzz/summon/as_node/thumb_armor_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.thumb_armor_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.ghost_flames_arm1] run function re:echo_knight/zzz/summon/as_node/ghost_flames_arm1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ghost_flames_arm1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.ghost_flames_arm] run function re:echo_knight/zzz/summon/as_node/ghost_flames_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ghost_flames_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.arm_left] run function re:echo_knight/zzz/summon/as_node/arm_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.arm_armor_left] run function re:echo_knight/zzz/summon/as_node/arm_armor_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_armor_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.ghost_flames_shoulder_pad1] run function re:echo_knight/zzz/summon/as_node/ghost_flames_shoulder_pad1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ghost_flames_shoulder_pad1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.ghost_flames_shoulder_pad] run function re:echo_knight/zzz/summon/as_node/ghost_flames_shoulder_pad
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ghost_flames_shoulder_pad set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.shoulder_pad_left] run function re:echo_knight/zzz/summon/as_node/shoulder_pad_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.shoulder_pad_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.chest] run function re:echo_knight/zzz/summon/as_node/chest
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.chest set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.chest_armor] run function re:echo_knight/zzz/summon/as_node/chest_armor
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.chest_armor set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.ghost_legs1] run function re:echo_knight/zzz/summon/as_node/ghost_legs1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ghost_legs1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.ghost_legs] run function re:echo_knight/zzz/summon/as_node/ghost_legs
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ghost_legs set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.cover_leg_left] run function re:echo_knight/zzz/summon/as_node/cover_leg_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.cover_leg_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.cover_leg_right] run function re:echo_knight/zzz/summon/as_node/cover_leg_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.cover_leg_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.cover_leg_front] run function re:echo_knight/zzz/summon/as_node/cover_leg_front
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.cover_leg_front set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.cover_leg_back] run function re:echo_knight/zzz/summon/as_node/cover_leg_back
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.cover_leg_back set from storage animated_java:gu out
execute on passengers if entity @s[tag=re.echo_knight.node.belly_armor] run function re:echo_knight/zzz/summon/as_node/belly_armor
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.belly_armor set from storage animated_java:gu out
function re:echo_knight/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function re:echo_knight/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function re:echo_knight/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new