# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.489f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.9899f,0.1415f,1.6166f,0f,0.1415f,-0.9899f,0.1983f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.9913f,0.1318f,1.4946f,0f,0.1318f,-0.9913f,-0.0701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.1983f,0.1318f,1.7486f,0f,0.0264f,-0.9913f,-0.0364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9913f,0.1318f,1.4946f,0f,0.1318f,-0.9913f,-0.0701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.9984f,0.0551f,-0.013f,0.3707f,0.0491f,0.7298f,-0.6819f,1.1162f,-0.0281f,-0.6814f,-0.7314f,0.2392f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9998f,0.0139f,-0.013f,0.2504f,0.019f,0.7312f,-0.6819f,1.3638f,0f,-0.682f,-0.7314f,0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.9984f,-0.0551f,0.013f,-0.3707f,-0.0491f,0.7298f,-0.6819f,1.1162f,0.0281f,-0.6814f,-0.7314f,0.2392f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9998f,-0.0139f,0.013f,-0.2504f,-0.019f,0.7312f,-0.6819f,1.3638f,0f,-0.682f,-0.7314f,0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.739f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9531f,0.3027f,0.3653f,0f,0.3027f,-0.9531f,0.1175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0185f,0.739f,0f,0.0185f,-0.9998f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.1875f,0f,0f,0f,0.4677f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}