# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5108f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.9692f,0.2463f,1.633f,0f,0.2463f,-0.9692f,0.291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.9575f,0.2884f,1.5554f,0f,0.2884f,-0.9575f,0.0065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [0.08f,0f,0f,0f,0f,-0.0153f,-0.0231f,1.8574f,0f,-0.0046f,0.0766f,0.0975f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9575f,0.2884f,1.5554f,0f,0.2884f,-0.9575f,0.0065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.6185f,-0.7755f,0.1266f,0.4432f,-0.5825f,0.3444f,-0.7363f,1.1926f,0.5274f,-0.5292f,-0.6647f,0.2851f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9821f,-0.0881f,0.1667f,0.2467f,-0.1814f,0.683f,-0.7075f,1.4211f,-0.0516f,-0.7251f,-0.6867f,-0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.6185f,0.7755f,-0.1266f,-0.4432f,0.5825f,0.3444f,-0.7363f,1.1926f,-0.5274f,-0.5292f,-0.6647f,0.2851f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9821f,0.0881f,-0.1667f,-0.2467f,0.1814f,0.683f,-0.7075f,1.4211f,0.0516f,-0.7251f,-0.6867f,-0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7608f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.888f,0.4598f,0.3881f,0f,0.4598f,-0.888f,0.0973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9974f,0.0726f,0.7608f,0f,0.0726f,-0.9974f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}