# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4947f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.8872f,0.4614f,1.4799f,0f,0.4614f,-0.8872f,0.2806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.8602f,0.5099f,1.473f,0f,0.5099f,-0.8602f,-0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-0.624f,0f,0f,0f,0f,0.1074f,0.3182f,1.725f,0f,0.0636f,-0.5368f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.8602f,0.5099f,1.473f,0f,0.5099f,-0.8602f,-0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.64f,-0.7643f,0.0791f,0.3736f,-0.3111f,0.1637f,-0.9362f,1.2055f,0.7025f,-0.6238f,-0.3425f,0.3825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9874f,0.0203f,0.1568f,0.2308f,-0.1295f,0.4647f,-0.876f,1.3699f,-0.0907f,-0.8853f,-0.4562f,0.0122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.64f,0.7643f,-0.0791f,-0.3736f,0.3111f,0.1637f,-0.9362f,1.2055f,-0.7025f,-0.6238f,-0.3425f,0.3825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9874f,-0.0203f,-0.1568f,-0.2308f,0.1295f,0.4647f,-0.876f,1.3699f,0.0907f,-0.8853f,-0.4562f,0.0122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7447f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.8764f,0.4816f,0.3722f,0f,0.4816f,-0.8764f,0.0943f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9968f,0.0805f,0.7447f,0f,0.0805f,-0.9968f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,1.1875f,0f,0f,0f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}