# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4848f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.8192f,0.5736f,1.4393f,0f,0.5736f,-0.8192f,0.2724f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.8192f,0.5736f,1.4547f,0f,0.5736f,-0.8192f,-0.022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.1638f,0.5736f,1.6851f,0f,0.1147f,-0.8192f,0.1393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.8192f,0.5736f,1.4547f,0f,0.5736f,-0.8192f,-0.022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.7896f,-0.5959f,0.1462f,0.4067f,-0.2999f,0.1669f,-0.9392f,1.2432f,0.5353f,-0.7855f,-0.3106f,0.3214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9761f,-0.055f,0.2104f,0.2188f,-0.2142f,0.4097f,-0.8867f,1.3617f,-0.0375f,-0.9106f,-0.4117f,-0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.7896f,0.5959f,-0.1462f,-0.4067f,0.2999f,0.1669f,-0.9392f,1.2432f,-0.5353f,-0.7855f,-0.3106f,0.3214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9761f,0.055f,-0.2104f,-0.2188f,0.2142f,0.4097f,-0.8867f,1.3617f,0.0375f,-0.9106f,-0.4117f,-0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7348f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.8969f,0.4423f,0.3619f,0f,0.4423f,-0.8969f,0.0996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9978f,0.0664f,0.7348f,0f,0.0664f,-0.9978f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}