# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4843f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.9901f,0.1401f,1.6131f,0f,0.1401f,-0.9901f,0.2029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.9907f,0.1364f,1.4924f,0f,0.1364f,-0.9907f,-0.0661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.1981f,0.1364f,1.7463f,0f,0.0273f,-0.9907f,-0.0311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9907f,0.1364f,1.4924f,0f,0.1364f,-0.9907f,-0.0661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.9994f,0.0351f,-0.0083f,0.3723f,0.0313f,0.7307f,-0.6819f,1.1135f,-0.0179f,-0.6818f,-0.7314f,0.2381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9999f,0.0088f,-0.0083f,0.2503f,0.0121f,0.7313f,-0.6819f,1.3604f,0f,-0.682f,-0.7314f,0.0051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.9994f,-0.0351f,0.0083f,-0.3723f,-0.0313f,0.7307f,-0.6819f,1.1135f,0.0179f,-0.6818f,-0.7314f,0.2381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9999f,-0.0088f,0.0083f,-0.2503f,-0.0121f,0.7313f,-0.6819f,1.3604f,0f,-0.682f,-0.7314f,0.0051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7343f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9728f,0.2318f,0.3606f,0f,0.2318f,-0.9728f,0.1262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0049f,0.7343f,0f,-0.0049f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.1875f,0f,0f,0f,0.4113f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}