# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4853f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.9897f,0.1429f,1.6131f,0f,0.1429f,-0.9897f,0.2001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.9907f,0.1358f,1.4923f,0f,0.1358f,-0.9907f,-0.0688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.1981f,0.1358f,1.7461f,0f,0.0272f,-0.9907f,-0.034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9907f,0.1358f,1.4923f,0f,0.1358f,-0.9907f,-0.0688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.9988f,0.0474f,-0.0112f,0.3713f,0.0423f,0.7302f,-0.6819f,1.1132f,-0.0242f,-0.6816f,-0.7314f,0.2388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9999f,0.012f,-0.0112f,0.2504f,0.0164f,0.7313f,-0.6819f,1.3606f,0f,-0.682f,-0.7314f,0.0058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.9988f,-0.0474f,0.0112f,-0.3713f,-0.0423f,0.7302f,-0.6819f,1.1132f,0.0242f,-0.6816f,-0.7314f,0.2388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9999f,-0.012f,0.0112f,-0.2504f,-0.0164f,0.7313f,-0.6819f,1.3606f,0f,-0.682f,-0.7314f,0.0058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7353f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9637f,0.267f,0.3615f,0f,0.267f,-0.9637f,0.1219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,1f,0.0066f,0.7353f,0f,0.0066f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}