# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
execute unless data storage animated_java:temp {entry:{data:{rig_hash: 'fb5bc275c253fa202955a7a5bdb35d72255de97ec16bf4d130b12af5653b9801'}}} run function animated_java:global/remove/outdated_rig
function aj:echo_bell/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack