# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(glowing_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9589f,0.2836f,0.4216f,0f,0.2836f,-0.9589f,-0.1376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece) {transformation: [-1f,0f,0f,0.1146f,0f,0.9589f,0.2836f,0.3433f,0f,0.2836f,-0.9589f,-0.0196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece2) {transformation: [-1f,0f,0f,-0.1458f,0f,0.9589f,0.2836f,0.5619f,0f,0.2836f,-0.9589f,0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece3) {transformation: [-1f,0f,0f,-0.1562f,0f,0.9589f,0.2836f,0.7663f,0f,0.2836f,-0.9589f,-0.0357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece4) {transformation: [-1f,0f,0f,0.1875f,0f,0.9589f,0.2836f,0.7288f,0f,0.2836f,-0.9589f,-0.0468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece5) {transformation: [-1f,0f,0f,-0.2109f,0f,0.9589f,0.2836f,0.3365f,0f,0.2836f,-0.9589f,-0.0976f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece6) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9589f,0.2836f,0.4571f,0f,0.2836f,-0.9589f,-0.2575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece7) {transformation: [-1f,0f,0f,0f,0f,0.9589f,0.2836f,0.6769f,0f,0.2836f,-0.9589f,-0.1925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece8) {transformation: [-1f,0f,0f,0.1563f,0f,0.9589f,0.2836f,0.3883f,0f,0.2836f,-0.9589f,-0.2452f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:echo_bell/animations/ring_bell/zzz/frames/180_root_function