# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(glowing_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9397f,0.342f,0.4289f,0f,0.342f,-0.9397f,-0.1595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece) {transformation: [-1f,0f,0f,0.1146f,0f,0.9397f,0.342f,0.3434f,0f,0.342f,-0.9397f,-0.0465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece2) {transformation: [-1f,0f,0f,-0.1458f,0f,0.9397f,0.342f,0.5596f,0f,0.342f,-0.9397f,-0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece3) {transformation: [-1f,0f,0f,-0.1562f,0f,0.9397f,0.342f,0.7666f,0f,0.342f,-0.9397f,-0.0366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece4) {transformation: [-1f,0f,0f,0.1875f,0f,0.9397f,0.342f,0.7299f,0f,0.342f,-0.9397f,-0.05f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece5) {transformation: [-1f,0f,0f,-0.2109f,0f,0.9397f,0.342f,0.3414f,0f,0.342f,-0.9397f,-0.1248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece6) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9397f,0.342f,0.4716f,0f,0.342f,-0.9397f,-0.277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece7) {transformation: [-1f,0f,0f,0f,0f,0.9397f,0.342f,0.687f,0f,0.342f,-0.9397f,-0.1986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece8) {transformation: [-1f,0f,0f,0.1563f,0f,0.9397f,0.342f,0.4022f,0f,0.342f,-0.9397f,-0.269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:echo_bell/animations/ring_bell/zzz/frames/192_root_function