# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(glowing_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9848f,0.1736f,0.4119f,0f,0.1736f,-0.9848f,-0.0964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece) {transformation: [-1f,0f,0f,0.1146f,0f,0.9848f,0.1736f,0.3474f,0f,0.1736f,-0.9848f,0.0298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece2) {transformation: [-1f,0f,0f,-0.1458f,0f,0.9848f,0.1736f,0.5683f,0f,0.1736f,-0.9848f,0.037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece3) {transformation: [-1f,0f,0f,-0.1562f,0f,0.9848f,0.1736f,0.7659f,0f,0.1736f,-0.9848f,-0.034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece4) {transformation: [-1f,0f,0f,0.1875f,0f,0.9848f,0.1736f,0.7274f,0f,0.1736f,-0.9848f,-0.0407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece5) {transformation: [-1f,0f,0f,-0.2109f,0f,0.9848f,0.1736f,0.3318f,0f,0.1736f,-0.9848f,-0.047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece6) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9848f,0.1736f,0.4337f,0f,0.1736f,-0.9848f,-0.2195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece7) {transformation: [-1f,0f,0f,0f,0f,0.9848f,0.1736f,0.6593f,0f,0.1736f,-0.9848f,-0.1797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece8) {transformation: [-1f,0f,0f,0.1563f,0f,0.9848f,0.1736f,0.3667f,0f,0.1736f,-0.9848f,-0.1995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:echo_bell/animations/ring_bell/zzz/frames/196_root_function