# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(glowing_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,0.4236f,0f,0.3007f,-0.9537f,-0.144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece) {transformation: [-1f,0f,0f,0.1146f,0f,0.9537f,0.3007f,0.3431f,0f,0.3007f,-0.9537f,-0.0274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece2) {transformation: [-1f,0f,0f,-0.1458f,0f,0.9537f,0.3007f,0.5612f,0f,0.3007f,-0.9537f,0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece3) {transformation: [-1f,0f,0f,-0.1562f,0f,0.9537f,0.3007f,0.7663f,0f,0.3007f,-0.9537f,-0.0359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece4) {transformation: [-1f,0f,0f,0.1875f,0f,0.9537f,0.3007f,0.7291f,0f,0.3007f,-0.9537f,-0.0477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece5) {transformation: [-1f,0f,0f,-0.2109f,0f,0.9537f,0.3007f,0.3378f,0f,0.3007f,-0.9537f,-0.1056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece6) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9537f,0.3007f,0.4612f,0f,0.3007f,-0.9537f,-0.2632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece7) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,0.6798f,0f,0.3007f,-0.9537f,-0.1943f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece8) {transformation: [-1f,0f,0f,0.1563f,0f,0.9537f,0.3007f,0.3922f,0f,0.3007f,-0.9537f,-0.2522f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:echo_bell/animations/ring_bell/zzz/frames/33_root_function