# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(glowing_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9962f,-0.0872f,0.4077f,0f,-0.0872f,-0.9962f,0.0014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece) {transformation: [-1f,0f,0f,0.1146f,0f,0.9962f,-0.0872f,0.378f,0f,-0.0872f,-0.9962f,0.14f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece2) {transformation: [-1f,0f,0f,-0.1458f,0f,0.9962f,-0.0872f,0.5932f,0f,-0.0872f,-0.9962f,0.0898f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece3) {transformation: [-1f,0f,0f,-0.1562f,0f,0.9962f,-0.0872f,0.7657f,0f,-0.0872f,-0.9962f,-0.0299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece4) {transformation: [-1f,0f,0f,0.1875f,0f,0.9962f,-0.0872f,0.7268f,0f,-0.0872f,-0.9962f,-0.0265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece5) {transformation: [-1f,0f,0f,-0.2109f,0f,0.9962f,-0.0872f,0.3431f,0f,-0.0872f,-0.9962f,0.0698f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece6) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9962f,-0.0872f,0.3968f,0f,-0.0872f,-0.9962f,-0.1231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece7) {transformation: [-1f,0f,0f,0f,0f,0.9962f,-0.0872f,0.6251f,0f,-0.0872f,-0.9962f,-0.1431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bell_piece8) {transformation: [-1f,0f,0f,0.1563f,0f,0.9962f,-0.0872f,0.3372f,0f,-0.0872f,-0.9962f,-0.0865f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:echo_bell/animations/ring_bell/zzz/frames/42_root_function