# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle block_crumble{block_state:"minecraft:dirt"} ~ ~ ~ 20 3 20 0 20 normal
particle block_crumble{block_state:"minecraft:gravel"} ~ ~ ~ 25 2 25 0 50 normal
playsound echoes:forgotten_echoes.bells.ring block @a ^ ^ ^3 50