# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5126f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6573f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5011f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.2f,0f,1.7573f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5011f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.9985f,-0.0512f,0.0176f,0.3813f,-0.0495f,0.7299f,-0.6818f,1.1534f,0.022f,-0.6816f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9997f,-0.0189f,0.0176f,0.25f,-0.0259f,0.7311f,-0.6818f,1.3954f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.9985f,0.0512f,-0.0176f,-0.3813f,0.0495f,0.7299f,-0.6818f,1.1534f,-0.022f,-0.6816f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9997f,0.0189f,-0.0176f,-0.25f,0.0259f,0.7311f,-0.6818f,1.3954f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7626f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9114f,0.4115f,0.3895f,0f,0.4115f,-0.9114f,0.1036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9985f,0.0556f,0.7626f,0f,0.0556f,-0.9985f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}