# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5054f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6554f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4991f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.2f,0f,1.7554f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4991f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.9996f,-0.0277f,0.0095f,0.3784f,-0.0268f,0.7309f,-0.6819f,1.1424f,0.0119f,-0.6819f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9999f,-0.0102f,0.0095f,0.25f,-0.014f,0.7313f,-0.6819f,1.386f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.9996f,0.0277f,-0.0095f,-0.3784f,0.0268f,0.7309f,-0.6819f,1.1424f,-0.0119f,-0.6819f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9999f,0.0102f,-0.0095f,-0.25f,0.014f,0.7313f,-0.6819f,1.386f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7554f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9573f,0.2892f,0.3817f,0f,0.2892f,-0.9573f,0.1191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.014f,0.7554f,0f,0.014f,-0.9999f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}