# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5132f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6683f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.512f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.2f,0f,1.7683f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.512f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-1f,-0.0051f,0.0018f,0.3756f,-0.0049f,0.7313f,-0.682f,1.1468f,0.0022f,-0.682f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-1f,-0.0019f,0.0018f,0.25f,-0.0026f,0.7314f,-0.682f,1.3918f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-1f,0.0051f,-0.0018f,-0.3756f,0.0049f,0.7313f,-0.682f,1.1468f,-0.0022f,-0.682f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-1f,0.0019f,-0.0018f,-0.25f,0.0026f,0.7314f,-0.682f,1.3918f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7632f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9859f,0.1673f,0.3896f,0f,0.1673f,-0.9859f,0.134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9997f,-0.0259f,0.7632f,0f,-0.0259f,-0.9997f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}