# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5107f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6662f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.51f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.2f,0f,1.7662f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.51f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-1f,-0.0034f,0.0012f,0.3754f,-0.0032f,0.7313f,-0.682f,1.144f,0.0014f,-0.682f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-1f,-0.0012f,0.0012f,0.25f,-0.0017f,0.7314f,-0.682f,1.3892f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-1f,0.0034f,-0.0012f,-0.3754f,0.0032f,0.7313f,-0.682f,1.144f,-0.0014f,-0.682f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-1f,0.0012f,-0.0012f,-0.25f,0.0017f,0.7314f,-0.682f,1.3892f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7607f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9875f,0.1576f,0.3871f,0f,0.1576f,-0.9875f,0.1352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9996f,-0.029f,0.7607f,0f,-0.029f,-0.9996f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}