# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4852f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6381f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4819f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.2f,0f,1.7381f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4819f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.9999f,-0.0149f,0.0051f,0.3768f,-0.0144f,0.7312f,-0.682f,1.1203f,0.0064f,-0.682f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-1f,-0.0055f,0.0051f,0.25f,-0.0075f,0.7313f,-0.682f,1.3647f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.9999f,0.0149f,-0.0051f,-0.3768f,0.0144f,0.7312f,-0.682f,1.1203f,-0.0064f,-0.682f,-0.7314f,0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-1f,0.0055f,-0.0051f,-0.25f,0.0075f,0.7313f,-0.682f,1.3647f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7352f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9753f,0.2207f,0.3615f,0f,0.2207f,-0.9753f,0.1276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0085f,0.7352f,0f,-0.0085f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}