# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.ghost_villager_a.animation.static.playing
tag @s remove aj.ghost_villager_a.animation.spawn.playing
tag @s remove aj.ghost_villager_a.animation.despawn.playing
tag @s remove aj.ghost_villager_a.animation.spawn_funny.playing
tag @s remove aj.ghost_villager_a.animation.idle.playing
tag @s remove aj.ghost_villager_a.animation.wave.playing
tag @s remove aj.ghost_villager_a.animation.no.playing
tag @s remove aj.ghost_villager_a.animation.take_item.playing