# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-0.0047f,0f,0.376f,0f,0f,0.376f,0f,1.032f,-0.376f,0f,-0.0047f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.0047f,0f,0.376f,-0.094f,0f,0.376f,0f,1.0908f,-0.376f,0f,-0.0047f,0.0012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-0.0047f,0f,0.376f,0f,0f,0.376f,0f,1.032f,-0.376f,0f,-0.0047f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-0.0047f,0f,0.376f,0f,0f,0.376f,0f,1.032f,-0.376f,0f,-0.0047f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.0047f,0f,0.376f,0f,0f,0.376f,0f,1.032f,-0.376f,0f,-0.0047f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.0047f,0.2564f,0.275f,-0.087f,0f,0.275f,-0.2564f,0.8939f,-0.376f,-0.0032f,-0.0035f,0.1421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.0047f,0.2564f,0.275f,0f,0f,0.275f,-0.2564f,0.9862f,-0.376f,-0.0032f,-0.0035f,0.094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.0047f,0.2564f,0.275f,-0.0905f,0f,0.275f,-0.2564f,0.8939f,-0.376f,-0.0032f,-0.0035f,-0.1399f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.0047f,0.2564f,0.275f,-0.0024f,0f,0.275f,-0.2564f,0.9862f,-0.376f,-0.0032f,-0.0035f,-0.094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.0047f,0f,0.376f,0f,0f,0.376f,0f,0.75f,-0.376f,0f,-0.0047f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-0.0047f,0f,0.376f,-0.0468f,0f,0.376f,0f,0.6095f,-0.376f,0f,-0.0047f,0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-0.0047f,0f,0.376f,-0.047f,0f,0.376f,0f,0.75f,-0.376f,0f,-0.0047f,0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}