# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:echo_knight rig_hash set value '0c430893952b25b62c78c1d80743606977e6b7ec953875abfc2d4d1055a53049'
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.attack1.frame dummy
scoreboard objectives add aj.attack2.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.hurt.frame dummy
scoreboard objectives add aj.death.frame dummy