# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5602f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,1f,0.004f,1.712f,0f,0.004f,-1f,0.2527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0175f,1.5602f,0f,0.0175f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.2229f,0.0175f,1.8091f,0f,0.0039f,-0.9998f,0.0044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0175f,1.5602f,0f,0.0175f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.9991f,-0.0435f,0.0009f,0.3753f,-0.0331f,0.7462f,-0.6649f,1.1878f,0.0282f,-0.6643f,-0.7469f,0.2304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-1f,-0.0009f,0.0009f,0.25f,-0.0013f,0.7469f,-0.6649f,1.4383f,-0.0001f,-0.6649f,-0.7469f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.9991f,0.0435f,-0.0009f,-0.3753f,0.0331f,0.7462f,-0.6649f,1.1878f,-0.0282f,-0.6643f,-0.7469f,0.2304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-1f,0.0009f,-0.0009f,-0.25f,0.0013f,0.7469f,-0.6649f,1.4383f,0.0001f,-0.6649f,-0.7469f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.8102f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9485f,0.3168f,0.4414f,0f,0.3168f,-0.9485f,0.064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9869f,0.1616f,0.8102f,0f,0.1616f,-0.9869f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}