# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5455f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.9996f,0.0286f,1.6779f,0f,0.0286f,-0.9996f,0.2634f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.9957f,0.0927f,1.5455f,0f,0.0927f,-0.9957f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.3202f,0.0927f,1.7619f,0f,0.0298f,-0.9957f,0.0201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9957f,0.0927f,1.5455f,0f,0.0927f,-0.9957f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.9732f,-0.2301f,0.0053f,0.3768f,-0.1912f,0.7955f,-0.575f,1.1495f,0.128f,-0.5606f,-0.8182f,0.2004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-1f,-0.0052f,0.0053f,0.25f,-0.0073f,0.8181f,-0.575f,1.4236f,-0.0013f,-0.575f,-0.8182f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.9732f,0.2301f,-0.0053f,-0.3768f,0.1912f,0.7955f,-0.575f,1.1495f,-0.128f,-0.5606f,-0.8182f,0.2004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-1f,0.0052f,-0.0053f,-0.25f,0.0073f,0.8181f,-0.575f,1.4236f,0.0013f,-0.575f,-0.8182f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7955f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9252f,0.3794f,0.4321f,0f,0.3794f,-0.9252f,0.0376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9727f,0.2322f,0.7955f,0f,0.2322f,-0.9727f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}