# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.9971f,-0.0756f,1.4391f,0f,-0.0756f,-0.9971f,0.2944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.8192f,0.5736f,1.4545f,0f,0.5736f,-0.8192f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.8192f,0.5736f,1.4545f,0f,0.5736f,-0.8192f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.8192f,0.5736f,1.4545f,0f,0.5736f,-0.8192f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [0.0261f,-0.9997f,-0.0039f,0.3892f,-0.9907f,-0.0254f,-0.1339f,1.0032f,0.1338f,0.0074f,-0.991f,0.0502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9991f,-0.0422f,-0.0039f,0.25f,-0.0413f,0.9901f,-0.1339f,1.3326f,0.0096f,-0.1336f,-0.991f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [0.0261f,0.9997f,0.0039f,-0.3892f,0.9907f,-0.0254f,-0.1339f,1.0032f,-0.1338f,0.0074f,-0.991f,0.0502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9991f,0.0422f,0.0039f,-0.25f,0.0413f,0.9901f,-0.1339f,1.3326f,-0.0096f,-0.1336f,-0.991f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9167f,0.3996f,0.3637f,0f,0.3996f,-0.9167f,-0.0091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.934f,0.3572f,0.7125f,0f,0.3572f,-0.934f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}