# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,0.9822f,0.188f,1.5252f,0f,0.188f,-0.9822f,0.141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.9929f,-0.1191f,1.4303f,0f,-0.1191f,-0.9929f,0.4226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.6967f,0.7173f,1.5007f,0f,0.7173f,-0.6967f,0.1363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.6967f,0.7173f,1.5007f,0f,0.7173f,-0.6967f,0.1363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.6967f,0.7173f,1.5007f,0f,0.7173f,-0.6967f,0.1363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [0.0334f,-0.9994f,-0.0117f,0.3892f,-0.9522f,-0.0283f,-0.3042f,1.0639f,0.3036f,0.0213f,-0.9525f,0.2191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.999f,-0.0422f,-0.0117f,0.25f,-0.0366f,0.9519f,-0.3042f,1.3805f,0.024f,-0.3034f,-0.9525f,0.1164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [0.0334f,0.9994f,0.0117f,-0.3892f,0.9522f,-0.0283f,-0.3042f,1.0639f,-0.3036f,0.0213f,-0.9525f,0.2191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.999f,0.0422f,0.0117f,-0.25f,0.0366f,0.9519f,-0.3042f,1.3805f,-0.024f,-0.3034f,-0.9525f,0.1164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,0.9822f,0.188f,0.7886f,0f,0.188f,-0.9822f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.9543f,0.2987f,0.4133f,0f,0.2987f,-0.9543f,-0.0036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9417f,0.3365f,0.7651f,0f,0.3365f,-0.9417f,0.1228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}