# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(nose) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6563f,0f,0f,-1f,0.25f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(headwear) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(eyelids) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(head) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(arm1_l) { transformation: [-1f,0f,0f,0.375f,0f,0.7314f,-0.682f,1.1328f,0f,-0.682f,-0.7314f,0.2361f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(arm_l) { transformation: [-1f,0f,0f,0.25f,0f,0.7314f,-0.682f,1.3781f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(arm1_r) { transformation: [-1f,0f,0f,-0.375f,0f,0.7314f,-0.682f,1.1328f,0f,-0.682f,-0.7314f,0.2361f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(arm_r) { transformation: [-1f,0f,0f,-0.25f,0f,0.7314f,-0.682f,1.3781f,0f,-0.682f,-0.7314f,0.0031f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(body) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(hovering_legs_ghost_stuff1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3762f,0f,0f,-1f,0.1244f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(hovering_legs_ghost_stuff) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.75f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(item_display) { transformation: [-0.5f,0f,0f,0f,0f,0.4375f,0f,1.1875f,0f,0f,-1f,0.3125f,0f,0f,0f,1f], start_interpolation: 0 }