# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ceapi:global/commands/as_entity/1 {cmd:'tag @s add bossbar.hide'}
function ceapi:global/commands/as_entity/1 {cmd:'data merge entity @s {Invulnerable:1b,NoAI:true}'}
function ceapi:global/commands/as_entity/1 {cmd:'function ceapi:global/music/end'}