# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(nose_armor) {transformation: [-1f,0f,0f,0f,0f,-0.1699f,0.9855f,0.1062f,0f,0.9855f,0.1699f,2.1143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,-0.1699f,0.9855f,0.1062f,0f,0.9855f,0.1699f,2.1143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,-0.1699f,0.9855f,0.6308f,0f,0.9855f,0.1699f,2.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_feathers) {transformation: [-1f,0f,0f,0f,0f,-0.1699f,0.9855f,0.5968f,0f,0.9855f,0.1699f,2.5794f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_armor) {transformation: [-1f,0f,0f,0f,0f,-0.1699f,0.9855f,0.6308f,0f,0.9855f,0.1699f,2.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.6956f,-0.0889f,0.7129f,-1.1826f,0.5677f,-0.6761f,0.4696f,1.3427f,0.4402f,0.7314f,0.5208f,1.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9763f,0.0209f,0.2152f,-1.2991f,0.1435f,-0.6822f,0.717f,1.2159f,0.1618f,0.7309f,0.6631f,1.3382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.9368f,0.0821f,-0.3401f,-1.2793f,-0.3067f,-0.6605f,0.6853f,1.0796f,-0.1684f,0.7464f,0.6439f,1.1862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.9607f,0.0076f,-0.2774f,-0.903f,-0.1454f,-0.8653f,0.4798f,1.0666f,-0.2364f,0.5013f,0.8324f,1.0284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2706f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2706f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2706f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2706f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2706f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2706f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2706f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2706f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2706f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2707f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-1.0703f,0f,0f,0f,1.2707f,0f,0f,0f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9643f,0.2338f,0.1246f,-0.9401f,-0.0904f,-0.7325f,0.6747f,0.6223f,0.2491f,0.6393f,0.7275f,1.863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9643f,0.2338f,0.1246f,-0.9401f,-0.0904f,-0.7325f,0.6747f,0.6223f,0.2491f,0.6393f,0.7275f,1.863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9924f,0.12f,0.0287f,-0.5313f,-0.0289f,-0.4518f,0.8916f,0.6594f,0.12f,0.884f,0.4518f,1.9714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [-0.9688f,-0.0726f,-0.2368f,0.907f,-0.2122f,-0.2493f,0.9449f,0.6042f,-0.1277f,0.9657f,0.2262f,1.9045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [-0.9688f,-0.0726f,-0.2368f,0.907f,-0.2122f,-0.2493f,0.9449f,0.6042f,-0.1277f,0.9657f,0.2262f,1.9045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.9688f,-0.0726f,-0.2368f,0.5312f,-0.2122f,-0.2493f,0.9449f,0.6594f,-0.1277f,0.9657f,0.2262f,1.9714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-1f,0f,0f,0f,0f,-0.5624f,0.8268f,0.3109f,0f,0.8268f,0.5624f,0.0505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-1f,0f,0f,0f,0f,-0.1554f,0.9879f,0.2266f,0f,0.9879f,0.1554f,0.5465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.8014f,0.507f,0.3172f,-0.461f,0.2347f,-0.2212f,0.9466f,0.4762f,0.5501f,0.8331f,0.0583f,0.5325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.8136f,-0.5174f,-0.2651f,0.4375f,-0.1705f,-0.2237f,0.9596f,0.4762f,-0.5558f,0.826f,0.0938f,0.5325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-1f,0f,0f,0f,0f,-0.5018f,0.865f,0.8508f,0f,0.865f,0.5018f,0.5161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-1.070299605,"py":1.2706443593,"pz":1.1552974122,"ry":159.995148249,"rx":42.9309053104}},"interactions":{"interaction_mace":{"px":-1.0703003667,"py":1.270646876,"pz":1.155295198,"ry":159.995148249,"rx":42.9309053104}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args