# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(belly) {transformation: [-0.9714f,0f,0f,0f,0f,0.0424f,0.9705f,0.4762f,0f,0.9705f,-0.0424f,0.5325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-0.9714f,0f,0f,0f,0f,-0.2102f,0.9483f,0.1146f,0f,0.9483f,0.2102f,2.0909f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9714f,0f,0f,0f,0f,-0.2102f,0.9483f,0.6282f,0f,0.9483f,0.2102f,2.0182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right) {transformation: [-0.6578f,-0.1318f,0.7415f,-1.2107f,0.7198f,-0.3996f,0.5676f,1.2839f,0.2215f,0.9071f,0.3578f,1.399f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right1) {transformation: [-0.9792f,0.0295f,0.2007f,-1.3265f,0.1679f,-0.4366f,0.8838f,1.1439f,0.1137f,0.8992f,0.4226f,1.3012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(finger_armor_right2) {transformation: [-0.9586f,0.0863f,-0.2715f,-1.3068f,-0.2832f,-0.3919f,0.8753f,0.9936f,-0.0308f,0.9159f,0.4001f,1.163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(thumb_armor_right) {transformation: [-0.972f,0.0821f,-0.22f,-0.9338f,-0.2276f,-0.56f,0.7966f,0.9734f,-0.0577f,0.8244f,0.563f,0.9982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1852f,0f,0f,0f,1.1084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike2) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1852f,0f,0f,0f,1.1084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike5) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1852f,0f,0f,0f,1.1084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike1) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1852f,0f,0f,0f,1.1084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike6) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1852f,0f,0f,0f,1.1084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike3) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1852f,0f,0f,0f,1.1084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_spike4) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1852f,0f,0f,0f,1.1084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1852f,0f,0f,0f,1.1084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_ball2) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1852f,0f,0f,0f,1.1083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle1) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1853f,0f,0f,0f,1.1083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mace_handle) {transformation: [0f,0f,0f,-1.1032f,0f,0f,0f,1.1853f,0f,0f,0f,1.1083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_right) {transformation: [-0.9561f,0.2656f,0.124f,-0.9417f,-0.0866f,-0.6601f,0.7462f,0.6134f,0.28f,0.7027f,0.6541f,1.8732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_armor_right) {transformation: [-0.9561f,0.2656f,0.124f,-0.9417f,-0.0866f,-0.6601f,0.7462f,0.6134f,0.28f,0.7027f,0.6541f,1.8732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_right) {transformation: [-0.9898f,0.1391f,0.0312f,-0.5313f,-0.0265f,-0.3944f,0.9186f,0.6594f,0.1401f,0.9084f,0.3941f,1.9714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad1) {transformation: [-0.9538f,-0.1051f,-0.1509f,0.9015f,-0.1176f,-0.2637f,0.9275f,0.5731f,-0.1413f,0.929f,0.2462f,1.9071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_shoulder_pad) {transformation: [-0.9538f,-0.1051f,-0.1509f,0.9015f,-0.1176f,-0.2637f,0.9275f,0.5731f,-0.1413f,0.929f,0.2462f,1.9071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(shoulder_pad_left) {transformation: [-0.9819f,-0.1082f,-0.1553f,0.5312f,-0.1211f,-0.2715f,0.9548f,0.6594f,-0.1455f,0.9563f,0.2535f,1.9714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.9714f,0f,0f,0f,0f,0f,0.9714f,0.8157f,0f,0.9714f,0f,1.1432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs1) {transformation: [-0.9714f,0f,0f,0f,0f,-0.3871f,0.8909f,0.228f,0f,0.8909f,0.3871f,0.0577f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_legs) {transformation: [-0.9714f,0f,0f,0f,0f,0.0092f,0.9713f,0.2266f,0f,0.9713f,-0.0092f,0.5465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_left) {transformation: [-0.9097f,0.2987f,0.2884f,-0.4765f,0.2563f,-0.1424f,0.956f,0.4762f,0.3266f,0.9437f,0.053f,0.5325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_right) {transformation: [-0.9316f,-0.3107f,-0.1887f,0.4375f,-0.1498f,-0.1449f,0.978f,0.4762f,-0.3313f,0.9394f,0.0885f,0.5325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cover_leg_back) {transformation: [-1f,0f,0f,0f,0f,-0.163f,0.9866f,0.8508f,0f,0.9866f,0.163f,0.5161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm3) {transformation: [-0.681f,-0.1268f,0.681f,0.9177f,0.6896f,-0.0336f,0.6833f,0.2341f,-0.0656f,0.9625f,0.1136f,1.3035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ghost_flames_arm2) {transformation: [-0.681f,-0.1268f,0.681f,0.9177f,0.6896f,-0.0336f,0.6833f,0.2341f,-0.0656f,0.9625f,0.1136f,1.3035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator_mace":{"px":-1.1031974679,"py":1.1852419055,"pz":1.1083345251,"ry":157.8517437644,"rx":48.7125778334}},"interactions":{"interaction_mace":{"px":-1.103198339,"py":1.1852441725,"pz":1.1083320924,"ry":136.5960966478,"rx":64.7007005193}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args