# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-0.84375 ^0.953125 ^1.3125 ~8.7677390572 ~-17.5838205271
data modify storage animated_java:temp entry.data.interactions.interaction_mace merge value { px: -0.84375, py: 0.953125, pz: 1.3125, ry: 8.7677390572, rx: -17.5838205271 }