# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.514f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.997f,0.0771f,1.6092f,0f,0.0771f,-0.997f,0.279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.9737f,0.2277f,1.514f,0f,0.2277f,-0.9737f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.4876f,0.2277f,1.6697f,0f,0.114f,-0.9737f,0.0364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9737f,0.2277f,1.514f,0f,0.2277f,-0.9737f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.8378f,-0.5459f,0.0109f,0.3802f,-0.5072f,0.7707f,-0.3858f,1.0835f,0.2022f,-0.3287f,-0.9225f,0.137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9998f,-0.0155f,0.0109f,0.25f,-0.0185f,0.9224f,-0.3858f,1.3921f,-0.004f,-0.3859f,-0.9225f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.8378f,0.5459f,-0.0109f,-0.3802f,0.5072f,0.7707f,-0.3858f,1.0835f,-0.2022f,-0.3287f,-0.9225f,0.137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9998f,0.0155f,-0.0109f,-0.25f,0.0185f,0.9224f,-0.3858f,1.3921f,0.004f,-0.3859f,-0.9225f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.764f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.8914f,0.4532f,0.41f,0f,0.4532f,-0.8914f,0.005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.9476f,0.3194f,0.764f,0f,0.3194f,-0.9476f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}