# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:ghost_villager_a/animations/idle/play
attribute @n[distance=..1,type=villager,tag=forgotten_echoes.echo_trader] minecraft:scale base reset
rotate @s facing entity @p