# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bodywear) {transformation: [-1f,0f,0f,0f,0f,0.7518f,0.6594f,1.3632f,0f,0.6594f,-0.7518f,0.4945f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.9469f,0.3215f,1.134f,0f,0.3215f,-0.9469f,0.6851f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(headwear) {transformation: [-1f,0f,0f,0f,0f,0.2376f,0.9714f,1.3397f,0f,0.9714f,-0.2376f,0.4739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyelids) {transformation: [-1f,0f,0f,0f,0f,0.2376f,0.9714f,1.3397f,0f,0.9714f,-0.2376f,0.4739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.2376f,0.9714f,1.3397f,0f,0.9714f,-0.2376f,0.4739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_l) {transformation: [-0.0155f,-0.9997f,-0.0169f,0.3934f,-0.9725f,0.019f,-0.2321f,0.9243f,0.2324f,0.0128f,-0.9725f,0.4734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_l) {transformation: [-0.9983f,-0.0549f,-0.0169f,0.25f,-0.0495f,0.9714f,-0.2321f,1.246f,0.0292f,-0.2309f,-0.9725f,0.3959f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm1_r) {transformation: [-0.0155f,0.9997f,0.0169f,-0.3934f,0.9725f,0.019f,-0.2321f,0.9243f,-0.2324f,0.0128f,-0.9725f,0.4734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_r) {transformation: [-0.9983f,0.0549f,0.0169f,-0.25f,0.0495f,0.9714f,-0.2321f,1.246f,-0.0292f,-0.2309f,-0.9725f,0.3959f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,0.7518f,0.6594f,0.7993f,0f,0.6594f,-0.7518f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff1) {transformation: [-1f,0f,0f,0f,0f,0.8905f,0.4551f,0.4103f,0f,0.4551f,-0.8905f,-0.1198f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hovering_legs_ghost_stuff) {transformation: [-1f,0f,0f,0f,0f,0.8213f,0.5706f,0.7169f,0f,0.5706f,-0.8213f,0.094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}